### ISSUE TITLE
ElementLinePp(2) plotting incorrect

### ISSUE THREAD

**Issue by Vinc0110** [kinnala/scikit-fem#1003]
Comparing a one-dimensional simulation with higher order elements, I noticed a strange behavior of `ElementLinePp()` when used with `p=2`. Other values for `p` seem to be fine. Of course, in this special case it would anyways be better to use `ElementLineP2()`, as stated in the warning message.

![ElementLinePp2](https://user-images.githubusercontent.com/63644854/211097167-b450e7f4-cf93-48e4-ad6b-39c6a2b9c9f2.png)
![ElementLineP2](https://user-images.githubusercontent.com/63644854/211097179-d7352ef5-4887-4b61-a7ef-40db7efad65c.png)

Example code:
``` python
import skfem
from skfem.models.poisson import laplace
from skfem.visuals.matplotlib import plot, show

mesh = skfem.MeshLine(p=[0, 0.2, 0.5, 1.0])

#element = skfem.ElementLineP2()
element = skfem.ElementLinePp(2)
basis = skfem.Basis(mesh, element)

A = skfem.asm(laplace, basis)
b = basis.zeros()
phi = basis.zeros()
phi[basis.get_dofs(lambda x: x == 0)] = -0.5
phi[basis.get_dofs(lambda x: x == 1.0)] = 2.0

phi = skfem.solve(*skfem.condense(A, b, x=phi, D=basis.get_dofs()))

ax = plot(basis, phi)
ax.set_title(f'{type(element).__name__}')
show()
```

**Comment by kinnala** [comment]
It remainds me of #969. Perhaps related or not.

**Comment by kinnala** [comment]
Yes, it's again something to do with 1D plotting. Here is a workaround:
```python
ax = plot(basis, phi, nrefs=0)
```

**Comment by Vinc0110** [comment]
With `nrefs=0` the plot does look correct, thanks for that hint!

Regardless of the plotting, the calculated values are still not identical:

With `ElementLineP2()`:
```
phi = array([-5.00000000e-01,  8.32667268e-17,  7.50000000e-01,  2.00000000e+00, 
-2.50000000e-01,  3.75000000e-01,  1.37500000e+00])
```

With `ElementLinePp(2)`:
```
phi = array([-5.00000000e-01,  5.55111512e-17,  7.50000000e-01,  2.00000000e+00,
0.00000000e+00,  0.00000000e+00,  0.00000000e+00])
```


By the way, my code above was slightly wrong: I messed up the boundary identification.
Replace 
```
phi[basis.get_dofs(lambda x: x == 0)] = -0.5
phi[basis.get_dofs(lambda x: x == 1.0)] = 2.0
```
with
```
phi[basis.get_dofs(lambda x: x[0] == 0)] = -0.5
phi[basis.get_dofs(lambda x: x[0] == 1.0)] = 2.0
```

**Comment by kinnala** [comment]
I believe that difference is because ElementLineP2 uses nodal basis and ElementLinePp uses hierarchical basis.

**Comment by Vinc0110** [comment]
I'm not entirely sure what that means. Is `ElementLinePp(2)` simply different from `ElementLineP2()` and cannot be used as a universal (but slower) substitute? 
In a larger simulation, where I'm trying to calculate eigenmodes in 1d, I also get different results when using `ElementLinePp(2)` instead of `ElementLineP2()`.

**Comment by kinnala** [comment]
In most applications you can use either one of those but they don't give exactly the same result because the basis functions are different. There are infinite different bases you can use to represent quadratic polynomials. There are many different choices that are used in FEM depending on the use case.

**Comment by Vinc0110** [comment]
Understood. Thanks for the help!

**Comment by kinnala** [comment]
We can leave this open because of the bug in skfem.visuals.matplotlib.plot for MeshLine1.

**Comment by kinnala** [comment]
I cannot remember what was the remaining work and cannot deduce it by reading this, closing.
