### ISSUE TITLE
CellBasis.plot(..., colorbar=False) still adds a colorbar

### ISSUE THREAD

**Issue by gatling-nrl** [kinnala/scikit-fem#1017]
also, CellBasis.plot(..., colorbar=None) adds a colorbar.

Expected behavior: would turn off colorbar.

**Comment by kinnala** [comment]
I agree. This possibility of adding options should persist though:
```python
Basis(MeshTri(), ElementTriP1()).plot(MeshTri().p[0], colorbar={'orientation': 'horizontal'}).show()
```
