### ISSUE TITLE
Subdomains & boundaries in refinement

### ISSUE THREAD

**Issue by kinnala** [kinnala/scikit-fem#104]
The subdomains and boundaries are currently invalid if one refines the mesh. Create a method to Mesh which removes them on refine and override in MeshTri etc. to create new indexing

Boundaries:

- [x] MeshTri uniform
- [ ] MeshTri adaptive
- [x] MeshQuad
- [ ] MeshTet
- [ ] MeshHex

**Comment by gdmcbain** [comment]
This would be perfect for the empirical convergence study of #13; thus far I've been remeshing the Gmsh GEO from scratch.

(What's ‘neq‛?)

**Comment by gdmcbain** [comment]
Yes, and this would be even more comvenient in conjunction with the adaptive use of `Mesh.refine` demonstrated in #80.

**Comment by kinnala** [comment]
For now I added a warning that the indexing is invalidated.

Subdomains are simple to maintain in refine, but now that I thought about this more carefully I think that maintaining the named boundaries is very hard using the current data structures. There are many edge cases so you have to be very careful or do something clever.

**Comment by kinnala** [comment]
Uniform refine in MeshTri now should preserve named boundaries (stuff in Mesh.boundaries) in ec297c1f33be6839aaed47ffa854aaaa0eb60d5c. I was overly pessimistic in the previous comment: it was quite straightforward although it required some meditation.

**Comment by kinnala** [comment]
I realized that there is still a bug in refine when called with integer larger than one. This is just a reminder for myself.
