### ISSUE TITLE
How to use a vector basis ? 

### ISSUE THREAD

**Issue by MSJavaScript** [kinnala/scikit-fem#1040]
I have read example 21, but I still have to idea how to use a vector basis in my code. For example, Suppose the nodes are 
x = [0, 1, 2, 3, 4, 5]
In one variable case, the linear form 
```python
@LinearForm
def A(v, _):
    return v
```
gives the values [0.5, 1.0, 1.0, 1.0, 1.0, 0.5] as I expected.

In two variables case. I want to write a linear form like [v1+v2, v1-v2]. If I write
```python
@LinearForm
def A(v, _):
    return [[1, 1], [1, -1]] @ v
```
the code raise errors. If I write (In fact, I don't think it make sense to make a dot product between a matrix and a vector )
```python
@LinearForm
def A(v, _):
    return dot([[1, 1], [1, -1]], v)
```
I got some confusing values. 

[ 0.5         0.28867513  1.          0.          1.          0.
  1.          0.          1.          0.          0.5        -0.28867513]

Below is the complete code
```python
import numpy as np
from skfem import *
from skfem.helpers import grad, dot
x = np.array([0, 1, 2, 3, 4, 5], dtype=float)
mesh = MeshLine(x)
e = ElementLineP1()
vec_e = ElementVector(e, dim=2)
ib = CellBasis(mesh, vec_e)
fb = FacetBasis(mesh, vec_e)
@LinearForm
def A(v, _):
    return dot([[1, 1], [1, -1]], v)
L = asm(A, ib)
print(L)
```

**Comment by kinnala** [comment]
The return value of a form has to always be a scalar. For this reason I'm not quite sure what you mean by [v1+v2, v1-v2]. You could do just one of them e.g. v1+v2.

**Comment by kinnala** [comment]
Here is a code but I don't have enough knowledge to verify the results. It requires `autograd` to calculate the derivative automatically:
```python
from skfem import *
from skfem.experimental.autodiff import *
from skfem.experimental.autodiff.helpers import *

import autograd.numpy as anp
import matplotlib.pyplot as plt


m = MeshLine().refined(5)


basis = Basis(m, ElementLineP1() * ElementLineP1())
fbasis = basis.boundary('left')


dt = 0.1


@NonlinearForm
def interior(u1, u2, v1, v2, w):
    return (u1[0] * v1[0]
            + u2[0] * v2[0]
            + dt * dot(grad(u1), grad(v1))
            + dt * dot(grad(u2), grad(v2))
            + dt * anp.exp(u1[0] - u2[0]) * v1[0]
            - dt * anp.exp(u2[0] - u1[0]) * v1[0]
            - dt * anp.exp(u1[0] - u2[0]) * v2[0]
            + dt * anp.exp(u2[0] - u1[0]) * v2[0]
            - w['uprev'][0] * v1[0]
            - w['uprev'][1] * v2[0])


@NonlinearForm
def boundary(u1, u2, v1, v2, w):
    return (dt * anp.sin(u1[0]) * v1[0]
            - dt * 0.1 * u1[0] * u2[0] * v2[0])


D = basis.get_dofs('right')
x = basis.zeros()
x[basis.get_dofs('right').all('u^1')] = 1

# loop over time steps
for k in range(10):
    print('time: {}'.format(k * dt))
    uprev = basis.interpolate(x)
    # nonlinear iteraiton
    for itr in range(100):
        x_prev = x.copy()
        J, F = interior.assemble(basis, x=x, uprev=uprev)
        Jb, Fb = boundary.assemble(fbasis, x=x)
        x += solve(*condense(J + Jb, F + Fb, D=D))
        res = np.linalg.norm(x - x_prev)
        if res < 1e-8:
            break
        print(res)

    # visualize
    (x1, x1basis), (x2, x2basis) = basis.split(x)
    ax = x1basis.plot(x1, color='k-')
    plt.title('t = {}'.format(k * dt))
    x2basis.plot(x2, ax=ax, color='r-').show()
```
Hopefully I got the details right.

![Figure_1](https://github.com/kinnala/scikit-fem/assets/973268/68b78033-aa19-4484-bc1d-3b11a5a57715)
![Figure_2](https://github.com/kinnala/scikit-fem/assets/973268/e74c98ff-70d9-4ede-af3a-f360bd8a8d0a)
![Figure_3](https://github.com/kinnala/scikit-fem/assets/973268/7c8ce3a6-8f30-4847-b391-2f3771def049)

**Comment by MSJavaScript** [comment]
@kinnala Thanks for your reply. I think your answer might be right. 
The results calculated by matlab are as the following. But here I set the initial condition u1(x, 0) = 1, u2(x, 0) = 0.  (By the way, how to set the initial condition in your code ?)
At t = 0.9, the solution is close to the steady state, and it is close to your answer.

So If I want to solve a vector-valued equation, I have to use **ElementComposite** instead of **ElementVector** ?
For the **NonlinearForm**, I can just write all the variational forms into  a single expression, and the **assemble** method of the **NonlinearForm** can divide them automatically, is that right ?

```matlab

m = 0;
x = linspace(0,1,33);
t = 0.1:0.1:0.9;

sol = pdepe(m,@pdex4pde,@pdex4ic,@pdex4bc,x,t);
u1 = sol(:,:,1);
u2 = sol(:,:,2);

hold on;
for i = 1:9
    plot(x, u1(i, :), 'r-');
     plot(x, u2(i, :), 'b-');
end
hold off;

% --------------------------------------------------------------
function [c,f,s] = pdex4pde(x,t,u,DuDx)
c = [1; 1]; 
f = DuDx; 
y = u(1) - u(2);
F = exp(y)-exp(-y);
s = [-F; F]; 
end
% --------------------------------------------------------------
function u0 = pdex4ic(x);
u0 = [1; 0]; 
end
% --------------------------------------------------------------
function [pl,ql,pr,qr] = pdex4bc(xl,ul,xr,ur,t)
pl = [sin(ul(1)); -0.1*ul(1)*ul(2)]; 
ql = [-1; -1]; 
pr = [ur(1)-1; ur(2)]; 
qr = [0; 0]; 
end
```
![untitled](https://github.com/kinnala/scikit-fem/assets/23021127/27902f33-28a7-4530-a872-be35fc743259)

**Comment by kinnala** [comment]
Initial condition is just setting x to some value before the iterations.

NonlinearForm will calculate Jacobian and the residual using automatic differentiation and assemble those.

Difference between ElementComposite and ElementVector is only technical. ElementVector is better suitable for problems such as elasticity and fluid flow where you are approximating vector fields. ElementComposite is better suited for systems of equations where you have multiple unknowns defined over the same domain.
