### ISSUE TITLE
Docs: Wrong rendered filenames of the example source-files

### ISSUE THREAD

**Issue by adtzlr** [kinnala/scikit-fem#1047]
They are rendered to

*    *See the source code of [ex%s.py07](https://github.com/kinnala/scikit-fem/blob/7.0.1/docs/examples/ex07.py) for more information.*

instead of

*    *See the source code of [ex07.py](https://github.com/kinnala/scikit-fem/blob/7.0.1/docs/examples/ex07.py) for more information.*

And here's a screenshot:
![image](https://github.com/kinnala/scikit-fem/assets/5793153/5045b727-21c3-40f9-a6b8-b45a4c88b440)

**This is a minor issue because the link is correct.**

**Comment by kinnala** [comment]
Thanks for the report. I believe this appeared at some point during a Sphinx update at readthedocs. Perhaps a later update has fixed it and simply rebuilding the docs would fix it, or then there has been an actual change in the syntax.

**Comment by adtzlr** [comment]
Also, this link

![image](https://github.com/kinnala/scikit-fem/assets/5793153/df699074-ac15-4458-8778-08cb6ff132fa)

shows

![image](https://github.com/kinnala/scikit-fem/assets/5793153/12f16955-5856-4e5a-934d-327a67c8a5bb)

instead of the example code.

**Comment by kinnala** [comment]
These are both now fixed.
