### ISSUE TITLE
conda/mamba conda-forge support

### ISSUE THREAD

**Issue by gatling-nrl** [kinnala/scikit-fem#1067]
Current versions of scikit-fem belong on (at least) conda-forge. I'm not enough of a package guru to implement this. But in my current environment, this is the only package left that still requires pip...

(edit:)
i.e. one should be able to write 
```
conda install -c conda-forge scikit-fem
```
and get something better than version 2.4.0 of `scikit-fem`.

**Comment by kinnala** [comment]
Some fellow implemented and then abandoned the conda-forge recipe. I haven't been able to get it handed over to my control.

**Comment by gatling-nrl** [comment]
hmmm. ok. i can take on harassing the conda-forge admins for control over the namespace, if that's all you're lacking.

**Comment by gatling-nrl** [comment]
![image](https://github.com/kinnala/scikit-fem/assets/38136423/3a9e3d4f-6da4-4ae4-ade7-e4e783de0768)

will let you know how it pans out.

**Comment by kinnala** [comment]
Thanks for looking into it!

**Comment by kinnala** [comment]
If I recall, there are some changes in dependencies which broke the recipe.

**Comment by gatling-nrl** [comment]
do you know about this feedstock he mentions?

https://conda.discourse.group/t/reclaim-namespace-our-package-on-conda-forge-has-been-abandoned-by-the-fellow-that-created-it/417

**Comment by kinnala** [comment]
Here is my old PR: https://github.com/conda-forge/scikit-fem-feedstock/pull/19

**Comment by kinnala** [comment]
I believe this is now resolved, see https://anaconda.org/conda-forge/scikit-fem
