### ISSUE TITLE
1D mesh in 2D, 3D space

### ISSUE THREAD

**Issue by dad616610** [kinnala/scikit-fem#1074]
Is it possible to generate a mesh of 1D elements in a higher space?

I'm trying to create a mesh, similar to this one, using 1D elements.
![image](https://github.com/kinnala/scikit-fem/assets/147147326/d9d9ef4b-88ae-4793-bb8c-acbc4e596acb)

Can I do this with build-in mesh generation? Can I run a simulation if I import such a mesh using meshio?

**Comment by kinnala** [comment]
There isn't a "proper" support for stuff like that but I have successfully made such simulations work by creating triangles whose edges correspond to the "1D elements". Then I simply apply `FacetBasis` to integrate over a subset of the edges and finally remove those third extra nodes in each triangle from the linear system by slicing.

So it depends how much effort you are willing to put into it. There are probably better libraries for this purpose though.

**Comment by kinnala** [comment]
In case you want to try, I made an example where I project $$f(x, y)=\sin(x + y)$$ onto the finite element mesh on a skeleton mesh which is the dark blue part in this picture:
![Figure_1](https://github.com/kinnala/scikit-fem/assets/973268/78f4aaaf-b557-4162-a04d-439541092a03)
I end up with:
![Figure_2](https://github.com/kinnala/scikit-fem/assets/973268/2939140e-d5fd-4333-8f39-81e7d64b062f)
Code is here:
```python
import numpy as np
from skfem import *


m1 = MeshTri().refined(2)
m2 = MeshTri().refined(2).translated((-1., -1.))

m = (m1 + m2).with_boundaries({
    'skeleton': lambda x: (x[0] == 0) + (x[1] == 0)
})

m.draw(boundaries=True).show()

fbasis = FacetBasis(m, ElementTriP1(), facets='skeleton')


@BilinearForm
def mass(u, v, _):
    return u * v

I = fbasis.get_dofs(facets='skeleton').all()
MII = mass.assemble(fbasis)[I][:, I]


@LinearForm
def proj(v, w):
    return np.sin(w.x[0] + w.x[1])


y = solve(MII, proj.assemble(fbasis)[I])

Y = fbasis.zeros()
Y[I] = y


m.plot(Y, shading='gouraud', colorbar=True).show()



``

**Comment by dad616610** [comment]
Thank you for such a detailed answer! I'll play with the code around to see if it fits my needs
