### ISSUE TITLE
get_dofs(nodes: Any)

### ISSUE THREAD

**Issue by JarosT55** [kinnala/scikit-fem#1078]
**Hi,**
I am trying to call the _get_dofs()_ function on listed meshes boundary nodes like:
_basis.get_dofs(nodes={'bnodes_a','bnodes_b'})_
The result is **'NotImplementedError()'**
The _bnodes_ are not on a trivial path; thus, extracting them by position query would be difficult.
I appreciate any suggestions.
**Regards
MichaelT**

**Comment by kinnala** [comment]
We don't have a way to tag (give a name) seta of nodes and nodes kwarg is for extracting DOFs for single points at a time.

Perhaps you mean: facets={'bnodes_a', 'bnodes_b'}) ?

**Comment by gdmcbain** [comment]
How is your `basis` defined?

Does [ex28](https://github.com/kinnala/scikit-fem/blob/master/docs/examples/ex28.py) work for you?  It loads a mesh from a file, where the mesh has named boundaries.

https://github.com/kinnala/scikit-fem/blob/44916dc9551dcf5a3b12586080d61e18dc39dabe/docs/examples/ex28.py#L72

then accesses a subset of those

https://github.com/kinnala/scikit-fem/blob/44916dc9551dcf5a3b12586080d61e18dc39dabe/docs/examples/ex28.py#L107

**Comment by gdmcbain** [comment]
Oh I missed the bit about nodes.  Do you actually want nodes?  Or just to access predefined boundaries?

**Comment by JarosT55** [comment]
Thank you **All** for the prompt response. I have not expected them ... so fast!!!!
as per doc _nodes_ kwarg is listed in the func description
_get_dofs(facets: Any | None = None, elements: Any | None = None, nodes: Any | None = None, skip: List[str] | None = None)_

I will try playing with **ex28.py**

Regards
MichaelT

**Comment by kinnala** [comment]
Perhaps you can try also: help(basis.get_dofs)

**Comment by JarosT55** [comment]
**Hi All,**
### @ _D = basis["heat"].get_dofs([b for b in mesh.boundaries if b.endswith("-inlet")])_ 
I use a similar syntax on the mesh. From a custom utility plot, I know it's every node, number, position, etc.
I must admit that  I am 2 weeks old **skfem-infant** still crawling on all four; thus, there are many mysteries at the front of my eyes.
One confusion is that the list of nodes from:
_mesh.boundaries['bnodes_a']_
produces a different list than the one from (for the _ElementTriP1()_)
_basis.get_dofs(['bnodes_a']).nodal_ix_
... but hey!
_basis.get_dofs(['bnodes_a']).facet_ix_
... is the perfect match!!! … and even better for _TriMorley()_ I have got _‘u_n’_s
_basis.get_dofs(['bnodes_a']).facet[‘u_n’]_

Thus, ... there are a lot of puzzles to put into place still ... in the skfem environment, **which looks accommodating and promising!**

**Regards
MichaelT**

**Comment by kinnala** [comment]
In scikit-fem, you will need to carefully distinguish between different topological entities (e.g., nodes, facets) of the mesh AND "degrees-of-freedom" (DOF) which are, in general, different. Especially if you use an element such as `ElementTriMorley` which has both, nodal DOFs and facet DOFs.

For example, `mesh.boundaries['bnodes_a']` does not produce a list of nodes but a list of facets. On the other hand, `basis.get_dofs(['bnodes_a']).XXX` produces a list of DOFs. Some discussion about this topic can be found from the documentation: https://scikit-fem.readthedocs.io/en/latest/advanced.html#indexing-of-the-degrees-of-freedom

**Comment by JarosT55** [comment]
**Hi,**
As per [gdmcbain](https://github.com/gdmcbain) advice, I have played a little bit with **ex28**.
The extraction of boundaries has worked as a charm:

            _boundaryIdxes = basis.get_dofs([boundaryName]).nodal_ix     
            ax.plot(*mesh.p[:, boundaryIdxes], color=boundaryColor, linewidth=2*boundaryLine, )_

 However, while attempting to visualize subdomains … **I encountered some problems I could not comprehend**. I assumed that each subdomain index addresses facet holding indexes of two nodes (defining the facet segment). I used the code like:

_domainIdxes  = mesh.subdomains[domainName]
sIdxes  = mesh.facets[0][domainIdxes] 
eIdxes  = mesh.facets[1][domainIdxes] 
seIdxes = [i for indexes in zip(sIdxes, eIdxes) for i in indexes]
ax.plot( *mesh.p[:, seIdxes], domainColor, markersize=domainMarker, label=domainName, linewidth=subdomainlinewidth )_

The resulting plot … is a little bit messy! I do not know why. **Is my assumption correct for organizing data?** Is there a better/proper way of extracting subdomains? I am attaching **ex28_basis_heat.png** file with a visual representation of my test play.

**Regards and HNY
MichaelT**
![ex28_basis_heat](https://github.com/kinnala/scikit-fem/assets/23690439/85860200-1fbf-4c10-90dd-be869fa1cc70)

**Comment by kinnala** [comment]
Subdomains are element indices, not facet indices. This does not make sense since you are slicing facets using element indices:

domainIdxes = mesh.subdomains[domainName]
sIdxes = mesh.facets[0][domainIdxes]

**Comment by JarosT55** [comment]
ooohhhhh ! Thanks

**Comment by JarosT55** [comment]
**uuuuuuFfffffff !!!**

The code is ... well ... certainly not very efficient ... but it 
![Uploading ex28_basis_heat.png…]()
works.

_for subdomain, domainColor in zip(mesh.subdomains, colLst):
  # Elements centroids
  domain_mesh  = mesh.restrict(mesh.subdomains[subdomain])
  domain_basis = Basis(domain_mesh, basis.elem)
  domain_basis.get_dofs(elements= lambda x: ax.plot(x[0], x[1], domainColor,    markersize=markersizeM, label='elements'))  
  # Elements facets   
  mesh_t2f      = mesh.t2f[:, mesh.subdomains[domainName]]domain_facets = mesh.facets[:,mesh_t2f]            
  sIdxes  = domain_facets[0]
  eIdxes  = domain_facets[1]
  seIdxes = [i for indexes in zip(sIdxes, eIdxes) for i in indexes]
  ax.plot( *mesh.p[:, seIdxes], domainColor, markersize=domainMarker, label=domainName, linewidth=linewidthM )_

Thank you for the valuable advices.

**Regards
MichaelT**

![ex28_basis_heat](https://github.com/kinnala/scikit-fem/assets/23690439/f02edd1a-6006-4a18-839d-8e39805f4930)
