### ISSUE TITLE
Lowest order integration rules for tets

### ISSUE THREAD

**Issue by kinnala** [kinnala/scikit-fem#1110]
Right now the lowest order integration rule for tets has 4 points. The following rule is suitable for P1 Laplacian though:
```python
quadrature=(np.array([[.25],[.25],[.25]]), np.array([1/6]))
```
It should be added to `get_quadrature`.

**Comment by adtzlr** [comment]
Great, this saves some computation time and memory for linear elasticity. 

The only *downside* (if it is really considered to be one) of it is that projections do not work with this lowest-order quadrature. But it is so obvious that this should not be a problem. I think a typical scikit-fem user has enough knowledge.

**Comment by kinnala** [comment]
I think it won't be a problem since usually it would not enabled by default, user has to write `Basis(..., intorder=1)`. Perhaps it will be enabled by default if initializing a basis for `Basis(..., ElementTetP0()))`. I will need to check this.

**Comment by kinnala** [comment]
So basically, before this change, if user initializes `Basis(mesh, ElementTetP0())` it chose automatically the rule with 4 integration points while, after the change, it would automatically choose the rule with 1 integration points. So there might be some surprises involved if a user relied on this behaviour.

**Comment by kinnala** [comment]
I am considering of circumventing the aforementioned issue by increasing `ElementTetP0.maxdeg` from 0 to 1.

**Comment by kinnala** [comment]
Nah, I will let the speed benefit show there.
