### ISSUE TITLE
coordinate-dependent Dirichlet data for other than P1

### ISSUE THREAD

**Issue by gdmcbain** [kinnala/scikit-fem#112]
The specification of inhomogeneous Dirichlet data for the Laplace equation is demonstrated in ex14.py for `ElementTriP1`:
https://github.com/kinnala/scikit-fem/blob/9c0cf416745941abd72f70865351ef0e095f83b2/docs/examples/ex14.py#L37

however, `Mesh.p` only contains the nodal coordinates, so this doesn't work if the element is changed to say `ElementTriP2`.

How might one go about specifying inhomogeneous Dirichlet data for elements with degrees of freedom that aren't all located at nodes of the mesh?  Does this relate to #84?  The P2 degrees of freedom on the boundary are available through `basis.get_dofs().all()`.

I suppose one could fall back on other techniques like:
* penalization, i.e. approximating the Dirichlet condition with a Robin condition (Ern & Guermond [2002](https://www.springer.com/gp/book/9783540426158), &sect;9.5.5)
* Lagrange multiplier (Stenberg [1995](http://dx.doi.org/10.1016/0377-0427(95)00057-7))

**Comment by kinnala** [comment]
You are correct about #84. Currently you have to use your expertise on the location of the DOF's, i.e. edge midpoints. You could find all boundary edges, find their midpoints, and use this info to assign DOF values. This is cumbersome, hence #84. If you need this feature, I could try to find time this weekend but cannot promise yet. 

Both alternative methods you mentioned should also work and be supported. 

There are at least two additional ways: Nitsche's method (see interior penalty example in docs, this I'd prefer over penalty) and using mixed formulation where Dirichlet condition is natural (i.e. mixed Poisson with H(div) elements).

**Comment by gdmcbain** [comment]
No, I don't need this feature at the moment, just thought it might be a good addition to the suite. A sequence of examples demonstrating all of the above techniques would be worthwhile.

I noticed this while looking into generalizing the membrane example from P1 to P1 or P2, i.e. composing complement_dofs with get_dofs instead of relying on interior_nodes. That works fine for the homogeneous Dirichlet condition.

**Comment by gdmcbain** [comment]
I changed the title as constant inhomogeneous Dirichlet data is easy too; e.g.
https://github.com/kinnala/scikit-fem/blob/9c0cf416745941abd72f70865351ef0e095f83b2/docs/examples/ex13.py#L60

**Comment by gdmcbain** [comment]
I've hit up against this again now.  As flagged in #31 on [2018-09-24](https://github.com/kinnala/scikit-fem/issues/31#issuecomment-423889850), I've started on the backward-facing step (branch: [backward-facing-step](https://github.com/gdmcbain/scikit-fem/tree/backward-facing-step)) as an example of the Navier–Stokes equations.  There are a few variations on the geometry and inlet conditions in the literature, but I was going to go with the Barkley, Gomes, & Henderson (2002)

https://github.com/gdmcbain/scikit-fem/blob/f31d262553f0e97e1268b5a95cacd0d73f083c5b/docs/examples/backward_facing_step.py#L6

which has a parabolic (i.e. fully developed plane Poiseuille) profile, _u_ = 4 _y_ (1 &minus; _y_) on inlet 0 < _y_ < 1, and the velocity is `ElementTriP2` in Taylor–Hood.

For the moment I'll press ahead with the example using plug-flow at the inlet at the mean value 2/3, as that'll still work for an example of through-flow, then think more carefully about which of the fixes for suggested above is most elegant.

**Comment by kinnala** [comment]
Have you tried doing something like
```python
fb = FacetBasis(m, ElementTriP2())

@linear_form
def fv(v, dv, w):
    x, y = w[0]
    return 4.0*y*(1-y)

u[I] = solve(asm(mass, fb), asm(fv, fb), I=I)
```
where `I` contains the DOF indices belonging to the respective boundary. I didn't try it but I think it should work fine. This must be of course adapted to the vectorial case.

**Comment by gdmcbain** [comment]
No, I haven't tried this yet. This was the first thing that I was going to try after the example was otherwise complete; it's pretty close. This does seem like the neatest of the options not involving knowledge of the locations of the nodes with which degrees of freedom are associated #84.

This is the L&sup2;- projection suggested in #84 isn't it. There was a suggestion there that that might induce a 'consistency error'.

**Comment by kinnala** [comment]
Yes this is L^2 projection on the boundary. Consistency error in the sense that in this case we would know exactly the value for the degree-of-freedom but when using L^2 projection you are unlikely to get the exact value. This is probably just fine for any practical applications and has only some theoretical implications.

**Comment by gdmcbain** [comment]
While I am leaning towards the L&sup2; as the best way to do this, following the finding of the DOF locations for `ElementTriP2` in #84, I did manage to work out how to impose the parabolic inlet profile _u_ = 4 _y_ (1 &minus; _y_) for the backward-facing step by interpolation: https://github.com/gdmcbain/scikit-fem/commit/42e5d8475a0cf8e39d4874458956d6ac20e14fe2
```python
xy = np.hstack([mesh.p, mesh.p[:, mesh.facets].mean(axis=1)])
inlet_dofs_ = basis['u'].get_dofs(mesh.boundaries['inlet'])
inlet_dofs = [np.concatenate([inlet_dofs_.nodal[f'u^{i}'],
                              inlet_dofs_.facet[f'u^{i}']])
              for i in [1, 2]]
y = xy.flatten('F')[inlet_dofs[1]]


uvp[inlet_dofs[0]] = 4 * y * (1 - y)
```

**Comment by kinnala** [comment]
I look now at adding a simple way to use the L^2 projection.

**Comment by kinnala** [comment]
Here is now a version which works with scalar fields only here: https://github.com/kinnala/scikit-fem/blob/master/skfem/utils.py#L257

It could be improved by adding support for vector fields, i.e. check if vector field => use `return sum(u * v)` instead of `return u * v`.

**Comment by gdmcbain** [comment]
> It could be improved by adding support for vector fields, i.e. check if vector field => use `return sum(u * v)` instead of `return u * v`.

I had a go at this in 506fdeb.  Fairly blindly though.  It seems to work in ex24. #136

**Comment by kinnala** [comment]
I also agree that this should work in general.
