### ISSUE TITLE
Add ex12.py to docs

### ISSUE THREAD

**Issue by kinnala** [kinnala/scikit-fem#114]

**Comment by kinnala** [comment]
Docstring in ex12.py must be extracted to ex12.rst (new file) and ex12.rst added to learning.rst.

**Comment by gdmcbain** [comment]
I should probably add a reference for 'Boussinesq k-factor' as it's not in Wikipedia.

The original reference is

* Boussinesq, J. (1868). Mémoire sur l'influence des frottements dans les mouvements réguliers des fluides. _Journal de mathématiques pures et appliquées 2e série_  **13**:377–424

though that doesn't use the symbol _k_.  That I took from 

* Dryden, H. L., F. D. Murnaghan, & H. Bateman (1956). _Hydrodynamics._ Dover, p. 178

**Comment by gdmcbain** [comment]
Actually [Google](https://www.google.fr/search?source=hp&ei=0OE-XNG6C4uAvwSP24C4CA&q=%22Boussinesq+k-factor%22&btnK=Google+Search&oq=%22Boussinesq+k-factor%22&gs_l=psy-ab.3...464.3435..3751...0.0..0.183.3132.0j21......0....1..gws-wiz.....0..0i131j0j0i10j0i22i30j33i160.FXvdFpYdOeo) says
> No results found for "Boussinesq k-factor".

I wonder whether this has a better-known name.  It's a convenient quantity that arises in lots of applications.
