### ISSUE TITLE
Add ex12.py to test_examples.py

### ISSUE THREAD

**Issue by kinnala** [kinnala/scikit-fem#115]

**Comment by gdmcbain** [comment]
I think pygmsh is using Circle CI these days but it retains a vestigial configuration for Travis that shows how it did it once upon a time.

  https://github.com/nschloe/pygmsh/blob/67b776fcc22ba05722ee2808708242d24fce6925/.travis.yml#L9-L14

**Comment by gdmcbain** [comment]
I replaced pygmsh with dmsh in https://github.com/kinnala/scikit-fem/compare/master...gdmcbain:ex12-doc .  It probably makes more sense for this example.
