### ISSUE TITLE
basis.project 

### ISSUE THREAD

**Issue by ympetus** [kinnala/scikit-fem#1170]
Method "basis.project" gives different results for same function with different notations:
f(x) = 1 and f(x) = x*0 + 1
Looks strange....

```
def fx(x):
    return 1.0 
def fx2(x):
    return x*0 + 1.0 

m = MeshLine().refined(3).with_boundaries({"left": lambda x: x[0] == 0})
e = ElementLineHermite()
basis = Basis(m, e)
print("project of f = 1\n", basis.project(fx))
print("project of f = x * 0 + 1\n", basis.project(fx2))
```

Output:
```
project of f(x) = 1 
[ 1.00000000e+00 -3.70794997e-14  1.00000000e+00  9.20331504e-14
  1.00000000e+00 -6.91455991e-15  1.00000000e+00 -2.24667056e-14
  1.00000000e+00  1.59679298e-14  1.00000000e+00 -2.26031293e-14
  1.00000000e+00 -1.44257381e-14  1.00000000e+00  4.61157504e-15
  1.00000000e+00  2.07234751e-14]
project of f(x) = x * 0 + 1 
[ 8.00000000e+00 -6.04253487e-10  8.00000000e+00  3.56397997e-09
  8.00000000e+00 -1.39409141e-10  8.00000000e+00 -3.28115530e-10
  8.00000000e+00  3.37668490e-10  8.00000000e+00 -3.46579092e-10
  8.00000000e+00 -2.77698842e-10  8.00000000e+00  4.57013662e-11
  8.00000000e+00  8.68301240e-10]
```

**Comment by kinnala** [comment]
Input to f is an array of quadrature points. Output must have one value per quadrature point. Do you propose there should be a guard against user providing incorrect f?

**Comment by ympetus** [comment]
Yes, this works without warnings, returns values of same shape and could lead to wrong results. 
Also it doesn't clear which projection is correct.
Thank you

**Comment by kinnala** [comment]
In this case I would use
```python
def f(x):  # x represents a vector field
    return 1 + 0 * x[0]  # output represents a scalar field
```
However, if the element was different, then those other options might be correct.

There are close to none guards within the library against incorrect user input. Sometimes it can be hard to decide what is ”correct” and what is ”incorrect” because so many use cases are possible. It can be confusing to new users.

**Comment by ympetus** [comment]
Ok, thank you
