### ISSUE TITLE
Solve PDE just in a subdomain

### ISSUE THREAD

**Issue by gdmcbain** [kinnala/scikit-fem#159]
Thinking about different ways to represent multiphysics problems like conjugate heat transfer, one of the basic questions is whether to use one or many meshes.   If one, it might be divided into subdomains (in the mesh, e.g. in Gmsh), as done previously for piecewise-definition of coefficients #89.  It could be that a single mesh is easier to work with than several, e.g. for identifying the interfaces and handling transmission conditions.

The issue then is how to solve a partial differential equation just in one subdomain.  Note that `InteriorBasis` always extends over the whole mesh, not having a restricting optional argument like `facets` of `FacetBasis`.  Thus a finite element function is always defined over the whole mesh; I don't think it's possible with the current machinery to define one just on a subdomain.

I think one way to restrict a problem to a subdomain might be via `Mesh.subdomains`, `InteriorBasis.element_dofs`, and `condense`.  I'll try to put an example together and see how it goes.

**Comment by gdmcbain** [comment]
Well that was easy.  Thanks to all the good work done thus far on the underlying machinery: everything needed was already there.

Now I think from here it would be easy enough to go on to construct a discrete Poincaré–Steklov operator mapping interfacial temperature to interfacial heat flux, or vice versa, and use that to couple the separate problems in the separate subdomains, coupled by continuity of temperature and (normal component of) heat flux.  That's what I would have done previously, but maybe I should instead pause and look into Nitsche's mortar method.

**Comment by kinnala** [comment]
I'm surprised that InteriorBasis.__init__ does not have an optional
argument for specifying the set of elements.

Some old version of the code definitely had it. But good that you found a
workaround.

Do you think we should consider adding such feature? I could work on it
next weekend.

**Comment by gdmcbain** [comment]
At first I was just amazed at how much easier this was than in other codes. Later it did occur to me that there was a bit of wasted assembly which could be avoided with such an optional argument.
