### ISSUE TITLE
generate refined basic meshes

### ISSUE THREAD

**Issue by gdmcbain** [kinnala/scikit-fem#16]
Given that more than half the examples call `skfem.Mesh.refine` to repeatedly `_uniform_refine` square or cubical meshes with simplicial or tensor elements and that this appeared in profiling while investigating assembly #15 to be a bit slow, it might be quicker to generate these meshes in  a single step.

This is reasonably straightforward and has already been implemented in other packages; I won't refer to any of those specifically as I haven't considered the licensing implications.

**Comment by kinnala** [comment]
I begun this work in 9d2831265e32a80c0c7ef83f433f85def7010d39

**Comment by kinnala** [comment]
I found a bug in the previous code. It was fixed in 15b089e4c6b527024a117c5dec64bab5b9ab74f1.

I think one could add init_tensor easily also for MeshQuad and MeshTri by looking at MeshLine.__mul__. Either use MeshLine.__mul__ or refactor that code to MeshQuad.init_tensor and modify the multiplication. MeshTri.init_tensor works simply by calling MeshQuad.init_tensor and then MeshQuad._splitquads.

There is no function to split hexes to tetrahedra so that would be needed to finish this up.

**Comment by kinnala** [comment]
MeshQuad and MeshTri have now init_tensor in 5ebb8241f1147dc1c77b711bc9cc5811d55f85c7.

MeshTet is the only one missing now.

**Comment by gdmcbain** [comment]
I think _splithex might be tricky.  Whereas a quadrilateral split along either diagonal still has the four original edges as valid edges so that any quadrilaterals can be split independently of the others and still give a conformal triangular mesh, this isn't the case with hexahedra—their faces get split and have to be split the same way on either side.  This is easy for a hexahedral mesh which is just a regular discretization of a cuboid but it might be tricky for a general unstructured hexahedral mesh.  It could be a problem solved in the literature; I don't know.

**Comment by gdmcbain** [comment]
While I was thinking about the difficulty of splitting hexahedra into tetrahedra, I thought a workaround might be to just use [`meshzoo.cube`](https://github.com/nschloe/meshzoo/blob/master/meshzoo/cube.py).  I demonstrated this by redoing `examples/ex09.py`: 5c1ee94b0d95a6584eca38d7fe4359596e7edc05.  Basically:
```python
m = MeshTet(*map(np.transpose, meshzoo.cube(nx=16, ny=16, nz=16)))
```

**Comment by kinnala** [comment]
Good idea. And since meshzoo is MIT licensed, we are able to include only the necessary parts without introducing additional dependencies. They also seem to have other interesting templates like  iso_sphere. Thanks for this tip.

**Comment by kinnala** [comment]
I included the meshzoo cube-function as slightly modified version named MeshTet.init_tensor. This pull request is now essentially done.
