### ISSUE TITLE
Fix ex4.py

### ISSUE THREAD

**Issue by kinnala** [kinnala/scikit-fem#18]
Ex4 depends on Comsol import. This functionality was removed so the example does not work.

**Comment by gdmcbain** [comment]
Would it be better here to replace the .mphtxt files with meshes in another format that `skfem.Mesh.load`, i.e. `meshio.read`, already knows or to teach the latter the format?

**Comment by kinnala** [comment]
I briefly considered the possibility of improving meshio, but I think in
the scope of this issue just creating the same or similar meshes
differently is sufficient.

**Comment by kinnala** [comment]
I fixed this in 9016545b9022ec7becacdbf895971dbc1daa105f while I was at it.
