### ISSUE TITLE
Gmsh Python API

### ISSUE THREAD

**Issue by gdmcbain** [kinnala/scikit-fem#180]
I've been experimenting with the new [Gmsh Python API](http://gmsh.info/doc/texinfo/gmsh.html#Gmsh-API), in conjunction with the wrapping package [gmsh-sdk](https://pypi.org/project/gmsh-sdk).  It's good.

So far, I've just been using it to generate MSH files for `Mesh.load`, but of course part of the appeal is that it might be possible to avoid writing out the mesh and rereading it (as is necessary for pygmsh); i.e. it should be possible to instantiate a `skfem.Mesh` directly from the data structures available in the Gmsh Python API.  This would bypass not only `Mesh.load` but also `Mesh.from_meshio`.  

In order to pass on any subdomains and boundaries, should it populate `Mesh.external` and then use `Mesh._parse_submeshes` as `Mesh.from_meshio` does?  

Or (thinking also of the impasse on loading `MeshLine.boundaries` in #175) should the `skfem.Mesh` constructors be enhanced to take not only points and cells but also optionally subdomains and boundaries?  Factoring that code out of `Mesh._parse_submeshes`.

**Comment by kinnala** [comment]
Do you happen to have a minimal example so I can try it out?

**Comment by kinnala** [comment]
Nevermind, I found some stuff here: https://gitlab.onelab.info/gmsh/gmsh/blob/master/demos/api/adapt_mesh.py

**Comment by kinnala** [comment]
Maybe the cleanest way of doing this would be along

> Or (thinking also of the impasse on loading MeshLine.boundaries in #175) should the skfem.Mesh constructors be enhanced to take not only points and cells but also optionally subdomains and boundaries? Factoring that code out of Mesh._parse_submeshes.

Basically we'd be writing various functions that take some external Mesh format object and transform those into a tuple of correct input variables for `Mesh.__init__`.

Some questions:
- How `Mesh.load` and `Mesh.save` fit into this picture?
- Where these importers should reside? New module or `utils` or something else?

**Comment by gdmcbain** [comment]
Problem:
```
Python 3.7.3 (default, Mar 27 2019, 22:11:17) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from skfem import *
>>> from scipy.sparse.linalg import gmres
>>> import gmsh
Erreur de segmentation (core dumped)
```

And a variation:
```
Python 3.7.3 (default, Mar 27 2019, 22:11:17) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from scipy.sparse.linalg import gmres
>>> import gmsh
>>> from skfem import *
free(): invalid pointer
Abandon (core dumped)
```

**Comment by gdmcbain** [comment]
But:
```
Python 3.7.3 (default, Mar 27 2019, 22:11:17) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import gmsh
>>> from skfem import *
```
doesn't seem to dump core.

The two errors in the previous comment aren't entirely repeatable.  Python does consistently dump core but randomly first issues one or other of the messages.

**Comment by gdmcbain** [comment]
I've just noticed that [gmsh-sdk](https://pypi.org/project/gmsh-sdk) is actually also a convenient way of installing Gmsh itself
```shell
pip install gmsh-sdk
which gmsh
```
→ `/home/geordie/.local/share/miniconda3/envs/scikit-fem/bin/gmsh`
```shell
gmsh -version
```
→ `4.5.1`.

This might replace the three lines

https://github.com/kinnala/scikit-fem/blob/55bcfc71ca1fd307a07ee9a5e3f9f548eadc8620/.travis.yml#L8-L10

Also is this fourth already redundant?

https://github.com/kinnala/scikit-fem/blob/55bcfc71ca1fd307a07ee9a5e3f9f548eadc8620/.travis.yml#L6

**Comment by gdmcbain** [comment]
A brief example of a Python script importing `gmsh` to open a MSH file and read the nodal coordinates was posted by C. Geuzaine 2020-01-13 in the Gmsh thread [‘Transforming mesh’](http://onelab.info/pipermail/gmsh/2020/013480.html); this might be a starting point for a future `skfem.importers.gmsh.from_file` module function.

**Comment by gdmcbain** [comment]
[enum](https://docs.python.org/3/library/enum.html) ?

**Comment by kinnala** [comment]
`gmsh` is GPL so cannot depend on it.

**Comment by gdmcbain** [comment]
This might be coming back in via nschloe/pygmsh#360.
