### ISSUE TITLE
python setup.py test fails

### ISSUE THREAD

**Issue by gdmcbain** [kinnala/scikit-fem#183]
Forgetting the command line to run the test suite, I tried
```python
python setup.py test
```
and it raised
> TypeError: asm() missing 2 required positional arguments: 'kernel' and 'ubasis'

The command line is `python -m unittest discover`, as given in `.travis.yml` and `Makefile`, but I wonder what's required to get the other to work.

**Comment by kinnala** [comment]
You must add some spells to setup.py and .cfg. I'll look into it.

**Comment by gdmcbain** [comment]
I think #184 covers it, just adding an entry to `setup.py`, nothing to `setup.cfg`.
