### ISSUE TITLE
tolerance for Krylov solvers

### ISSUE THREAD

**Issue by gdmcbain** [kinnala/scikit-fem#188]
Experimenting with the new `skfem.utils.solver_iter_krylov` using `scipy.sparse.linalg.gmres` with `skfem.utils.build_pc_ilu` for a three-dimensional version of ex25 ('Forced convection'), it's going quite well (up to a `basis.N` of 911&thinsp;752 so far, solving in a few minutes).

But I found that the optional keyword argument `tol` to `solver_iter_krylov` didn't seem to be doing anything.  It turns out that this `tol` is passed in to the solver (here `gmres`) as `atol` and the `gmres` (relative) `tol` left as the default and this was dominating.

https://github.com/scipy/scipy/blob/0f5d8aab5d9990c433168ad3424b3f5c9440978e/scipy/sparse/linalg/isolve/lgmres.py#L168

Perhaps it should be possible to pass in `tol` as well as `atol`?

Maybe `solver_iter_krylov` should just pass on `*args, **kwargs` to the solver?  That would be simpler, if a little less explicit.  

It might also facilitate using solvers from outside `scipy.sparse.linalg` that take different arguments (presumably though always taking the linear operator and right-hand side as first two positional arguments, and maybe the initial guess as the third?).

**Comment by kinnala** [comment]
> Maybe solver_iter_krylov should just pass on *args, **kwargs to the solver? That would be simpler, if a little less explicit.

I think this is fine.
