### ISSUE TITLE
listing as a scikit

### ISSUE THREAD

**Issue by gdmcbain** [kinnala/scikit-fem#193]
Should scikit-fem be listed in the [SciKits Index](http://scikits.appspot.com/scikits)? 

According to https://scipy.org/scikits.html,

> An automatically maintained list of Scikits can be found here: http://scikits.appspot.com/scikits

> The technical step to make this happen is simple: register the project in the Python package index with a name chosen to start with scikit. Examples of existing package: scikit-learn (machine learning), scikits.sparse (additional sparse matrix routines).

which should (by my reading) already apply to https://pypi.org/project/scikit-fem/

According to http://scikits.appspot.com/contribute, 

>  Note that scikits do not have to be hosted on the SciPy servers. Any package named "scikits.xyz" on the Python Packaging Index will be included on this website automatically. 

which is slightly different but doesn't seem to have stopped packages like https://pypi.org/project/scikit-fmm from appearing in the list as http://scikits.appspot.com/scikit-fmm.

Maybe the index isn't regenerated from PyPI very often.

**Comment by kinnala** [comment]
I don't know what happened, but here it is: http://scikits.appspot.com/scikit-fem

**Comment by gdmcbain** [comment]
That's odd, I get 404 for  http://scikits.appspot.com/scikit-fem and there's nothing in the alphabetical list at http://scikits.appspot.com/scikits between scikit-fda and.scikit-fmm.

**Comment by gdmcbain** [comment]
The first lonk returned by Google for "scikit-fem site:appspot.com" is https://www.scikits.appspot.com/scikit-fem but my Firefox Android browser refuses to display it: ‘Cette connexion n’est pas certifiée’ , `SSL_ERROR_BAD_CERT_DOMAIN`.

**Comment by gdmcbain** [comment]
But now it is all working fine:
* [scikit-fem](http://scikits.appspot.com/scikit-fem) does appear between scikit-fda and scikit-fmm at http://scikits.appspot.com/scikits
* http://scikits.appspot.com/scikit-fem, and also https://scikits.appspot.com/scikit-fem

I don't know what happened, but it doesn't matter now.  I note that scikit-fdiff doesn't show up, but that could be because it's indexed in PyPI as https://pypi.org/project/skfdiff; anyway, that's an issue for scikit-fdiff not scikit-fem.
