### ISSUE TITLE
should functional return float rather than ndarray?

### ISSUE THREAD

**Issue by gdmcbain** [kinnala/scikit-fem#200]
While implementing `class Form` #199 for #198, I noticed that the behaviour of `functional` differs from `linear_form` and `bilinear_form`; the latter assemble over the finite elements whereas the former doesn't.  This factoring of discretization into two steps (within each element, then assembling over mesh) might be useful for the latter too #192.

Thus far, `functional` is only used in ex22 where its result is passed to `adaptive_theta`, which wants an array of length equal to the number of elements; however, it could also be assembled, e.g. to calculate the area of a mesh, or the volume beneath a deformed two-dimensional membrane or plate; e.g. in the ex12, the `area` can be computed with
```python
sum(asm(functional(lambda w: 1.), basis)
```
or the volume as
```python
sum(asm(functional(lambda w: w.w), basis, w=basis.interpolate(x)))
```

Conversely, various ideas for elemental matrices from bilinear forms were mooted on gitter and in #192.

This is a suggestion for maybe something like a new `instancemethod` `Form.elemental` which returns:
* `functional`: `ndarray` (1-d array, being float per element)
* `linear_form`: `ndarray` (2-d array, being 1-d array per element)
* `bilinear_form`: `ndarray` (3-d array, being 2-d array per element)

plus in the last two cases maybe also the indices required for subsequent assembly; this 'subsequent assembly' in the `functional` case is simply `sum` so no indices are required.

This would naturally follow the resolution of #198.

**Comment by kinnala** [comment]
I suppose this makes sense. Let's go for it.

**Comment by gdmcbain** [comment]
On functionals, I wonder whether the currents in ex13 #116 #203 shouldn't be calculated with functionals rather than linear forms.
