### ISSUE TITLE
warnings in mesh save load cycle tests

### ISSUE THREAD

**Issue by gdmcbain** [kinnala/scikit-fem#205]
The last two outputs from `python -m unittest -v tests/test_mesh.py`:
```
runTest (tests.test_mesh.SaveLoadCycle) ... /home/geordie/src/scikit-fem/skfem/importers/meshio.py:81: UserWarning: Unable to load tagged boundaries/subdomains.
  warnings.warn("Unable to load tagged boundaries/subdomains.")
local variable 'boundaries' referenced before assignment
ok
runTest (tests.test_mesh.SaveLoadCycleHex) ... local variable 'boundaries' referenced before assignment
ok
```

**Comment by gdmcbain** [comment]
Ah, I see, this is somewhat expected; `boundaries` and `subdomains` are only defined in `skfem.importers.meshio.from_meshio` if `'gmsh:physical' in `m.cell_data[meshio_type]` and `m.cell_data[bnd_type]`, respectively, but regardless they are passed to the `mesh_type` constructor.  Without `boundaries` and `subdomains`, this raises a `NameError` but it's caught, the warning emitted, and a simple mesh returned.

**Comment by kinnala** [comment]
Closing for now. If you have a proposition on how to improve, we reopen.

**Comment by gdmcbain** [comment]
Yes, O. K.

Ideally I'd change the function so that it wouldn't warn about situations where nothing's wrong, but I think it's tricky to distinguish deliberate absence of boundaries and subdomains from inability to detect them.

So instead, I'm thinking about [`unittest.TestCase.assertWarns`](https://docs.python.org/3/library/unittest.html#unittest.TestCase.assertWarns).

**Comment by gdmcbain** [comment]
The same `UserWarning` is also emitted by ex12; there the domain is tagged as a subdomain `'disk'` but the boundary isn't tagged.  The whole boundary is accessed with

https://github.com/kinnala/scikit-fem/blob/0eb2dceb442f4770661db734f45f18e3e17d871f/docs/examples/ex12.py#L19

I'll change the example so that it does define the boundary.
