### ISSUE TITLE
covering threading

### ISSUE THREAD

**Issue by gdmcbain** [kinnala/scikit-fem#207]
I'm a little nervous that the recent refactoring of forms #199 might have affected threading, which was used inside the old `skfem.utils.asm` function and is now used in the `assemble` methods of `LinearForm` and `BilinearForm`.  Threading with more than one thread isn't covered in `tests` or `docs/examples`.  (During development of #199 I regularly ran `pytest -n auto tests` and `parallel python {} ::: docs/examples/ex??.py`.)

There was a snippet in the old docstring for `asm`:

https://github.com/kinnala/scikit-fem/blob/a2bdb953e26df1b7228284d481a4bb87ddbb3335/skfem/assembly/asm.py#L38-L50

but I never attempted to extend that into a complete example.

Should `nthread > 1` in `LinearForm` or `BilinearForm` be tested or demonstrated?

I'm not sure what the use case is.  The profiling I've done has been on quite narrow classes of problems but in no case has assembly been significant compared to meshing or solving.  I mean it looks like a good idea, I just don't know what kind of example to write to showcase it.

**Comment by kinnala** [comment]
I actually never had a real use case in mind. I just had an example where
the assembly took around 2 minutes without threading and less than a minute
with threading. I think the resulting matrix was so big that I'd never be
able to solve that on my laptop.

I could try to recreate that. Maybe now it needs to be a different
decorator altogether.

**Comment by kinnala** [comment]
This seems to work:
```python
import numpy as np

from timeit import timeit
from numba import njit
from skfem import *
from skfem.assembly.form.bilinear_form import BilinearForm

m = MeshTet()
m.refine(5)
basis = InteriorBasis(m, ElementTetP2())

class ThreadablePoissonForm(BilinearForm):
    @staticmethod
    @njit(nogil=True)
    def kernel(A, ix, u, v, w, dx):
        for k in range(ix.shape[0]): 
            i, j = ix[k]
            A[i, j] = np.sum((u[j][1][0]*v[i][1][0] +
                              u[j][1][1]*v[i][1][1] +
                              u[j][1][2]*v[i][1][2]) * dx, axis=1)

@bilinear_form
def bilinf(u, du, v, dv, w):
    return sum(du * dv)

def asm_multithreaded():
    return ThreadablePoissonForm(None).assemble(basis, nthreads=8)

def asm_singlethreaded():
    return asm(bilinf, basis)

print("Multithreaded assembly took " +
      str(timeit(asm_multithreaded, number=2)) + " s")
print("Singlethreaded assembly took " +
      str(timeit(asm_singlethreaded, number=2)) + " s")
```
But not so greatly:
```
Multithreaded assembly took 6.666582662001019 s
Singlethreaded assembly took 8.072949173998495 s
```
With larger problem:
```
Multithreaded assembly took 31.915914687000623 s
Singlethreaded assembly took 37.448626509998576 s
```
I wonder if this support should be dropped since the difference is not that great after all...

**Comment by kinnala** [comment]
Remark: Changes are required after Numba 0.46.0 release. It seems that they are dropping support for some of the type inference required here. This works now with 0.44.0 but you get a deprecation warning.
