### ISSUE TITLE
slower Mesh.load

### ISSUE THREAD

**Issue by gdmcbain** [kinnala/scikit-fem#214]
`Mesh.load` in Release 0.2.0 #195 is slower since it calls `Mesh._build_mappings` twice.

This is significant on larger problems.

To demonstrate it, a simple Gmsh GEO file was written:
```C++
SetFactory("OpenCASCADE");
Sphere(1) = {0.0, 0.0, 0.0, 1.0};
Physical Volume(1) = {1};
Physical Surface(1) = {1};
```
and a mesh generated with
```shell
gmsh -3 -clscale 6.25e-2 ball.geo
```
which gives 242 199 vertices—big enough to demonstrate the issue, small enough to be manageable.  

This is loaded with a basic Python script:

```python
from time import time

import skfem

tic = time()
mesh = skfem.MeshTet.load('ball.msh')
toc = time() - tic
print(f'Took {toc:.1f} s to load {mesh}')
```

On current master (95a485f) it takes 56.0 s, versus 32.8 s on tag 0.1.19 (a2bdb95).

Besides `time.time`, this was profiled with
```shell
python -m cProfile -o ball.prof -s cumtime ball.py
```
which shows that on master there are two calls to `._build_mappings` taking a cumulative 47.27 s versus one call on 0.1.19 taking 24.58 s.

* Scripts: [ball.tar.gz](https://github.com/kinnala/scikit-fem/files/3323750/ball.tar.gz)

**Comment by gdmcbain** [comment]
[SnakeViz](http://jiffyclub.github.io/snakeviz/) profile on master:

![snakeviz](https://user-images.githubusercontent.com/1588947/60072820-fe904380-9761-11e9-88ca-c2c60f5e464a.PNG)

and on 0.1.19:

![snakeviz](https://user-images.githubusercontent.com/1588947/60072878-2c758800-9762-11e9-9691-66bda2d188f2.PNG)

**Comment by kinnala** [comment]
I sort of understood this but I just wiped it under the rug because I thought it doesn't matter. The results of `_build_mappings` are used to do the matching between gmsh entities and ours. I'll investigate this later. This is my last week before the summer vacation.

**Comment by kinnala** [comment]
Maybe we could reuse the results of `_build_mappings` from the first call somehow? By injecting them to the resulting `Mesh` object and bypassing the second call? Is it too hacky?

**Comment by gdmcbain** [comment]
Yeah..., I was thinking about memoizing or something.  I'll look into this as its critical for the problems I'm currently working with (ten times as many nodes as this example).  Maybe an alternative constructor.  Maybe a 'proto-' mesh that doesn't have all the features of a `skfem.Mesh` but is a stepping-stone towards it.

Another avenue I'll investigate is why `numpy.unique` takes so long and whether it can be avoided.

**Comment by kinnala** [comment]
> Another avenue I'll investigate is why numpy.unique takes so long and whether it can be avoided.

These parts of the codebase (`_build_mappings`) are the oldest. Brainlessly ported some earlier Matlab scripts without thinking how this should actually be done in NumPy.

**Comment by kinnala** [comment]
Should be fixed by https://github.com/kinnala/scikit-fem/commit/84644ba728fdf6d8138223ce2866aa803cbd58fb

Can you confirm @gdmcbain ?

**Comment by gdmcbain** [comment]
Yes, that's fixed.  Thanks!
