### ISSUE TITLE
Add doflocs to all Element subclasses

### ISSUE THREAD

**Issue by kinnala** [kinnala/scikit-fem#224]
Remaining work from #223 .

**Comment by kinnala** [comment]
done: ElementTetP0-P2, ElementTriP0-P2, ElementQuad2

**Comment by kinnala** [comment]
ElementVectorH1 should also work

**Comment by gdmcbain** [comment]
There was an interesting comment on a question like this on the Firedrake list before Christmas, which I'm reminded of while thinking again about higher order plotting #287. Someone had (much as in #84 #223) [asked](http://mailman.ic.ac.uk/pipermail/firedrake/2019-December/003953.html) whether:

> it is possible to access the list of all points used by piecewise quadratic (or higher order) elements on a regular mesh.

Matt Knepley [replied](http://mailman.ic.ac.uk/pipermail/firedrake/2019-December/003954.html):

> The problem is that this is a completely crazy way of thinking about finite
elements that we are stuck with thanks to Tom Hughes and his followers. Coordinates on a mesh are a field, just like any other
field, and are discretized using a finite element space, just like any other field. What are the consequences of this?

> 1) You should not assume that the dual basis for coordinates are point evaluation functionals, or another way, not assume that we store coordinates by the values at certain points that you know ahead of time. For example, we might store them as Bezier curves, or splines, or using model DG.

> 2) If you want the coordinates at a point, you should interpolate them there just as you would a solution field.

> 3) You cannot assume that coordinates use the same space, or degree, as the solution.

This is certainly onerous for the interpolation. Is it too doctrinaire? Or is looking at things in this way important e.g. for flexibility w.r.t. future generalizations? I haven't decided, but a stimulating comment, I think.

**Comment by kinnala** [comment]
I'm not completely sure I follow this but it might have to do with the fact that I have not looked too much into isoparametric/isogeometric methods.

**Comment by kinnala** [comment]
#305 has now also ElementHex1.

**Comment by kinnala** [comment]
Missing are Argyris, Morley, tri_rt0, tet_rt0, tet_n0.

**Comment by kinnala** [comment]
Missing
- [ ] tet_n0
- [ ] tet_rt0
