### ISSUE TITLE
FacetBasis on MeshQuad

### ISSUE THREAD

**Issue by gdmcbain** [kinnala/scikit-fem#244]
There seems to have been a regression involving `MeshQuad.boundaries` since July.  

A previously working (but too complicated to share) example now raises
```  File "/home/geordie/src/scikit-fem/skfem/assembly/global_basis/facet_basis.py", line 121, in __init__
    Y = self.mapping.invF(x, tind=self.tind)
  File "/home/geordie/src/scikit-fem/skfem/mapping/mapping_isoparametric.py", line 143, in invF
    raise ValueError("Inverse mapped point outside reference element!")
```
after a call like 
```python
FacetBasis(mesh, element, facets=mesh.boundaries['outlet'])
```

I'll reproduce this in a simpler example shortly.

**Comment by gdmcbain** [comment]
A minimally modified version of the Boussinesq _k_-factor example ex12 failed to reproduce the error; it worked fine.

I'll post it here as an example of generating and using `MeshQuad`.
[ex12-quad.tar.gz](https://github.com/kinnala/scikit-fem/files/3839519/ex12-quad.tar.gz).

```python
from skfem import *
from skfem.models.poisson import laplace, unit_load
from skfem.importers import from_meshio

import numpy as np

from pygmsh import generate_mesh
from pygmsh.built_in import Geometry

geom = Geometry()
circle = geom.add_circle([0.] * 3, 1., .5**3)
geom.add_raw_code('Mesh.RecombineAll=1;')
geom.add_raw_code('Recombine Surface {};'.format(circle.plane_surface.id))
geom.add_physical(circle.line_loop.lines, 'circle')
geom.add_physical(circle.plane_surface, 'disk')
m = from_meshio(generate_mesh(geom, dim=2))

basis = InteriorBasis(m, ElementQuad1())

A = asm(laplace, basis)
b = asm(unit_load, basis)

D = basis.get_dofs(m.boundaries['circle']).all()

x = solve(*condense(A, b, D=D))

area = sum(b)
k = b @ x / area**2

if __name__ == '__main__':
    print('area = {:.4f} (exact = {:.4f})'.format(area, np.pi))
    print('k = {:.5f} (exact = 1/8/pi = {:.5f})'.format(k, 1/np.pi/8))

    m.save('k.xdmf', {'w': x[basis.nodal_dofs[0]]})
```

**Comment by gdmcbain** [comment]
The `ValueError` is raised by attempting
```python
FacetBasis(m, ElementQuad1())
```
anywhere after the definition of the `MeshQuad m`.

**Comment by gdmcbain** [comment]
Broken example: 
[ex12-quad.tar.gz](https://github.com/kinnala/scikit-fem/files/3839535/ex12-quad.tar.gz).

**Comment by gdmcbain** [comment]
```python
fb = FacetBasis(m, e, MappingAffine(m))
```
works.  The default is `MappingIsoparametric`.

**Comment by gdmcbain** [comment]
The affine mapping doesn't really work though, in the real example where the `FacetBasis` is actually used (to apply a Neumann boundary condition).  It runs without raising an error but the numerical results are rubbish.

**Comment by gdmcbain** [comment]
I'll try to construct a better example of the issue tomorrow and then git bisect.

**Comment by gdmcbain** [comment]
`FacetBasis` seems to work fine on a default `MeshQuad` as in `ex01`; e.g., parameterizing the mesh and element in `ex01` to optionally use `MeshQuad` and `ElementQuad1`

```python
from argparse import ArgumentParser

parser = ArgumentParser(description='Dirichlet-Poisson on unit square')
parser.add_argument('-q', '--quad', help='use MeshQuad', action='store_true')
args = parser.parse_args()

if args.quad:
    m = MeshQuad()
    e = ElementQuad1()
else:
    m = MeshTri()
    e = ElementTriP1()
```

and adding a postprocess computation of the flux through the boundary:

```python
@linear_form
def flux(v, dv, w):
    return sum(dv * w.n)

fb = FacetBasis(m, e)
…
f = asm(flux, fb)
…
print('flux:', f @ x)
```

works fine with or without (i.e. using default `MeshTri` and `ElementTriP1`) the `-q` flag.

The modified example: [ex01_quad.tar.gz](https://github.com/kinnala/scikit-fem/files/3844348/ex01_quad.tar.gz).

**Comment by gdmcbain** [comment]
`FacetBasis` also works if the `MeshQuad` is constructed from the product of two `MeshLine`s.
```python
    l = MeshLine(np.linspace(0, 1, 2**4))
    m = l * l
 ```

**Comment by gdmcbain** [comment]
The error seems only to be raised when the `MeshQuad` is loaded via `meshio`; e.g. `MeshQuad.load('quad.msh')`.

I removed `pygmsh` from the problem and wrote a couple of simple GEO files, `tri.geo`:


```
Point(1) = {0, 0, 0};
Point(2) = {1, 0, 0};
Point(3) = {0, 1, 0};
Point(4) = {-1, 0, 0};
Point(5) = {0, -1, 0};

Circle(1) = {2, 1, 3};
Circle(2) = {3, 1, 4};
Circle(3) = {4, 1, 5};
Circle(4) = {5, 1, 2};

Curve Loop(1) = {1:4};
Plane Surface(1) = {1};

Physical Curve("circle") = {1:4};
Physical Surface("domain") = {1};
```

and `quad.geo`:
```
Include "tri.geo";
Recombine Surface {1};
```

then testing with

```python
m = MeshQuad.load('quad.msh')
e = ElementQuad1()
fb = FacetBasis(m, e)
```

suggested by bisection that the error was introduced in [7477d4b1317e7f512325ab0fc702f69ba7584e8c] `Add Exception if inverse mapping is outside of reference element`; however, that just looks like the error was detected then and might have been lurking earlier so I'd better write a better test.

**Comment by gdmcbain** [comment]
> The error seems only to be raised when the MeshQuad is loaded via meshio; e.g. MeshQuad.load('quad.msh').

The error is not raised if the mesh is loaded from meshio after having been saved from scikit-fem; e.g.

```python
@functional
def circumference(w):
    return 1.


l = MeshLine(np.linspace(0, 1, 3))
m = l * l
e = ElementQuad1()
fb = FacetBasis(m, e)

print(asm(circumference, fb))

fname = 'quad.vtk'
m.save(fname)
m0 = MeshQuad.load(fname)
print(m0)
fb0 = FacetBasis(m0, e)
print(asm(circumference, fb0))
```
    
in both cases correctly computes a circumference of 4.0.

**Comment by gdmcbain** [comment]
Is what's happening here that having computed the global (x, y) coordinates of the boundary quadrature points on the line facets that skfem then tries to compute where these are in relation to the associated quadrilateral, in reference coordinates, and that in the general case finds half the time that they're 'outside'? If so, would it be reasonable to put a tolerance on what's considered outside?

I'm guessing that why this has been tricky to track down is that when the quadrilateral element isn't sheared or rotated relative to the reference, the mapping of the boundary quadrature points to the reference quad is exact.

**Comment by kinnala** [comment]
Without looking into this more carefully, I'd try first the ordering of the
nodes (clockwise or counter-clockwise). I think an assumption is made
regarding that when evaluating basis functions and normals on the boundary.
I'll try to look into this asap.

**Comment by kinnala** [comment]
Issue is most likely in this method:

https://github.com/kinnala/scikit-fem/blob/70aa668560e76925a35f87b1c659a8e8f8ebda23/skfem/mapping/mapping_isoparametric.py#L132

I've had some issues with the iteration before.

**Comment by kinnala** [comment]
Could try e.g. projecting back to the quadrilateral or different initial
guess.

**Comment by gdmcbain** [comment]
```python
 if np.sum(dX) < 1e-6:
```

Should this use a norm rather than a sum?

**Comment by gdmcbain** [comment]
But isn't the real issue that the test against exteriority isn't appropriate when applied to facet quadrature points, which ideally would lie on the boundary of the element and so be marginally exterior?

**Comment by kinnala** [comment]
You might very well be correct. We could try adding e.g. a constraint to
the iteration and see what happens.

**Comment by gdmcbain** [comment]
O. K., I've finally come up with a minimal example.

```python
m0 = MeshQuad()
m = MeshQuad([[0, 1, 1, 0],
              [0, .1, 1, 1]],
             m0.t)
e = ElementQuad1()
FacetBasis(m0, e)
FacetBasis(m, e)
```

On `master`, this raises the `ValueError` from `invF` on the last line but not the secondlast line.  With the tolerance for the exteriority test in `invF` #252, it runs without error.
