### ISSUE TITLE
examples fail on latest released version

### ISSUE THREAD

**Issue by gdmcbain** [kinnala/scikit-fem#247]
Version 0.2.0 installed with `pip` can't run the current examples which expect `condense` to `expand` #228; i.e. ex01, 02, 05, 06, 09, …, ex28.  This leads to various errors, depending on how the solution vector is subsequently interpreted

Also ex29 fails with `NameError: name 'ElementLineP2' is not defined` #235.

**Comment by gdmcbain** [comment]
```bash
conda deactivate
conda create -n skfem-ex28
conda activate skfem-ex28
conda install pip
pip install scikit-fem
pip install pygmsh
wget https://raw.githubusercontent.com/kinnala/scikit-fem/master/docs/examples/ex28.py
python ex28.py
```

**Comment by kinnala** [comment]
I drafted new version 0.2.1. I should've called it 0.3.0 as it was backwards-incompatible, but oh well. I'm certain 1.0.0 happens during spring and after that I'm more careful with semver.
