### ISSUE TITLE
acceptance criterion for MappingIsoparametric.invF

### ISSUE THREAD

**Issue by gdmcbain** [kinnala/scikit-fem#251]
After the termination criterion for `MappingIsoparametric.invF` #249 comes the acceptance criterion

https://github.com/kinnala/scikit-fem/blob/70aa668560e76925a35f87b1c659a8e8f8ebda23/skfem/mapping/mapping_isoparametric.py#L142-L143

It was pondered in the investigation into the regression of `FacetBasis` for `MeshQuad` #244 that 
> the test against exteriority isn't appropriate when applied to facet quadrature points, which ideally would lie on the boundary of the element and so be marginally exterior.

In the same example snippet as used in #249 
```python
m = MeshQuad()
e = ElementQuad1()
fb = FacetBasis(m, e, facets=[0])
x = fb.mapping.G(fb.X, find=fb.find)
Y = fb.mapping.invF(x, tind=fb.tind)
```
again stepping through the last call with `pdb`, but this time replacing the `np.sum` termination criterion with the `np.linalg.norm` #250 , the terminal value of `X` is
```python
array([[[-0.77459667,  0.        ,  0.77459667]],

       [[-1.        , -1.        , -1.        ]]])
```
which makes `x - self.F(X, tind)` vanish identically but `np.abs(X)` is
```
array([[[0.77459667, 0.        , 0.77459667]],

       [[1.        , 1.        , 1.        ]]])
```
which is clearly marginal for `(np.abs(X) > 1.0).any()`.

I think I can imagine that in a less trivial case than `MeshQuad()`, the `X` produced by the Newton iteration and satisfying the termination criterion might also have components satisfying `np.abs(X) > 1.0`, if only by a little.

**Comment by gdmcbain** [comment]
So what about a bit of tolerance?
```python
        if (np.abs(X) > 1.0 + 1e-12).any():
```

**Comment by gdmcbain** [comment]
Thinking a bit more about this acceptance criterion

https://github.com/kinnala/scikit-fem/blob/70aa668560e76925a35f87b1c659a8e8f8ebda23/skfem/mapping/mapping_isoparametric.py#L142-L143

which I had been calling a test against exteriority, isn't it only that for a hypercube (MeshQuad or MeshHex)? Is MappingIsoparametric only used on such meshes? On a simplicial mesh, wouldn't the test have a lot of false negatives?

**Comment by kinnala** [comment]
Currently, yes. Although I used it for curved triangular elements earlier.

**Comment by gdmcbain** [comment]
Actually was the acceptance criterion only needed because of the buggy termination criterion? Could it just be cut now?

**Comment by kinnala** [comment]
It was used also earlier to discover bugs in the indexing of local finite element bases that caused boundary mappings to fail for hexahedral elements. I don't recall all details, but I suppose it can be turned into a test instead so that it could discover similar bugs in the future.

**Comment by gdmcbain** [comment]
Following up these last questions in #256.
