### ISSUE TITLE
Running ex17 test fails

### ISSUE THREAD

**Issue by kinnala** [kinnala/scikit-fem#275]
For some reason generate_mesh adds both triangular and quadrilateral elements to the resulting Mesh object when using RecombineAll=1. Thus, using the automatic mesh type detection mechanism in importers.meshio doesn't work as such. I'm working on a temporary fix which allows forcing the mesh type. For some reason ex17 wasn't run under the test suite.

**Comment by gdmcbain** [comment]
I'm puzzled at this.  Could you elaborate?  I'm running
```bash
$ gmsh -version
4.5.0-git-0c1b63c8d
```
and
```bash
$ pip list | grep pygmsh
pygmsh                        6.0.2       /home/geordie/src/pygmsh   
```
under Ubuntu 19.10 and can't reproduce; i.e. (at, say, line 146 of `generate_mesh`) I get
```python
'quad' in mesh.cells and 'triangle' not in mesh.cells
```
thus in `skfem.importers.meshio.from_meshio`, I get `meshio_type == 'quad'`.

**Comment by gdmcbain** [comment]
I've reproduced a failure of ex17.  (Not as a test, just as a script, but I think it's the same.)  This was running under Microsoft Windows 10 with Gmsh 3.0.6.  

Gmsh introduces some triangles
```
Info    : Blossom completed (0.02 s):   312 quads     0 triangles 0 invalid quads  0 quads with Q < 0.1 Avg Q = 0.744 Min Q 0.461
Info    : Meshing surface 10 (Plane, Delaunay)
Info    : Blossom: 1032 internal 132 closed
Info    : Blossom completed (0.02 s):   318 quads     6 triangles 0 invalid quads  0 quads with Q < 0.1 Avg Q = 0.738 Min Q 0.422
```
which raises the expected
```
Exception: Mesh._validate(): Mesh contains a vertex not belonging to any element.
```

**Comment by gdmcbain** [comment]
I think ex17 should be modified to never produce a mixed mesh rather than the library modified to handle such a case.

I think this can be done in Gmsh (see comments in #276) and so via `geom.add_raw_code`; otherwise the example should revert to a simplicial mesh.

**Comment by gdmcbain** [comment]
```python
geom.add_raw_code('Mesh.RecombinationAlgorithm=3;\n');
```

**Comment by gdmcbain** [comment]
A catch though:  I don't think there are that many recombination algorithms in older Gmsh in which case Gmsh seems to silently ignore the option!  That means that on exactly the problematic old versions of Gmsh, the fix doesn't work!  However, `RecombinationAlgorithm=2` seems O. K.
