### ISSUE TITLE
Get rid of matplotlib depedency?

### ISSUE THREAD

**Issue by kinnala** [kinnala/scikit-fem#286]
Should we move the plotting related functionalities from `Mesh` classes into separate files so that `matplotlib` can be an optional dependency? I've really enjoyed the simplicity of
```
m = MeshTri()
m.draw()
```
when experimenting and would like that similar workflow remains but I suppose it would be enough to have
```
m = MeshTri()
skfem.visualize.draw(m)
```
and
```
m = MeshTri()
skfem.visualize.plot(m, m.p[0, :])
```
to do simple plotting.

What do you think @gdmcbain ?

**Comment by gdmcbain** [comment]
Yes, if possible. Matplotlib seems to bring in a lot of other things. I was puzzled to see an entry for pyparsing Japanese in the output of cProfile for #280 recently.

**Comment by kinnala** [comment]
I can work on this, shouldn't be a huge refactor.

**Comment by kinnala** [comment]
I've also considered of building a separate `meshplots` library which would utilize also other tools such as `plotly` and allow simple plotting from all sorts of mesh formats. But moving these into separate modules should suffice for now.

**Comment by gdmcbain** [comment]
I've also been experimenting on three-dimensional visualization with:
* yt: but it only reads Exodus II and doesn't seem to like the flavour from meshio
* pyvista: but it doesn't like my graphics card or Mesa or something.

**Comment by kinnala** [comment]
Remaining work:
- [ ] add the removed functionality to `skfem.visualize`
- [ ] fix examples and tests

**Comment by gdmcbain** [comment]
Running
```shell
parallel python {} ::: docs/examples/ex*.py
```
reveals a few more examples to be updated: exx 04, 13, 18, 21, 24:
```
AttributeError: 'MeshTet' object has no attribute 'draw'
```
or
```
AttributeError: 'MeshTri' object has no attribute 'plot'
```
