### ISSUE TITLE
Add pacopy to the test suite

### ISSUE THREAD

**Issue by kinnala** [kinnala/scikit-fem#290]
https://github.com/kinnala/scikit-fem/blob/57d1962a3cc9e70fe30712c1bdc6f7afdefeaaf8/tests/test_examples.py#L174

**Comment by gdmcbain** [comment]
This is a good idea. We'll probably want to shorten ex27 though. Or rather have it run in a short way if imported, as in the test suite, but longer if invoked from the command-line, to generate the nice figures for the documentation; say fewer and lower milestones in Reynolds number for the test, probably just the first nonzero will do.
