### ISSUE TITLE
starting guess for solve

### ISSUE THREAD

**Issue by gdmcbain** [kinnala/scikit-fem#300]
SciPy's iterative solvers like [`scipy.sparse.linalg.cg`](https://docs.scipy.org/doc/scipy/reference/generated/scipy.sparse.linalg.cg.html#scipy.sparse.linalg.cg) optionally accept `x0`, a ‘starting guess for the solution’.  This could be passed to `skfem.utils.solver_iter_krylov` or similar, but in some situations, e.g. a transient simulation with unchanging evolution operator, the previous solution might be a good guess and this changes at each time.  One could reconstruct the solver at each time step (saving the preconditioner and other constant options), but maybe it would be tidier to be able to pass `x0` directly to `skfem.utils.solve` after the `LinearOperator A` and right-hand side `b`?

**Comment by kinnala** [comment]
Resolved by #304 .
