### ISSUE TITLE
Add check that integration orders match

### ISSUE THREAD

**Issue by kinnala** [kinnala/scikit-fem#309]
When assembling Petrov-Galerkin -type of matrices with `asm` using two different `InteriorBasis` objects (different solution and test function bases), there is no check that the two objects have equal integration order. It should be easy to check since the current error message is very unhelpful:
```
Exception in thread Thread-12:
Traceback (most recent call last):
  File "/home/tom/.conda/envs/scikit-fem-dev/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/home/tom/.conda/envs/scikit-fem-dev/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/tom/src/scikit-fem/skfem/assembly/form/bilinear_form.py", line 23, in kernel
    A[i, j] = np.sum(self.form(*ubasis[j], *vbasis[i], w) * dx,
  File "/home/tom/src/scikit-fem/docs/examples/contact.py", line 172, in proj_cauchy
    return C(Eps(du))[itr, jtr] * v
ValueError: operands could not be broadcast together with shapes (390,3) (390,6) 
```
Took me a while to debug that what's going on.

**Comment by gdmcbain** [comment]
Ah yes, good idea; I've seen that error message before and it took me a while to debug too. I think that was in the pressure-volume forms of the Stokes equation with Taylor-Hood elements.

So this is good but it also reminds me of an idea for possible future generalization (not v1, maybe v2, v3, …). Some use is made in the finite element method of reduced integration for special purposes (mass-lumping, stabilization).. It might be good to allow the user to specify not merely the order of integration but also the quadrature scheme. The check then would be that the schemes or at least their abscissæ match.
