### ISSUE TITLE
mesh-convergence in structural vibration

### ISSUE THREAD

**Issue by gdmcbain** [kinnala/scikit-fem#318]
I'm a bit puzzled at the eigenfrequencies in the ‘structural vibration’ [ex21](https://kinnala.github.io/scikit-fem-docs/examples/ex21.html) when the mesh is refined; they don't seem to converge before my machine runs out of memory.  This is using the geometry of ex21 but also other simple ones like flattish elongated boxes like beams or plates, including ones with multiple materials #315.

Of course boundaries aren't preserved during refinement #104, but in ex21 they're easily recovered with 
```python
m.boundaries['fixed'] = m.facets_satisfying(lambda x: x[2] == 0.)
```
after the call to `m.refine`.

Here's my minimally modified ex21: [beams.py.txt](https://github.com/kinnala/scikit-fem/files/4094189/beams.py.txt).  Calling it with `python beams.py -r 0`, `-r 1`, `-r 2` gives:

0. [ 80.17036319 179.80324866 214.18727331]
1. [ 61.02158326 135.15096073 149.1143932 ]
2. [ 49.63520068 110.2739215  118.82280969]

and `-r 3` runs out of memory.

The eigenfrequencies of beams &c. similarly don't converge to the known analytical solutions, whereas I've checked in another code (ANSYS) using the same mesh and they do.  (This was behind my interest in serendipity elements #314 but I subsequently found that ANSYS also got accurate answers on coarse meshes with linear 8-node hexahedra.  It's hard to know exactly what ANSYS is doing, of course, but I don't expect anything too fancy here.)

I'll checkout the WIP #317 without threading and try to see more clearly what the linear elastic forms are doing.

Most likely I'm making a small simple error somewhere, perhaps of interpretation, perhaps a little bug in the script.

**Comment by gdmcbain** [comment]
I am getting much less mesh-dependent eigenfrequencies in the two-dimensional ex03:

0. (50, 10) [0.01029339 0.05554975 0.08188535 0.13264495 0.22105733 0.24485105]
1. (100, 20) [0.0102668  0.05535409 0.0818689  0.1320289  0.21972848 0.24472409]
2. (200, 40) [0.01025974 0.05530334 0.08186304 0.13187295 0.21939837 0.24468756]

**Comment by kinnala** [comment]
This is related #75 . Apparently the name of the example changed?

**Comment by gdmcbain** [comment]
Duplicate of #75.
