### ISSUE TITLE
MeshQuad.plot nodal function

### ISSUE THREAD

**Issue by gdmcbain** [kinnala/scikit-fem#32]
`mesh.MeshQuad.plot` says

> Visualize nodal or elemental function (2d).

but for nodal functions it raises

> `Exception`: The parameter `x` must have one value per element.

Minimal example:
```python
m = MeshQuad()
m.plot(m.p[0])
```

The function passed in is passed on to `self._splitquads` which unless `len(x) = self.t.shape[1]` (i.e. `x` has as many values as there are quadrilateral elements) raises the exception.

**Comment by kinnala** [comment]
Fixed in PR.
