### ISSUE TITLE
specify quadrature

### ISSUE THREAD

**Issue by gdmcbain** [kinnala/scikit-fem#326]
One of the things arising from the recent investigation into the poor behaviour of elastic modal analysis with `ElementTetP1` #75 was the idea of reduced quadrature; e.g. in discussing `ElementHex1`, Petyt (1990, [_Introduction to Finite Element Vibration Analysis_](https://doi.org/10.1017%2fCBO9780511624292), Cambridge University Press, §5.8) recommends a rule with one abscissa at the centroid.  Reduced quadrature or ‘selective integration’ is also discussed by

* Benzley, S. E., Perry, E., Merkley, K., Clark, B. & Sjaardema, G. (1995). [A comparison of all hexagonal and all tetrahedral finite element meshes for elastic and elasto-plastic analysis](https://imr.sandia.gov/papers/abstracts/Be15.html). In T. Tautges (ed.), In Proceedings, 4th International Meshing Roundtable (pp. 179–191).

although their practical recommendation is for increasing the order of the element as done here in #322.

Currently I don't see an easy way to experiment with quadrature in scikit-fem.  I think though that enabling this would be simple generalization of the constructor for [`skfem.assembly.Basis`](
https://github.com/kinnala/scikit-fem/blob/89f726808f50bf9773f1e2c7d43248ccbd0714a0/skfem/assembly/basis/basis.py#L26).

https://github.com/kinnala/scikit-fem/blob/89f726808f50bf9773f1e2c7d43248ccbd0714a0/skfem/assembly/basis/basis.py#L26

or maybe

https://github.com/kinnala/scikit-fem/blob/89f726808f50bf9773f1e2c7d43248ccbd0714a0/skfem/assembly/basis/interior_basis.py#L35-L40

(and similarly for [`FacetBasis`](https://github.com/kinnala/scikit-fem/blob/89f726808f50bf9773f1e2c7d43248ccbd0714a0/skfem/assembly/basis/facet_basis.py#L36-L42)) so that either one specifies:
* the actual quadrature rule, i.e. `X` and `W` which become attributes of the `InteriorBasis`, or
* `intorder: int` as now, and the rule is computed from [`skfem.quadrature.get_quadrature`](https://github.com/kinnala/scikit-fem/blob/89f726808f50bf9773f1e2c7d43248ccbd0714a0/skfem/quadrature.py#L8), or
* nothing, also as now, and `intorder` is computed from [`self.elem.maxdeg`](https://github.com/kinnala/scikit-fem/blob/89f726808f50bf9773f1e2c7d43248ccbd0714a0/skfem/assembly/basis/basis.py#L52).

A possible further modification is that the type of the rule returned by `get_quadrature` is `Tuple[ndarray, ndarray]` from which it is unclear which is weights and which abscissae.  Perhaps a quadrature rule might be represented as in [`quadpy.nsimplex._helpers.NSimplexScheme`](https://github.com/nschloe/quadpy/blob/ef2fe0720c08a9a563c8f9ba678e0e44e190c89d/quadpy/nsimplex/_helpers.py#L8-L9) as an object with attributes `weights` and `points`, or more simply as a `NamedTuple` (or `dataclass`) with similarly named attributes; given Python's duck-typing, reference from within `skfem.assembly` only to attributes `weights` and `points` might enable direct use of one of the many schemes from quadpy while only importing it at the top-level user-script in which the basis is instantiated.

I don't think that this is urgent—I don't have any immediate plans to use it myself—but it seems like an easy addition and something that should be present in a general finite element library.  I think it's mostly a matter of deciding on the desired syntax.

**Comment by kinnala** [comment]
I think this is a good idea and I'll take these into account. I'm now looking into revamping `skfem.quadrature` while I'm hacking with the reference elements.

**Comment by kinnala** [comment]
I spent some time looking into quadpy but couldn't find any documentation on the reference domains used by the quadrature rules. Since rules for triangles return 3-vectors:
```
In [25]: s.points                                                                                     
Out[25]: 
array([[0.5       , 0.5       , 0.        ],
       [0.16666667, 0.16666667, 0.66666667],
       [0.5       , 0.        , 0.5       ],
       [0.16666667, 0.66666667, 0.16666667],
       [0.        , 0.5       , 0.5       ],
       [0.66666667, 0.16666667, 0.16666667]])
```
my guess is that it is using barycentric coordinates which is not directly compatible with the reference domains used in scikit-fem. So we would still need to create some sort of transformation if a NamedTuple with weights and points was used.

So for now I'm dropping

> Perhaps a quadrature rule might be represented as in quadpy.nsimplex._helpers.NSimplexScheme as an object with attributes weights and points, or more simply as a NamedTuple (or dataclass) with similarly named attributes; given Python's duck-typing, reference from within skfem.assembly only to attributes weights and points might enable direct use of one of the many schemes from quadpy while only importing it at the top-level user-script in which the basis is instantiated.

and focusing on the former approach.

**Comment by gdmcbain** [comment]
Ah.  I hadn't looked in detail into quadpy, sorry.  I think it works like this:
```python
tri = skfem.MeshTri()
triangle = tri.p[:, tri.t][:, :, 0]

abscissæ = quadpy.triangle.strang_fix_cowper_03().points
```
then `triangle @ abscissæ.T` is
```
[[0.33333333 0.2        0.6        0.2       ]
 [0.33333333 0.6        0.2        0.2       ]]
```
which is the same as `skfem.quadrature.get_quadrature_tri(3)[0]`.  (This isn't the same as the rule in your snippet, but I wasn't sure which one that was; there are a lot in `quadpy.triangle`.)

**Comment by kinnala** [comment]
I see. Can this made work equivalently for triangles and rectangles or not? I'm still thinking your suggestion:

> Perhaps a quadrature rule might be represented as in quadpy.nsimplex._helpers.NSimplexScheme as an object with attributes weights and points, or more simply as a NamedTuple (or dataclass) with similarly named attributes; given Python's duck-typing, reference from within skfem.assembly only to attributes weights and points might enable direct use of one of the many schemes from quadpy while only importing it at the top-level user-script in which the basis is instantiated.

NSimplexScheme probably works only for simplices. That's why they have https://github.com/nschloe/quadpy/blob/master/quadpy/ncube/_helpers.py#L8 right?

**Comment by gdmcbain** [comment]
> Can this made work equivalently for triangles and rectangles or not?

Hmm, I see.  No, I haven't worked out a way to cajole these into acting the same.  I wonder why it's done the way it is.  Oh well.  Sorry for the false lead.

**Comment by kinnala** [comment]
Nevertheless, I still don't oppose using these representations in `skfem.quadrature`. I think it pays off in the long term to be compatible with other packages in the ecosystem.

**Comment by gdmcbain** [comment]
I wonder whether multiple inheritance would help here; e.g. deriving `MeshTet` from `MeshSimplex` as well as `Mesh3D`.
