### ISSUE TITLE
expose element lengths

### ISSUE THREAD

**Issue by gdmcbain** [kinnala/scikit-fem#331]
Stabilization techniques like ‘streamwise diffusion’ ([Elman, Silvester & Wathen 2014, §6.3.2](doi.org/10.1093/acprof:oso/9780199678792.003.0007)) are based on an ‘element Péclet number’ which requires a measure of the length of the local element.

The details of the definition vary (Elman et al p. 253 prefer ‘a measure of the element length in the direction of the wind’), but a simple start on this might be to expose of the local variable `lengths` in

https://github.com/kinnala/scikit-fem/blob/0065458db249a91380f88a6c4286738b5dc97731/skfem/mesh/mesh3d/mesh3d.py#L41-L44

and similarly the argument of `max` in

https://github.com/kinnala/scikit-fem/blob/0065458db249a91380f88a6c4286738b5dc97731/skfem/mesh/mesh2d/mesh2d.py#L43-L46

Then `param` could be moved up to the common superclass `skfem.Mesh`.

**Comment by kinnala** [comment]
In bilinear form definition you can use w.h which should do the trick.
