### ISSUE TITLE
Improve test infrastructure

### ISSUE THREAD

**Issue by kinnala** [kinnala/scikit-fem#333]
I'd like to run the tests in a Docker container so that I'm able to locally figure out what went wrong in the build. Simultaneously I'd change the test infrastructure to use `pytest`.

My plan is
- to create `/docker_tests/Dockerfile`
- push manually the testing container to Dockerhub
- follow instructions at https://docs.travis-ci.com/user/docker/ to run tests inside the container

**Comment by gdmcbain** [comment]
There are lots of advantages to pytest, yes; I think its worth switching to it from what's available in the standard library.

I also like the idea of containerization. I haven't quite been convinced that Docker is the last word in that, but if it's supported by the continuous integration system then it's worth using, yes.
