### ISSUE TITLE
internal boundaries from meshio not in bndfacets

### ISSUE THREAD

**Issue by gdmcbain** [kinnala/scikit-fem#336]
I was porting some old one-dimensional code to scikit-fem and found that whereas previously I had identified an internal vertex facet as a `Physical Point` in the Gmsh GEO, this wasn't picked up by `skfem.io.meshio.from_meshio`.

Roughly the code is like:
```python
from pygmsh import generate_mesh
from pygmsh.built_in import Geometry

import meshio
import skfem
from skfem.io import from_meshio

geom = Geometry()
points = []
lines = []
for x in range(3):
    points.append(geom.add_point([x, 0., 0.]))
    if len(points) > 1:
        lines.append(geom.add_line(*points[-2:]))                     
geom.add_physical(points[0], 'start')
geom.add_physical(points[1], 'middle')
geom.add_physical(points[2], 'end')
geom.add_physical(lines, 'domain')
mesh = from_meshio(generate_mesh(geom, dim=1))
``` 
Then `mesh.boundaries` is missing `'middle'`:
```python
{'start': array([0]), 'end': array([2])}
```

The reason is simple:

https://github.com/kinnala/scikit-fem/blob/61424c55508954e71302c78dc5e6637883f68a27/skfem/io/meshio.py#L101

`index` doesn't include `'middle'` because it's not in `bndfacets`.

I haven't decided whether the current behaviour is better or it should be changed to permit the definition of internal facets.  Here I was just going to use it as a probe point at which to simply sample the solution without having to interpolate.  I wonder whether the latter might be interesting for other applications (interfacial sources? domain decomposition into subdomains?).

**Comment by kinnala** [comment]
So Gmsh and other mesh generators allow, in general, defining these named sets of interior facets (i.e. interfaces)? Then I think we should support it since one might want to, e.g., integrate over a set of interior facets, or use line loads like we did here in Fig. 7: https://arxiv.org/pdf/1707.08396.pdf.

Do you have time to add some tests that
- `define_boundary`
- `get_dofs` (not important since will be deprecated)
- `boundary_dofs`
- correct subsets are preserved when uniformly refined (for supported elements, e.g., `MeshTri` and `MeshQuad`)
work properly with the named interfaces?

**Comment by gdmcbain** [comment]
> So Gmsh and other mesh generators allow, in general, defining these named sets of interior facets (i.e. interfaces)? 

Yes, though they're not quite facets, they're independent (n-1)-dimensional elements, supported on the same points as the domain elements, that happen to coincide with facets. Their most obvious use is patches of boundary but Gmsh doesn't enforce this in any way. 

Also they aren't restricted to n-1 dimensions, any dimension ≤ n is fine; e.g. one can define a Physical Point, a Physical Curvr, a Physical Surface, and a Physical Volume in a tetrahedral mesh. Currently the things of dimension < n - 1 [I've forgotten what the things of lower dimension than facets in a complex are called ] aren'r represented in a skfem.Mesh. I mean they do have .p and Mesh3d has .edges but there aren't named subsets of these like .boundaries and .subdomains. 

I'll write the tests in the morning.

**Comment by gdmcbain** [comment]
> preservation of named subsets when uniformly refined (for supported elements, e.g., MeshTri and MeshQuad)

I hadn't realized that some elements were supported like this, i.e. that some parts of #104 were complete; I last hit #104 when attempting uniform refinement of beams.msh in ex21 in #75, but that's MeshTet. Well that's a good start anyway, I'll include them.

**Comment by gdmcbain** [comment]
Thanks for ‘A posteriori estimates…’; very nice.

I have solved a much simpler two-dimensional Poisson problem in FreeFem++ a few years ago, following on a discussion on that mailing list, [‘Poisson solution at interface’](https://ljll.math.upmc.fr/pipermail/freefempp/2014-October/003621.html).  In my version, I generated the mesh in Gmsh 2.14.2 using
```c++
Point(1) = {0, 0, 0};

Extrude {(1 + Sqrt(5)) / 2, 0, 0} {Point{1};}
Extrude {0, 1, 0} {Line{1};}
Extrude {0, 1, 0} {Line{2};}

Line Loop(10) = {4, 8, -6, -7, -3, 1};
Line Loop(11) = {2, -4, -1, 3};
Plane Surface(12) = {11};

Line Loop(13) = {8, -6, -7, 2};

Plane Surface(14) = {13};

Physical Surface("solid", 11) = {9, 5};

Physical Line("cold", 1) = {6};
Physical Line("heater", 2) = {2};
```
which gives a triangulation of a rectangle 0 < _x_ < _&phi;_, 0 < _y_ < 2, with a line marked across _y_ = 1.  

![superficial msh](https://user-images.githubusercontent.com/1588947/74790279-3e1c2900-530b-11ea-814d-cedbfeda56ff.png)

This was solved with _u_ = 0 on _y_ = 2, the rest of the boundary insulated, and a unit source on the marked internal line.  Since this is really a one-dimensional problem, the exact solution is easy: _u_ = 1 in 0 < _y_ < 1 and _u_ = 2 &minus; _y_ in 1 < _y_ < 2.  

![superficial](https://user-images.githubusercontent.com/1588947/74790623-3e68f400-530c-11ea-8fc6-ead604671158.png)


Perhaps I'll adapt that to scikit-fem as an example. Or perhaps I'll try the same thing on the insulated wire (exx 17, 26), heating the circle _r_ = _a_ rather than the disk _r_ ≤ _a_.

**Comment by gdmcbain** [comment]
- [ ] [`define_boundary`](https://github.com/kinnala/scikit-fem/blob/f116b1ac001ba83023a37665b97079f0633607e0/skfem/mesh/mesh.py#L405-L420)
- [ ] [`get_dofs`](https://github.com/kinnala/scikit-fem/blob/f116b1ac001ba83023a37665b97079f0633607e0/skfem/assembly/basis/basis.py#L195-L228)
- [ ] [`boundary_dofs`](https://github.com/kinnala/scikit-fem/blob/f116b1ac001ba83023a37665b97079f0633607e0/skfem/assembly/basis/basis.py#L170-L193)
- [ ] [`refine`](https://github.com/kinnala/scikit-fem/blob/f116b1ac001ba83023a37665b97079f0633607e0/skfem/mesh/mesh.py#L111) (with `arg=None` for uniform refinement)
  - [ ] `MeshTri`
  - [ ] `MeshQuad`

**Comment by gdmcbain** [comment]
Pausing on this to resolve #321.

**Comment by gdmcbain** [comment]
A proposal to resolve #321 was made in #338, following which #337 was withdrawn, so I'll copy some comments from there, equally applicable to any attempt to resolve the present issue:

@kinnala [2020-02-18](https://github.com/kinnala/scikit-fem/pull/337#issuecomment-587395394):

> So this causes m.boundaries to have interface facets also?

> I don't oppose this, but I have to check that it makes sense with respect to the current implementation of Basis.boundary_dofs.

> Also, currently Mesh.define_boundary won't allow defining interfaces, so we might want to add a keyword argument boundaries_only which has default value True and gets passed over to self.facets_satisfying.

and

> Just checked that MeshTri._uniform_refine, MeshQuad._uniform_refine should properly preserve interfaces. I think other mesh types don't support these yet. It might work with MeshLine if we're lucky since the order of indexing is preserved, we should modify the test test_mesh.RefinePreserveSubsets accordingly.

**Comment by gdmcbain** [comment]
I see: one would henceforth have to be more careful with `Mesh.define_boundary` that `test` didn't inadvertantly capture internal facets.  I'll make `boundaries_only` by default.

**Comment by gdmcbain** [comment]
While attempting to craft a test-case for this kind of internal boundary for #680, I found that this facility seems to have been lost in 

https://github.com/kinnala/scikit-fem/blob/0855dae117728588f269d968c8da4dbe06446d1b/skfem/mesh/mesh.py#L164-L165

which replaces the deprecated `define_boundary`.  I'll open a new issue.
