### ISSUE TITLE
nonzero natural conditions in 1-D

### ISSUE THREAD

**Issue by gdmcbain** [kinnala/scikit-fem#34]
I can't figure out how to impose nonzero natural conditions on a one-dimensional problem.  

Essential conditions are easy, same as in higher dimensions.

Consider u'' = 0 with u(0) = 0 and u'(1) = 1 so that the exact solution is u = x.

I can solve this as trivially two-dimensional problem (∇v, ∇u) = [v, n . ∇u]|(x=1) = [v, 1]|(x=1):

```python
m = MeshQuad.init_tensor(*(np.linspace(0., 1.),)*2)
e = ElementQuad1()
ib = InteriorBasis(m, e)
fb = FacetBasis(m, e)


@linear_form
def boundary_flux(v, dv, w):
    return v * (w.x[0] == 1.)


n = m.p.shape[-1]
L = asm(laplace, ib)
b = asm(boundary_flux, fb)
u, D = ib.find_dofs(lambda x, y: x == 0.)
I = ib.dofnum.complement_dofs(D)  # noqa E741
u = np.zeros_like(b)
u[I] = solve(*condense(L, b, I=I)) # noqa E741
```

but trying the same thing with the minimal modifications to drop the dimension from two to one
```python
m = MeshLine(np.linspace(0., 1.))
e = ElementLineP1()
```
fails at `FacetBasis` with
> NotImplementedError: The given mesh type is not supported!

I think that this is merely the proximate cause, raised by `get_quadrature`, but on inspection `MeshLine` appears incomplete, lacking attributes `facets`, `t2f`, `f2t`.

**Comment by gdmcbain** [comment]
Filling in the quadrature rule for `refdom is "point"` in 904da9b on branch neumann1d with
```python
    elif refdom is "point": # 0
        return np.zeros((1, 1)), np.ones(1)
```
the next hurdle hit is
> AttributeError: 'MeshLine' object has no attribute 'f2t'

**Comment by kinnala** [comment]
I sort of saw these challenges when I reimplemented the 1D support but forgot to do anything about it. Let us try to find a fix so that the implementation is as similar as in higher dimensions.

**Comment by gdmcbain** [comment]
Indeed this works and gets me going again on what I was really working on—coupled domains, but more on that later, all going well (or otherwise).  

Thank you!

Meanwhile a couple of thoughts:
* If the mesh is not generated but read, e.g. in a format like MEDIT or  Gmsh's MSH, it will often contain auxiliary sets of boundary elements, e.g. points, edges, or triangles for one-, two-, and three- dimensional simplicial meshes, respectively.   These are partially used in ex13.py, though only as collections of nodes for essential boundary conditions, not as elements proper for natural conditions.  Maybe sometimes it would be more convenient to have the facets in hand than to have to search for them?  I haven't thought through how this fits in to scikit-fem.
* For an impressive compendium of quadrature rules, see https://github.com/nschloe/quadpy.

**Comment by gdmcbain** [comment]
Thinking a bit more about `get_quadrature("point", …)`, given above as
```python
    elif refdom is "point": # 0
return np.zeros((1, 1)), np.ones(1)
```
and the ideal of
> a fix so that the implementation is as similar as in higher dimensions

If "point" is considered as a 0-simplex, and the canonical *n*-simplex as the convex hull of `np.eye(n, n+1, 1)`, the corners are (columnwise):
```
>>> (lambda n: np.eye(n, n+1, 1))(3)
array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])
>>> (lambda n: np.eye(n, n+1, 1))(2)
array([[0., 1., 0.],
       [0., 0., 1.]])
>>> (lambda n: np.eye(n, n+1, 1))(1)
array([[0., 1.]])
>>> (lambda n: np.eye(n, n+1, 1))(0)
array([], shape=(0, 1), dtype=float64)
```
 
Similarly, if "point" is considered as a zero-dimensional hypercube:
```
>>> np.array(list(product([-1, 1], repeat=3))).T
array([[-1, -1, -1, -1,  1,  1,  1,  1],
       [-1, -1,  1,  1, -1, -1,  1,  1],
       [-1,  1, -1,  1, -1,  1, -1,  1]])
>>> np.array(list(product([-1, 1], repeat=2))).T
array([[-1, -1,  1,  1],
       [-1,  1, -1,  1]])
>>> np.array(list(product([-1, 1], repeat=1))).T
array([[-1,  1]])
>>> np.array(list(product([-1, 1], repeat=0))).T
array([], shape=(0, 1), dtype=float64)
```

Looked at this way, the "0" given in the comment is actually the embedding of the zero-dimensional point in one dimension.  The "N.A." in the docstring is better.  I also note that the docstring states that the shape of the first value returned is number-of-dimensions × number-of-quadrature-points; again `(0, 1)` for "point".

**Comment by kinnala** [comment]
Closing this after adding some 1D tests.
