### ISSUE TITLE
vedo, formerly known as vtkplotter

### ISSUE THREAD

**Issue by gdmcbain** [kinnala/scikit-fem#361]
As noted in #44, matplotlib distorts three-dimensional views uncontrollably.  Some very nice plots were added to #357 using vtkplotter.  It might be a worthwhile addition to `skfem.visuals` #286.  (I haven't looked at the licence or portability.)

**Comment by kinnala** [comment]
License seems to be MIT. I don't oppose this, the plots look great. I'll try to get it working on my Python setup and try it out.

**Comment by gdmcbain** [comment]
A quick experiment went well.  

On a laptop running Microsoft Windows 10 
```shell
pip install vtkplotter
```
Then after having run `ex32.py` from #342, run
```python
from vtkplotter import Plotter

vp = Plotter()
vp.load('ex32.vtk')
vp.show()
```

This pops up a 'Visualization Toolkit Win32OpenGL' showing a green triangulated ellipsoid which can be rotated, translated, and zoomed with the mouse.  
* Hit 'h' in this window to display help back in the terminal.  
* Hit '4' to cycle through scalars to colour by; here twice for pressure.
* Hit 's' to save screenshot.png.

![screenshot](https://user-images.githubusercontent.com/1588947/79286565-5d4ac780-7f04-11ea-87f4-82d4b27b2a99.png)

This does nicely show the _p_ ~_xy_ pattern expected from creeping convection in a horizontally heated ellipsoid.

I assume this could be scripted, once I read the docs.

**Comment by gdmcbain** [comment]
To generate a PNG rather than a window, 
```python
from vtkplotter import Plotter, screenshot

vp = Plotter(offscreen=True)
...
screenshot('ex32.png')
```
See marcomusy/vtkplotter#55.

That saves the PNG without throwing up a window; however, it doesn't colour by pressure.  The answer to that might be in marcomusy/vtkplotter#131.

**Comment by gdmcbain** [comment]
Here we go:
```python
from vtkplotter import Plotter, screenshot

Plotter(offscreen=True).load("ex32.vtk").pointColors("pressure").show()
screenshot("ex32.png")
```

**Comment by gdmcbain** [comment]
I'd deferred this as it wasn't working on my Ubuntu 19.10 desktop (something about nvidia nouveau); as mentioned the previous work had been done under Microsoft Windows 10.

Yesterday I updated the desktop to Ubuntu 20.04 LTS and it's working fine.  Here's a recipe.
* conda 4.8.3 # from Miniconda3-latest-Linux-x86_64.sh
* `python=3.7` in a `conda create` # gives Python 3.7.7
* `conda install vtk`
* `pip install vtkplotter`

**Comment by kinnala** [comment]
I've been encountering issues trying to run this in a docker container, I'm only developing inside containers nowadays.

I think I have to next try it out in a Ubuntu 20.04 virtual machine.
