### ISSUE TITLE
Making docs more lightweight

### ISSUE THREAD

**Issue by kinnala** [kinnala/scikit-fem#363]
Some points:

- I'm not happy with how the docs are currently recompiled manually and uploaded to a different repository. I'd prefer to use a single repository instead.

- I also like the minimalistic style of e.g. meshio (and many others) where everything necessary is in a single markdown README file rendered by GitHub. We probably cannot go that far due to the complexity of scikit-fem, but I'd still prefer minimalism.

- I have started to also dislike Sphinx (for examples and tutorials) which has always felt a bit clumsy, not being very portable and requiring too much effort to maintain.

My proposition:

- Let's remove the examples from Sphinx doc and go back to the more relaxed "one file with docstring comments" per example; supposed to be read from Github directly and links from README.md (e.g. via the web view https://github.com/kinnala/scikit-fem/blob/master/docs/examples/ex02.py). These can be run in the test suite as it is currently done.

- For step-by-step tutorials, I'll recreate them as Jupyter Notebooks which are also nicely rendered by Github (e.g. https://github.com/bokeh/bokeh-notebooks/blob/master/tutorial/06%20-%20Linking%20and%20Interactions.ipynb) OR as simple markdown files. Whichever is more straightforward to integrate to the test suite.

- Keep the Sphinx documentation for the purpose of evolving it into a top class API documentation.

**Comment by gdmcbain** [comment]
If the top README.md gets too long (and maybe slow to load because of too many embedded images? I don't know) there's no barrier to adding more Markdown pages linked to from there. No need to worry about that for now though. 

I do like the idea of keeping the documentation closer to the source and so more synchronized, yes.

**Comment by gdmcbain** [comment]
One thing that would be missed from Sphinx RsT is LaTeX, at least at first, but then it occurs to me that having to do without LaTeX might actually be a good thing, a continuous and immediate motivation for bettering the API. The new-style forms are a good step here; with those, one needs LaTeX less: `grad(u)` is nearly as good as &nabla; _u_.
