### ISSUE TITLE
Incorrect edges returned by `Mesh3D.boundary_edges`

### ISSUE THREAD

**Issue by gdmcbain** [kinnala/scikit-fem#370]
I've been working on applying the block-diagonally preconditioned MINRES+AMG Stokes solver of #342 & ex32 to other MeshTet geometries and found some odd errors.  It seems to have nothing to do with the operators but something to do with `.find_dofs` when there are several Gmsh elementary entities in a single Gmsh `Physical Surface`.  The situation here is three Physical Surfaces: inlet, outlet, and wall, with uniform positive pressure applied at the inlet, zero pressure at the outlet, and zero velocity on the wall.  Typically the inlet and outlet are single elementary surfaces and the walls include everything else.  Example: a cube with inlet and outlet on an opposing pair of faces and the other four being walls.

I generate a tetrahedral mesh with marked boundaries in Gmsh, marking the boundaries in two different ways: first with all four walls combined, second with a separate Physical Surface for each.
```
SetFactory("OpenCASCADE");

Box(1) = {0, 0, 0, 1, 1, 1};

Physical Volume("fluid", 13) = {1};

Physical Surface("inlet") = {1};
Physical Surface("outlet") = {2};

Physical Surface("wall") = {3, 4, 5, 6};

Physical Surface("wall3") = {3};
Physical Surface("wall4") = {4};
Physical Surface("wall5") = {5};
Physical Surface("wall6") = {6};
```

I load this with 
```
import numpy as np
import skfem

basis = skfem.InteriorBasis(skfem.MeshTet.load("duct.msh"), skfem.ElementTetP2())

walls = {"separate": np.concatenate([b.all() for k, b in basis.find_dofs().items()
                                     if k.startswith("wall") and k[len("wall") :]]),
         "combined": np.concatenate([b.all() for k, b in basis.find_dofs().items()
                                     if k.endswith("wall")])}
```

Now I was thinking that `walls["separate"]` and `walls["combined"]` would be equal arrays of degrees of freedom on the walls but apparently not.

```python
walls["diff"] = np.setdiff1d(walls["combined"], walls["separate"])
print('In "separate" but not "combined"',  np.setdiff1d(walls["separate"], walls["combined"]))  # empty
print('In "combined" but not "separate"', walls["diff"])  # several
print('In "combined", not "separate", and not edge', np.setdiff1d(walls["diff"], basis.edge_dofs))  # empty
```

The "combined" approach has more degrees of freedom on the walls, with the extra ones all being in `basis.edge_dofs`.  (I haven't located them more precisely yet.)  The result is typically a singular matrix.  The "separated" approach seems to lead to a correct matrix

I haven't ascertained whether the discrepancy is in Gmsh, meshio, or `skfem.MeshTet.load` (or in my understanding of `basis.find_dofs`).

**Comment by kinnala** [comment]
Can you upload the mesh so I can test it?

**Comment by kinnala** [comment]
As you mention edges, it could be related to https://github.com/kinnala/scikit-fem/issues/83

**Comment by gdmcbain** [comment]
Here's the GEO, MSH, and the Python skfem script: [duct.zip](https://github.com/kinnala/scikit-fem/files/4620268/duct.zip)

**Comment by kinnala** [comment]
Got
```
In "separate" but not "combined" []
In "combined" but not "separate" [2419 2420 2428 2442 2454 2455 2462 2463 2475 2476 2702 2764 2765 2766
 2775 2776 2777 2781 2782 2792 2793 2817 2818 2821 2833 2834 2840 2842
 2844 2845 2849 2850 2861 2868 2869 2870 2894 2895 2901 2902 2908 2925
 2926 2927 2938 3066 3067 3070 3154 3186 3207 3208 3209 3254 3255 3256
 3261 3295 3296 3303 3304 3306 3308]
In "combined", not "separate", and not edge []
```
Tried to locate where is DOF 2419:
```

>>> np.nonzero(basis.edge_dofs == 2419)
np.nonzero(basis.edge_dofs == 2419)
(array([0]), array([1533]))
>>> basis.edge_dofs[:, 1533]
basis.edge_dofs[:, 1533]
array([2419])
>>> m.edges[:, 1533]
m.edges[:, 1533]
array([270, 432])
>>> m.p[:, 270]
m.p[:, 270]
array([0.49201093, 0.        , 0.09993278])
>>> m.p[:, 432]
m.p[:, 432]
array([0.50363245, 0.09947986, 0.        ])
>>> 1533 in m.boundary_edges()
1533 in m.boundary_edges()
True
```
Seems to indeed be on the boundary.

**Comment by kinnala** [comment]
I find these coordinates
```
array([0.49201093, 0.        , 0.09993278])
array([0.50363245, 0.09947986, 0.        ])
```
a bit confusing.

**Comment by kinnala** [comment]
Aha, apparently I have defined a boundary edge to be something which has both nodes on the boundary and not all points:
```python
    def boundary_edges(self) -> ndarray:
        """Return an array of boundary edge indices."""
        return np.nonzero(np.isin(self.edges,
                                  self.boundary_nodes()).all(axis=0))[0]
```
I have to see if this affects `find_dofs`.

**Comment by kinnala** [comment]
It does (in `Basis._get_dofs`):
```python
            edge_ix = np.intersect1d(
                m.boundary_edges(),
                edge_candidates[subset_ix]
            )
```

**Comment by kinnala** [comment]
So there is definitely a bug in `Mesh3D.boundary_edges` and possibly a bug also in `Basis._get_dofs`.

**Comment by kinnala** [comment]
Note: This will affect only 3D and elements that have edge DOFs.

**Comment by kinnala** [comment]
We are able to reliably find the facets on the boundary of the domain. The boundary edges should be deduced based on these boundary facets instead of the current (now obviously faulty) approach.

**Comment by kinnala** [comment]
I'll do something else now but I consider this relatively high priority and hope to fix it asap and release 1.0.1.

**Comment by gdmcbain** [comment]
Thank you for kicking off the investigation.  The explanation is plausible but troubling.  It sounds as though the extra degrees of freedom in the "combined" case are midpoints of edges that have their two termini on different planes of the boundary but midpoint in the interior, but when the Stokes operator was assembled and condensed it was the "combined" case that worked while the "separate" case that was singular.  I'll boil down a minimal script showing this.

The idea of using facets does make sense.

**Comment by gdmcbain** [comment]
Here's the Stokes script.  [stokes.txt](https://github.com/kinnala/scikit-fem/files/4632105/stokes.txt)

The element is changed from `ElementTetP2` to Taylor&ndash;Hood (`ElementVectorH1(ElementTetP2())` and `ElementTetP1`) with the walls applying to the velocity part.  The same kind of pattern is observed with "combined" being a strict superset of "separate" with the difference all being "edge_dofs".  (With ndim=3 times as many dofs now.)

The result of trying to solve the two cases is:
```
Trying to solve combined case.
C:\Users\gmcbain\AppData\Local\Continuum\anaconda3\envs\scikit-fem\lib\site-packages\scipy\sparse\linalg\dsolve\linsolve.py:193: MatrixRankWarning: Matrix is exactly singular
  warn("Matrix is exactly singular", MatrixRankWarning)
Conductance: nan
Trying to solve separate case.
Conductance: 0.035134620538645724
```
The exact answer is the Boussinesq _k_ factor for the square: _k_ = 0.03514, according to Dryden, H. L., F. P. Murnaghan, & H. Bateman 1956 _Hydrodynamics,_, p. 197, so the "separate" case looks good.

**Comment by kinnala** [comment]
You might want to check that there are no tets that have all nodes on the
boundary. Here is my related SE question:
https://scicomp.stackexchange.com/questions/23250/usefulness-of-elements-with-mesh-dependent-stability

And btw the accepted answer incorrectly states that this is also the case
in 2D: it is not.

**Comment by gdmcbain** [comment]
Wow, I'm 'slightly shocked' too!  Scary stuff!

A visual check in the Gmsh GUI shows all eight corners of the cube being shared by at least three distinct tetrahedra (maybe more that aren't visible from the outside).  I assume that in the cube it's only the eight corners that are in danger?  The SE question has the additional necessary condition that three of the four facets are also on the boundary.  It looks as though all along the twelve edges of the cube there are tetrahedra with two facets, five edges, and all four vertices on the boundary. (Although only four of these twelve edges would be all "wall" in my inlet&ndash;outlet b.v.p.; the other eight would be border of the inlet or outlet.)

/Do you think that I should be putting more effort into alternatives to Taylor&ndash;Hood?  I see that `ElementTriMini` were added in February #329 but don't have an example yet.

**Comment by gdmcbain** [comment]
The additional dofs in the "combined" Physical Surface are indeed spurious:

```python
basis.doflocs[:, walls['diff']]
```
shows their coordinates and none are either 0 or 1.

I haven't really worked out what it means to try to impose zero velocity on these internal degrees of freedom.  Ah: I remember now that before I was solving directly, I was using the block diagonally AMG preconditioned MINRES and was seeing anomalous pressures along the edges of the cube that belonged to two walls.  I guess what was happening there is that the pressure was undetermined at those vertices because they were surrounded by immobilized fluid.  I'll see if I can regenerate a figure.

**Comment by gdmcbain** [comment]
I haven't got that figure yet, but I did find one case matching the SE disaster.

```python
mesh = skfem.MeshTet.init_tensor(*[np.linspace(0, 1, 4)]*3)
```
![corner](https://user-images.githubusercontent.com/1588947/82017862-6d9ebf80-96c7-11ea-8c97-d64eda6ec7fc.png)

**Comment by gdmcbain** [comment]
Actually that mesh turned out O. K., presumably as none of the eight corners are all wall, they're all one-third inlet or outlet.

If also the parts of the wall are defined separately
```python
mesh.define_boundary("inlet", lambda x: x[0] == 0.)
mesh.define_boundary("outlet", lambda x: x[0] == 1.)
mesh.define_boundary("floor", lambda x: x[1] == 0.)
mesh.define_boundary("ceiling", lambda x: x[1] == 1.)
mesh.define_boundary("front", lambda x: x[2] == 0.)
mesh.define_boundary("back", lambda x: x[2] == 1.)
```
all is well.

![pressure](https://user-images.githubusercontent.com/1588947/82019515-b73cd980-96ca-11ea-8101-e3fa7be527f5.png)

**Comment by gdmcbain** [comment]
> /Do you think that I should be putting more effort into alternatives to Taylor–Hood? I see that ElementTriMini were added in February #329 but don't have an example yet.

The use of MINI is tangential here (it avoids the bug, but the bug should be fixed anyway), but I have tried it out on ex18.  At the level of the script, it's a very simple matter of replacing `ElementTriP2` with `ElementTriMini`: https://github.com/gdmcbain/scikit-fem/commit/92a39d56a6b484ad7c06ece92cba7b02d8af68cd.  It's almost too trivial to add as an example?
