### ISSUE TITLE
ElementTetMini

### ISSUE THREAD

**Issue by gdmcbain** [kinnala/scikit-fem#371]
ElementTetMini should avoid #370 on `MeshTet`, for example for Stokes problems.

`ElementTriMini` was added in #329.  It looks as though `ElementTetMini` should be a straightforward generalization.  I did also initially think that about `ElementHex2` #327 for which it wasn't the case; care has to be taken with the sequence of the additional degrees there, but for a MINI there is only one additional degree of freedom, the interior dof.

**Comment by gdmcbain** [comment]
I've just noticed that the introduction of the MINI element in
*  Arnold, D. N., Brezzi, F. & Fortin, M. (1984). A Stable Finite Element for the Stokes Equations. _Calcolo,_ 21, 337--344. doi: 10.1007/bf02576171 

and its treatment in

*  Braess, D. (2001). _Finite Elements._ Cambridge University Press, &sect;3.7

are both only two-dimensional, for triangular elements.

**Comment by gdmcbain** [comment]
Neither the triangular nor tetrahedral MINI element seem to appear in the [Periodic Table of the Finite Elements](http://femtable.org).

**Comment by kinnala** [comment]
I think the proof should be equivalent for the stability on triangles and
tetrahedra. Trying it out should be quick though.

I mean,

(div v, p) = -(v, grad p) = 0

and picking v to be the elementwise bubble, you get p = const. in each
element.

Thus, if p is the difference of two solutions, they are the same up to a
constant.

**Comment by gdmcbain** [comment]
There is a _d_-dimensional treatment of &lsquo;The ℙ<sub>1</sub>-bubble/ℙ<sub>1</sub> finite element&rsquo; in &sect;4.2.4 of
*  Ern, A., Guermond, J.-L. (2004). _Theory and Practice of Finite Elements._ New York: Springer

**Comment by gdmcbain** [comment]
How is the coeffiicient 27 in the interior_dof of ElementTriMini arrived at?  I assume the element will work regardless of what value is chosen, but that there's a sensible convention out there.

**Comment by kinnala** [comment]
I think it was simply normalized so that the value is one at the element midpoint. But actually it doesn't matter because this basis doesn't form a partition of unity.

**Comment by gdmcbain** [comment]
Ah, O. K.; even though `doflocs[-1] == [np.nan] * dim`, that seems reasonable.

I calculate 256 for the tet.
