### ISSUE TITLE
extend ElementH2 to 1D and 3D

### ISSUE THREAD

**Issue by kinnala** [kinnala/scikit-fem#39]
This should be quite easily done. I cannot currently figure any use case for 3D but at least in 1D you could create Hermite elements this way.

- [x] cubic Hermite 1d
- [x] BFS in 2D
- [ ] BFS in 3D for Cahn-Hilliard

**Comment by gdmcbain** [comment]
A possible three-dimensional use case: the [Cahn–Hilliard equation](https://en.wikipedia.org/wiki/Cahn%E2%80%93Hilliard_equation) is fourth-order in space.  Most of finite element discretizations introduce the laplacian of the concentration as an auxiliary variable so as to convert it to a system of second-order equations, but

* Stogner, R. H., & G. F. Carey. (n.d.) [Cahn–Hilliard phase decomposition and directed pattern assembly](https://users.ices.utexas.edu/~roystgnr/usnccm9.pdf).  9th US National Congress on Computational Mechanics

used:
* Clough–Tocher macroelement triangles
*  Bogner–Fox–Schmidt squares, analogous Hermite cubes

**Comment by kinnala** [comment]
$C^1$ element for 3D can be, in princple, now implemented using the machinery, but I wonder if it will be in practice too intensive. Also, because I'm not familiar with the respective applications, I'll leave it as future work.
