### ISSUE TITLE
Better support for high-order meshes

### ISSUE THREAD

**Issue by kinnala** [kinnala/scikit-fem#399]
This is just random ideas and possible future directions regarding high-order meshes. We have `ex31.py` for quadratic meshes but it's a bit convoluted because you go back and forth between `InteriorBasis` and `Mesh`.

I was reading https://mfem.org/mesh-format-v1.x/ and experimented with similar ideas in scikit-fem. I created a new module with classes `Topology`, `Dofnum` (extracted from `InteriorBasis._build_dofnum`) and `Geometry`.

Then you describe the traditional triangular mesh as follows:

```python
>>> from skfem import *
>>> from topology import *
>>> m = MeshTri()
>>> t = m.t
>>> p = m.p
>>> topo = Topology(t)
>>> dofnum = Dofnum(topo, ElementTriP1())
>>> geom = Geometry(p, dofnum)
>>> geom.p
array([[0., 1., 0., 1.],
       [0., 0., 1., 1.]])
>>> geom.t
array([[0, 1],
       [1, 2],
       [2, 3]])
```
This `Geometry` is approximately API compatible with traditional `skfem.Mesh` so you can build a `MappingIsoparametric` and, using that, an `InteriorBasis`:
```python
>>> mapping = MappingIsoparametric(geom, ElementTriP1())
>>> basis = InteriorBasis(m, ElementTriP2(), mapping)
```
Eventually I'd abstract out the mapping step so that `geom` is directly compatible with `InteriorBasis` constructor and returns the correct mapping via `geom.mapping()`.

Anyhow, now a quadratic mesh would be described simply as follows:
```python
>>> dofnum = Dofnum(topo, ElementTriP2())
>>> geom = Geometry(array([[0. , 1. , 0. , 1. , 0.5, 0. , 0.5, 1. , 0.5],
...        [0. , 0. , 1. , 1. , 0. , 0.5, 0.5, 0.5, 1. ]]), dofnum)
>>> mapping = MappingIsoparametric(geom, ElementTriP2())
>>> basis = InteriorBasis(m, ElementTriP2(), mapping)
```

Pretty cool? Obviously all this should be invisible to the user but I wonder if this warrants a rewrite of `skfem.mesh` so that we can easily define `MeshTri2` or something to refer to the quadratic mesh.

**Comment by kinnala** [comment]
I think I'll start working on this during the summer break. Some goals:
- [ ] Extract `InteriorBasis._build_dofnum` into a separate module (`class Dofnum`)
- [ ] Be able to define `MeshTri1` (same as `MeshTri`) using a combination of `Geometry`, `Topology`, `Element` and `Dofnum`
- [ ] Assemble `skfem.models.poisson.laplace` and some boundary forms equivalently with `MeshTri` and `MeshTri1`
- [ ] Be able to define `MeshTri2` and load a quadratic mesh, e.g., from gmsh.
- [ ] Convergence tests for quadratic meshes
- [ ] Be able to visualize high-order meshes

**Comment by kinnala** [comment]
Now in the branch we can do
```python
from skfem import *
from skfem.mesh.topology import *
from skfem.mesh.geometry import *
from skfem.assembly.basis.dofnum import *
from skfem.models.poisson import *
m = MeshTri()
topo = Topology(m.t)
dofnum = Dofnum(topo, ElementTriP1())
geom = Geometry(m.p, dofnum)
basis = InteriorBasis(geom, ElementTriP2())
```
Then
```python
>>> laplace.assemble(basis) - laplace.assemble(InteriorBasis(m, ElementTriP2()))
<9x9 sparse matrix of type '<class 'numpy.float64'>'
        with 0 stored elements in Compressed Sparse Row format>
```

**Comment by kinnala** [comment]
Definition of a quadratic mesh could now look something like this:
```python
class MeshTri2(Geometry):
    def __init__(self, p, t):
        super(MeshTri2, self).__init__(p, Dofnum(Topology(t), ElementTriP2()))
```
But I'll do some meditation before rushing to do it so I can figure out if we can easily generalize it further. I'd like to also support, e.g., surface meshes and NURBS meshes in the long term.

**Comment by kinnala** [comment]
I'll also check out what is the performance loss of defining `MeshTri` in this way:
```python
class MeshTri(Geometry):
    def __init__(self, p, t):
        super(MeshTri, self).__init__(p, Dofnum(Topology(t), ElementTriP1()))
```
If there is no performance loss, then this has the potential of simplifying `skfem.mesh` quite a bit.

**Comment by kinnala** [comment]
![image](https://user-images.githubusercontent.com/973268/83883209-d9ff6280-a74b-11ea-98f2-d1ed682b36c0.png)

Here is a fancy wobbly mesh.

**Comment by kinnala** [comment]
```
MeshTri1 as above, assembling the Laplacian with 262 144 elements and ElementTriP2:
1.26 s ± 14.8 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
classical MeshTri: 
1.68 s ± 371 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
```
As `MeshTri1` is still a bit less featureful than `MeshTri`, it's not conclusive, but seems that we have a chance of replacing the old meshes completely. This has a chance of reducing the amount of LOC significantly and simplifying the codebase.

**Comment by kinnala** [comment]
![image](https://user-images.githubusercontent.com/973268/83942408-d88d7300-a7fb-11ea-8866-6b7b6a42e8cd.png)

Quadratic quad mesh working as expected:
```python
class MeshQuad2(Geometry):
    def __init__(self, p, t):
        super(MeshQuad2, self).__init__(p, Dofnum(Topology(t), ElementQuad2()))   
```

**Comment by gdmcbain** [comment]
> I was reading https://mfem.org/mesh-format-v1.x/

I took a look at this.  I'm familiar with the idea of the mesh being the product of a geometry and a topology, but I was interested that in MFEM the order is reversed; that is, I had always thought of the geometry being specified absolutely (coordinates of points, usually and in scikit-fem and meshio, but also conceptually higher dimensional manifolds like curves or surfaces, specified parametrically or as level-sets, or howsoever, like the circular interface [discussed](https://github.com/kinnala/scikit-fem/pull/305#issuecomment-573312435) in #305) and then the topology specified as being supported by those geometrical entities.  In MFEM [Geometry](https://mfem.org/mesh-format-v1.x/#geometry), 

> The geometry of the mesh, i.e. the actual position of mesh elements in physical space is described by specifying the mesh nodes as a general finite element (vector) function.

I guess that this means that these &lsquo;mesh nodes&rsquo; needn't necessarily be geometric points but depending on the finite element space chosen any kind of degree of freedom as in Ciarlet's triplet definition of a finite element (_K_, _P_, _&Sigma;_).  I haven't thought through what that flexibility might enable but it does sound appealing.

**Comment by kinnala** [comment]
Just did some serious progress on this in #493 

![Figure_1](https://user-images.githubusercontent.com/973268/95666154-b3b95b80-0b5f-11eb-8def-eb4e1c2ab99b.png)

Loading a quadratic mesh from Gmsh using meshio and solving the Laplace equation.

**Comment by kinnala** [comment]
Decided to merge the preliminary work in #493 to get it started.

**Comment by kinnala** [comment]
Closing this shortly and opening new ones that are more detailed.
