### ISSUE TITLE
examples relying on pygmsh broken with Gmsh 4 now using format MSH4

### ISSUE THREAD

**Issue by gdmcbain** [kinnala/scikit-fem#40]
The two examples, ex12 and ex13, using pygmsh.generate_mesh are broken.  In each case the call raises 
> AssertionError: Need mesh format 2

from `meshio.gmsh_io._read_header`.

I think this might be the result of upgrading to Gmsh 4.  The MSH files are binary but the first two lines are
```
$MeshFormat
4 1 8
```

The 4 is what is asserted to be 2 by meshio, so I think this is a [https://github.com/nschloe/meshio](meshio) issue.  I'll report and try to fix it there.

**Comment by gdmcbain** [comment]
As reported under #41, following some work on nschloe/meshio#280, the error raised is now a `UnicodeDecodeError` rather than an `AssertionError`.

**Comment by gdmcbain** [comment]
As a result of work upstream on MSH4 nschloe/meshio#280 and binary MSH4 nschloe/meshio#284, this is half fixed.  Example ex12 now runs again; however, ex13 still fails though with a new, third,error:
> `KeyError: 'gmsh:physical'`

This has been raised upstream in nschloe/pygmsh#209 and nschloe/meshio#280.

**Comment by kinnala** [comment]
I suppose it does not matter. I checked out the contents of the object outputted by meshio.read yesterday. It seems that the contents are really mesh format specific. For example, MSH2 format output for tetrahedral mesh stores only the facet indexing. So a wrapper is needed to populate Submesh.edges. Already P2 elements for tet's have DOFs on edges so this is required.

**Comment by gdmcbain** [comment]
Facet indexing?  The [Gmsh MSH2 format](http://gmsh.info/doc/texinfo/gmsh.html#MSH-file-format-version-2) stores all elements in terms of nodes, `node-number-list` in:
> elm-number elm-type number-of-tags < tag > … node-number-list

which was all that was need for the `t` attribute of `skfem.Mesh`.  I thought that was passed on fairly faithfully from MSH by `meshio.read`?  

Not edges, no, but for `elm-number` 11
>     10-node second order tetrahedron (4 nodes associated with the vertices and 6 with the edges)

I thought it would have 10 entries in `node-number-list`; `meshio.msh_io._read_cells` seems to know about `elm-number` 11 which it calls `"tetra10"`.

**Comment by gdmcbain** [comment]
It would be a shame to have the facility only for linear elements.  Perhaps there will always be an issue for exotic elements which few if any mesh formats will know about; I guess these require some subsequent processing. But P2 etc shouldn't be in that category.

Now I believe that `meshio.read` for MSH2 (or direct use of `pygmsh.generate_msh` pre Gmsh 4) will return `cells` as a dictionary with keys 'tetra', 'triangle', 'line', &c., containing all the elements that are part of physical entities. The corresponding physical tags should be in `cell_data`.

Is the concern that the triangles, e.g., need to be linked to the two or one tetrahedra of which they are facets?

**Comment by kinnala** [comment]
You are correct. Tetrahedra and facet triangles must be linked via MeshTet.f2t and MeshTet.t2f.

This is definitely something that can be worked out though, but it requires some meditation.

**Comment by gdmcbain** [comment]
It seems that reading physical tags from MSH4 #41 is stalled upstream in nschloe/meshio#289.  

A makeshift that works with current pygmsh and meshio master for ex13 is to add
```
extra_gmsh_arguments=['-format', 'msh2']
```
to the call to `pygmsh.generate_mesh`.

I expect nschloe/pygmsh#213 to go through shortly though and that will enable another route for meshing consisting of simple elements (least order lines, triangle, tetrahedra, quadrilaterals, and hexahedra): `mesh_file_type="mesh"`, though that will also necessitate ditching the Gmsh `$PhysicalNames` `"ground"` and `"positive"` which the intermediate MEDIT mesh format doesn't store.  The boundaries would then be accessed by `int` tags.
