### ISSUE TITLE
wedge cells and elements

### ISSUE THREAD

**Issue by gdmcbain** [kinnala/scikit-fem#411]
Would it be worth adding wedge cells and elements? I recently received a mesh of these (too big to attach here, but I think a simple one could be constructed by extruding a triangular mesh in the third dimension).

Four isoparametric wedge elements with 6, 15, 9, and 12 nodes, respectively, are listed in

* Kardestuncer, H. (ed.) (1988). *Finite Element Handbook*. New York: McGraw-Hill, p. 2.130

**Comment by gdmcbain** [comment]
A difficulty: the facets of a wedge aren't all of the same topological type, there are three quadrilaterals and two triangles.  (I don't know the name for the subclass of polyhedra whose facets are the same kind of polygon, like tetrahedra and hexahedra, or for its complement.)  This complicates the `Mesh.facets` attribute; it can't be simple a rectangular array.  (Unless padded with a sentinel value like the &minus;1 in  `Mesh.f2t` for facets on the boundary?)

**Comment by gdmcbain** [comment]
Ern & Guermond (2004, &sect;1.2.5) refer to wedge elements as &lsquo;prismatic Lagrange finite elements&rsquo; and (table 1.3) depict ℙℝ<sub><i>k</i></sub> for _k_ = 1, 2, and 3.

* Ern, A., Guermond, J.-L. (2004). _Theory and Practice of Finite Elements_. Springer, &sect;1.2.5 &lsquo;Prismatic Lagrange finite elements&rsquo;

**Comment by gdmcbain** [comment]
Zienkiewicz & Taylor (2000, &sect;8.13) call them &lsquo;triangular prism elements&rsquo; and draw the 6, 15, and 26-node &lsquo;serendipity&rsquo; elements (figure. 8.23).

*  Zienkiewicz, O. C., Taylor, R. L. (2000). _The Finite Element Method. I: The Basis_. Butterworth-Heinemann.

**Comment by gdmcbain** [comment]
There's some discussion of &lsquo;vtkWedge&rsquo; and Wedge6 in nschloe/meshio#863.

**Comment by kinnala** [comment]
I've been thinking about this every now and then and still a proper solution escapes me. If only `CellBasis` assembly is needed for nodal elements then I think this can be implemented by hacking `Mesh.facets`, essentially disabling it.

**Comment by gdmcbain** [comment]
Hmm...Would the boundary of a mesh of homogeneous wedges or pyramids be something like a mixed mesh #412 ?  Could it be handled with something like a MultiBasis #728 ?

**Comment by kinnala** [comment]
I think we could technically implement a separate `FacetMeshTri` and `FacetMeshQuad` for which `CellBasis` gives an integral over the boundary. Regarding wedge elements, I'm making some progress in #740.
