### ISSUE TITLE
mixed meshes

### ISSUE THREAD

**Issue by gdmcbain** [kinnala/scikit-fem#412]
I wonder what are good ways to treat mixed meshes; e.g. a combination of triangles and quadrilaterals. I recently received one with wedges #411 and tetrahedra, but I would envisage treating the tri&ndash;quad case first. One of these arose by accident in one of the examples when Gmsh failed to combine all the triangles into quadrilaterals. #288 

I wonder whether this could be done with the library as is, using multiple meshes with the same  points, a bit like subdomains (but not literal `Mesh.subdomains`); a `meshio.Mesh` can support blocks of cells of different types on the one array of points.

**Comment by gdmcbain** [comment]
Actually a hurdle might be that currently a Mesh can't have unattached points.

**Comment by kinnala** [comment]
I was thinking this while working on #400 but didn't yet do anything about it. I think the correct way to do it is to create multiple `Mesh`-like entities that share the indices of the corresponding nodes. Then the rest of the machinery from `InteriorBasis` to `BilinearForm` should detect that there are multiple meshes and then ultimately try to combine them into a single matrix. But it requires some major changes, I could keep this in mind when continuing from #400 .

**Comment by gdmcbain** [comment]
Yes, I fear that doing this properly could require major changes. But plunging boldly ahead, I've hackily redone the Poisson problem of ex01 with 68 of the 256 quadrilaterals split into 2 &times; 68 = 136 triangles.  I only used `ElementQuad1` and `ElementTriP1` and had to hack the `InteriorBasis.N`, but it looks O. K.:
```python
import numpy as np

import skfem
from skfem.models.poisson import laplace, unit_load

import meshio

mesh = skfem.MeshQuad()
mesh.refine(4)

mask = np.random.default_rng(0).random(mesh.t.shape[1]) < .8

tmesh = skfem.MeshTri(mesh.p,
                      np.hstack([mesh.t.T[~mask].T[[0, 1, 3]],
                                 mesh.t.T[~mask].T[1:]]),
                      validate=False)
qmesh = skfem.MeshQuad(mesh.p, mesh.t[:, mask], validate=False)

basis = {'triangle': skfem.InteriorBasis(tmesh, skfem.ElementTriP1()),
         'quad': skfem.InteriorBasis(qmesh, skfem.ElementQuad1())}
basis['triangle'].N = basis['quad'].N = mesh.p.shape[1]  # !!! 

A = sum(skfem.asm(laplace, b) for b in basis.values())
b = sum(skfem.asm(unit_load, b) for b in basis.values())
u = skfem.solve(*skfem.condense(A, b, I=mesh.interior_nodes()))

mmesh = meshio.Mesh(
    np.hstack([mesh.p.T, np.zeros((mesh.p.shape[1], 1))]),
    [("triangle", tmesh.t.T),
     ("quad", qmesh.t.T)],
    {"deflexion": u})

meshio.write('triquad.vtk', mmesh, binary=False)
```

**Comment by gdmcbain** [comment]
![triquad](https://user-images.githubusercontent.com/1588947/86083143-cfcb4c80-badc-11ea-9c7c-8f9f8cf2f91b.png)

**Comment by kinnala** [comment]
Cool! This is useful. Gives an idea what should be worked on. Apparently
not too many changes are needed to support the lowest order elements.

**Comment by gdmcbain** [comment]
` ` `python
A = sum(skfem.asm(laplace, b) for b in basis.values())
b = sum(skfem.asm(unit_load, b) for b in basis.values())
` ` `

The assemblies inside the sums could be performed in parallel #450.

**Comment by kinnala** [comment]
I was wondering something like this:
```python
m = MeshHybrid.load('meshwithtrianglesandquads.msh')
mtri, mquad = m  # unpacks to standard MeshTri and MeshQuad with the indexing modified
basis = InteriorBasis(m, (ElementTriP1(), ElementQuad1()))
# after this everything works as expected
```
Can we uniquely determine the order in the element tuple? E.g., mesh type with less vertices / element comes first or will there be an issue in 3D that has more complicated hybrid meshes?

**Comment by gdmcbain** [comment]
I think if the mesh is read by meshio the cell-types will already be identified. In meshio 4, the cells are a list of pairs of cell type string and.a connectivity array.

**Comment by gdmcbain** [comment]
Oh you mean the type returned by MeshHybrid.load. Should it just be a list like the list in meshio.Mesh.cells?

**Comment by kinnala** [comment]
I'm not sure what `meshio.Mesh.cells` is like. I'd prefer to not change how `Mesh` works internally but somehow transparently create and assemble multiple `Mesh` objects like in your example.

**Comment by gdmcbain** [comment]
I see, yes, in

https://github.com/kinnala/scikit-fem/blob/5ff0fd9e282e97c6a57d57d65a1156985c696a19/skfem/io/meshio.py#L37

we read the derived attribute meshio.Mesh.cells_dict rather than the primitive meshio.Mesh.cells. In that case, what about MeshHybrid returning a dict like the cells_dict, with the keys being the cell-types. 

The meshio.Mesh.cells is sort of more general in that it can contain multiple items with the same cell-type. I'm not sure that that would ever be used though as there is no way to attach any metadata to the items of the cells list. (!)

**Comment by kinnala** [comment]
Here is some code I've been fooling around with:
```python
import dask.bag as db
import numpy as np 

from skfem import *
from skfem.models import laplace

meshi = MeshQuad() 
meshi = meshi.refined(4) 
 
mask = np.random.default_rng(0).random(meshi.t.shape[1]) < .8 

mesh1 = MeshTri(meshi.p, 
                np.hstack([meshi.t.T[~mask].T[[0, 1, 3]], 
                           meshi.t.T[~mask].T[1:]]))
mesh2 = MeshQuad(meshi.p, meshi.t[:, mask])

params = [
    (mesh1, ElementTriP1()),
    (mesh2, ElementQuad1()),
]

m = MeshQuad1.init_tensor(*[np.linspace(0, 1, 1001)]*2)

def multimesh(mesh, elem, N):

    return [
        (mesh, elem, None, None, ix)
        for ix in np.array_split(np.arange(mesh.nelements, dtype=np.int64), N)
    ]

def multiasm(form, basistype, params, scheduler='threading'):

    bag = db.from_sequence(params)
    c = bag.map(lambda p: form.coo_data(basistype(*p))).sum()
    out = c.compute(scheduler=scheduler)
    return out.tocsr()
```
In [1]: %time A1 = multiasm(laplace, Basis, multimesh(m, ElementQuad2(), 2))                              
CPU times: user 33.4 s, sys: 6.07 s, total: 39.4 s
Wall time: 21.6 s

In [2]: %time A2 = asm(laplace, Basis(m, ElementQuad2()))                                                 
CPU times: user 20.7 s, sys: 14 s, total: 34.7 s
Wall time: 34.8 s

In [3]: A3 = multiasm(laplace, Basis, params)        

In [4]: A3                                           
Out[4]: 
<289x289 sparse matrix of type '<class 'numpy.float64'>'
        with 2129 stored elements in Compressed Sparse Row format>
```
This works on top of #692 with no changes.

**Comment by kinnala** [comment]
Yesterday there was a nice difference between parallel and nonparallel assembly but now it's gone. As if the efficiency depends on the position of the sun.

**Comment by kinnala** [comment]
Here is my work from today:
```python
In [1]: %time basis = MultiBasis(splitmesh(m, 4), ElementQuad1(), parallel=True)                          
/home/tom/src/scikit-fem/skfem/mesh/mesh.py:388: UserWarning: Transforming over 1000 elements to C_CONTIGUOUS.
  warn("Transforming over 1000 elements to C_CONTIGUOUS.")
CPU times: user 4.75 s, sys: 645 ms, total: 5.4 s
Wall time: 1.6 s

In [2]: %time A2 = multiasm(laplace, basis, parallel=True)                                                
CPU times: user 3.99 s, sys: 315 ms, total: 4.31 s
Wall time: 1.54 s

In [3]: %time basis = Basis(m, ElementQuad1())       
CPU times: user 1.94 s, sys: 447 ms, total: 2.39 s
Wall time: 2.39 s

In [4]: %time A1 = asm(laplace, basis)               
CPU times: user 1.72 s, sys: 291 ms, total: 2.01 s
Wall time: 2.01 s
```
Still no changes to #692:
```python
import dask.bag as db
import numpy as np 

from skfem import *
from skfem.models import laplace

meshi = MeshQuad() 
meshi = meshi.refined(4) 
 
mask = np.random.default_rng(0).random(meshi.t.shape[1]) < .8 

mesh1 = MeshTri(meshi.p, 
                np.hstack([meshi.t.T[~mask].T[[0, 1, 3]], 
                           meshi.t.T[~mask].T[1:]]))
mesh2 = MeshQuad(meshi.p, meshi.t[:, mask])

meshes = (mesh1, mesh2)
elems = (ElementTriP1(), ElementQuad1())

m = MeshQuad1.init_tensor(*[np.linspace(0, 1, 1001)]*2)


def splitmesh(mesh, nsplits):

    from dataclasses import replace

    return [
        replace(
            mesh,
            doflocs=mesh.p,
            t=mesh.t[:, ix],
        ) for ix in np.array_split(np.arange(mesh.nelements, dtype=np.int64),
                                   nsplits)
    ]


def MultiBasis(mesh,
               elem,
               mapping=None,
               intorder=None,
               elements=None,
               quadrature=None,
               parallel=False):

    from itertools import cycle

    # TODO not supported yet
    assert mapping is None
    assert intorder is None
    assert elements is None
    assert quadrature is None

    if isinstance(mesh, list):
        mesh = tuple(mesh)

    if isinstance(elem, list):
        elem = tuple(elem)

    if not isinstance(mesh, tuple):
        mesh = (mesh,)

    if not isinstance(elem, tuple):
        elem = (elem,)

    params = [arg for arg in zip(mesh, cycle(elem))]

    if parallel:
        import dask.bag as db
        bag = db.from_sequence(params)
        c = bag.map(lambda p: Basis(*p))
        return c.compute(scheduler='threading')

    return [Basis(*p) for p in params]


def multiasm(form, bases, parallel=False):

    if parallel:
        import dask.bag as db
        bag = db.from_sequence(bases)
        c = bag.map(lambda basis: form.coo_data(basis)).sum()
        out = c.compute(scheduler='threading')
        return out.tocsr()

    return sum(map(lambda basis: form.coo_data(basis), bases)).tocsr()

```

**Comment by kinnala** [comment]
Oh yeah, the most important part:
```
In [5]: (A1-A2).mean()                               
Out[5]: -1.1942566695985367e-26
```

**Comment by kinnala** [comment]
In #738 this is now a bit easier:
```python
import numpy as np 
 
from skfem import *
from skfem.models.poisson import laplace, unit_load 
 
import meshio 
 
mesh = MeshQuad() 
mesh = mesh.refined(4) 
 
mask = np.random.default_rng(0).random(mesh.t.shape[1]) < .8 
 
tmesh = MeshTri(mesh.p, 
                np.hstack([mesh.t.T[~mask].T[[0, 1, 3]], 
                           mesh.t.T[~mask].T[1:]])) 
qmesh = MeshQuad(mesh.p, mesh.t[:, mask]) 
 
basis = [
    Basis(tmesh, ElementTriP1()), 
    Basis(qmesh, ElementQuad1()),
]
 
A = asm(laplace, basis)
b = asm(unit_load, basis)
u = solve(*skfem.condense(A, b, I=mesh.interior_nodes())) 
 
mmesh = meshio.Mesh( 
    np.hstack([mesh.p.T, np.zeros((mesh.p.shape[1], 1))]), 
    [("triangle", tmesh.t.T), 
     ("quad", qmesh.t.T)], 
    {"deflexion": u}) 
 
meshio.write('triquad.vtk', mmesh, binary=False) 
```
Not quite a "native support", but it's getting closer.

**Comment by kinnala** [comment]
Plotting "kind of" works out of the box :rofl: 
![Kuvakaappaus - 2021-09-14 12-08-16](https://user-images.githubusercontent.com/973268/133229707-ad86d697-69b5-4b1f-a2ea-a51d022b5fa6.png)

**Comment by kinnala** [comment]
Combining meshes with linear elements is working:
```python
from skfem import *
from skfem.models import laplace, unit_load

m = (MeshTri().refined()
     + (MeshQuad().translated((1, 0)).refined()
        + MeshTri().translated((2, 0)).refined()))
e = [ElementTriP1(), ElementQuad1(), ElementTriP1()]
basis = [Basis(*me) for me in zip(m, e)]

A = asm(laplace, basis)
f = asm(unit_load, basis)

y = solve(*condense(A, f, I=m[0].nodes_satisfying(lambda x: ((x[0] > 0)
                                                             * (x[0] < 3)
                                                             * (x[1] > 0)
                                                             * (x[1] < 1)))))


from skfem.visuals.matplotlib import plot, draw, show
ax = plot(basis[0], y, Nrefs=4)
draw(basis[0], ax=ax)
plot(basis[1], y, ax=ax, Nrefs=4)
draw(basis[1], ax=ax)
plot(basis[2], y, ax=ax, Nrefs=4)
draw(basis[2], ax=ax)
show()
```
![Figure_1](https://user-images.githubusercontent.com/973268/133254792-49dcb29f-6989-4e55-aad7-aa2608b11794.png)

**Comment by kinnala** [comment]
Changed + to @ because this combination operation must be done in correct order.

**Comment by kinnala** [comment]
However, higher order elements require hacking the Dofs object which I'm not going to do now. However, in the long term I suppose it would be useful to separate Dofs from Basis as much as possible.
