### ISSUE TITLE
MeshLine.element_finder

### ISSUE THREAD

**Issue by gdmcbain** [kinnala/scikit-fem#417]
It's impossible to construct an `InteriorBasis.interpolator` when `.mesh` is `MeshLine` since the latter has no `.element_finder`.

Hardly urgent since the nodal values are usually good enough.  What I was actually trying to do just now was plot the `ElementLineHermite` shape functions by interpolating onto a fine `numpy.linspace` of points from a `MeshLine` of a single cell with a cardinal vector for the degrees of freedom; I'd used `.lbasis` for `ElementLineP1` and `ElementLineP2` but `ElementLineHermite` doesn't have an `.lbasis`.  There might be another way to do that but anyway I figure the `.element_finder` might come in handy for something else later.

**Comment by gdmcbain** [comment]
So far only `MeshTri` and `MeshQuad` have an `.element_finder`; those for `Mesh3D` might come in handy too later.

**Comment by gdmcbain** [comment]
Partly looking ahead to `MeshTet` (and also hoping for an implementation independent of dimension), I looked at [scipy.spatial.Delaunay.find_simplex](https://docs.scipy.org/doc/scipy/reference/generated/scipy.spatial.Delaunay.find_simplex.html#scipy.spatial.Delaunay.find_simplex) but `Delaunay` doesn' t work in one dimension; `Delaunay(skfem.MeshLine().p.T)` raises `*** ValueError: Need at least 2-D data`.

**Comment by kinnala** [comment]
I think we could make an algorithm based on octrees that finds the correct element efficiently in 3D.

**Comment by gdmcbain** [comment]
I have some particle-tracking applications for which that would be nice although thus far I really only have the flow-fields in two dimensions and they're already covered.

I wonder whether the octree would generalize to *n* dimensions. (Specifically here including *n*=1.)

**Comment by kinnala** [comment]
Yes, I think 1, 2, and 3 dimensions should work. The question is that whether it's worth the trouble to build a vectorized octree implementation ourselves or is there an implementation available somewhere in the ecosystem that we can use?

**Comment by gdmcbain** [comment]
Yes, I'd think that there ought to be one out there. I haven't found it yet but then I don't need it right away. It probably would be better to leave it to a heavily optimized and tested package if one were found as in some applications (mapping between meshes?) it would get hammered.
