### ISSUE TITLE
DOC: quantify performance

### ISSUE THREAD

**Issue by gdmcbain** [kinnala/scikit-fem#425]
> The performance claim in vague: “Despite being fully interpreted, the code has a reasonably good performance.”
> If the author could be more specific (quantifiable), it would help the reviewer in making a judgement.

 (From #422 .)

**Comment by gdmcbain** [comment]
A bit tricky this; there are so many external factors. But I suppose to give some idea, could one assemble and solve something like ex01 (Dirichlet Poisson) on a million (reasonable nontrivial round number?) triangles and a million tetrahedra? Profile with cProfile, separating into mesh, basis, and assembly; the actual solve is less important, I think, as it can be delegated to an external routine (AMGCL, PyAMG, PETSc,. ...), maybe quote anyway but certainly under a separate heading.

How.is one to characterize the hardware? Is there a standard Linux.command for that?

**Comment by gdmcbain** [comment]
Of course it could be handy to have some benchmark speed tests in hand for assessing future developments too.

**Comment by kinnala** [comment]
I agree with the original comment. Although I wasn't supposed to make a performance claim when I wrote the sentence, it obviously reads as one and it's not very clear what it means.

I'm thinking that we could measure the assembly time of (grad u, grad v) for different number of DOF's and compare it to two prototype implementations: naive Python implementation with for loops over elements (will be significantly slower) and C implementation with for loop over elements (will be slightly faster I think but hopefully not too much?).

I could look into this when I have the time. If it's not feasible then we simply remove the performance claim.

**Comment by kinnala** [comment]
A related comment from #426 :
> The authors claims that the assembly, while made in pure python, is "fast enough" ? This shall be made more explicit. Do the authors mean that the assembly takes a negligible time compared to the resolution of the resulting linear system ?

**Comment by kinnala** [comment]
I propose we create a simple and concice performance benchmark with these ideas and add it to README.
