### ISSUE TITLE
Add Dofs.get_element_dofs

### ISSUE THREAD

**Issue by kinnala** [kinnala/scikit-fem#427]
This was a feature request from @ahhuhtal . The use case would be to figure out what degrees-of-freedom correspond to a named subdomain.

**Comment by gdmcbain** [comment]
Like in the example of the insulated wire? 

https://github.com/kinnala/scikit-fem/blob/9c485745018a915ae683295a011f910228741352/docs/examples/ex26.py#L38

**Comment by kinnala** [comment]
Yeah, I see your point: why have a separate function if it can be done in one line?

Well, in principle, `get_element_dofs` could work also with function handles and so on. But the real reason for introducing `Dofs` objects was to have a single place for different methods that fetch DOF's. So maybe instead of making new multitype methods, we simply add multiple methods to `Dofs`? Such as
- `Dofs.element_dofs_byindex`
- `Dofs.element_dofs_byhandle`
- `Dofs.element_dofs_bytag`
and so on.
