### ISSUE TITLE
Add a gallery of examples

### ISSUE THREAD

**Issue by kinnala** [kinnala/scikit-fem#428]
From #426
> The authors claims that more than 30 examples illustrate the use of the library. I did not find any page that summarises those examples. It would be very useful for new users. I mean something similar to what the MFEM developers provide: https://mfem.org/examples/

Also related from https://github.com/kinnala/scikit-fem/pull/420#issuecomment-657289008
> I wonder whether more generally it might be good to have a gallery of figures from the suite of examples as an index into them, like https://matplotlib.org/gallery (this goes back to #31 #365 and I suppose further discussion should be taken up under the latter rather than here).

I propose we add this to Sphinx docs and also add a link to it in README to make it obvious.

**Comment by kinnala** [comment]
Or would Github Wiki work better than Sphinx? Maybe it allows storing the images more easily? I'll look into that.

**Comment by kinnala** [comment]
I did a test here how Github Wiki could look like: https://github.com/kinnala/scikit-fem/wiki/Examples

I'm not very convinced of it because both equations and images are a bit tedious. I'll look next into having something in the Sphinx doc.

**Comment by gdmcbain** [comment]
Hey, I didn't know about
```
<img src="https://render.githubusercontent.com/render/math?math=-\Delta u = 1">
```
Neat!

**Comment by gdmcbain** [comment]
I was going to say that https://mfem.org/examples is good, but then I saw https://mfem.org/gallery which is even better.  Very nice figures, very inspiring.  I think these will repay my closer study.

**Comment by thelfer** [comment]
> I was going to say that https://mfem.org/examples is good, but then I saw https://mfem.org/gallery which is even better. Very nice figures, very inspiring. I think these will repay my closer study.

@gdmcbain @kinnala  IMHO, both are interesting. The gallery allows users to see what can be done with the products, but the examples list give appropriate starting points for a specific topic (elasticity for instance).

**Comment by kinnala** [comment]
I'm currently working on something similar to https://mfem.org/examples, i.e. name + figure + short description + url to source code. It will be part of the Sphinx documentation.
