### ISSUE TITLE
Discuss nonlinear problems and nonuniform data in the paper

### ISSUE THREAD

**Issue by kinnala** [kinnala/scikit-fem#430]
From #426 

> The authors shall describe how the library could be used in non linear cases. In particular, the contact problem given in the first example is indeed non linear.

> Can non uniform coefficients be handled ? To make my question clearer, would I be able to treat:
> a linear elastic problem with a non uniform Young Modulus.
> a heat transfer equation with a non uniform heat source Those non uniform coefficients are dealt with in UFL using the notion of functions spaces. Is there anything equivalent in scikit-fem ?

Should we discuss these in the paper?

**Comment by gdmcbain** [comment]
Let's see.  These are all handled easily by scikit-fem as it stands, I believe.  I think the techniques are covered in the suite of examples.  Going back to #24 (2018-08-07), quite new to scikit-fem, I [wrote](https://github.com/kinnala/scikit-fem/pull/24#issue-206583284):

> It wasn't immediately clear to me how to write forms with variable coefficients so I wrote an example, solving the Legendre equation.

That became ex16 &lsquo;spatially varying coefficient&rsquo;.  It's a diffusion operator, but the same technique would apply to uneven Lamé coefficients in linear elasticity, nonuniform source terms.

That's for a coefficient that varies with position; for coefficients varying by subdomain, there's ex17, fufilling #89 &lsquo;piecewise-definition of coefficients on subdomains&rsquo; (2018-11).

Then there are coefficients that are functions of finite element functions, like the Young&ndash;Laplace equation ex10, the Bratu&ndash;Gelfand equation ex23, and the Navier&ndash;Stokes equation ex27.  I think that covers the kind of nonlinear cases asked about.

The Bratu&ndash;Gelfand equation is handled a bit differently; I'm not sure why.  I guess it's simpler so can be, but I think it could be handled in the same way as the others if that was of interest, to have only one way of doing things.

Apart from the Bratu&ndash;Gelfand example, the fundamental notion is `Basis.interpolate`.  The coefficient is defined as a finite element function with degrees of freedom in some `Basis` and then it's interpolated onto the quadrature points associated with that basis.  These quadrature points have to be the same as those used by the trial and test bases in the bilinear form (or just the test basis in the linear form), and for the bilinear form itself, but the three bases don't have to be the same.  Does that cover it?

**Comment by kinnala** [comment]
It seems to me that `u` is defined in `FunctionSpace(mesh, "Lagrange", 2)` and "projected" to `Q`:
```python
C = project((1.0 + self.u**2), self.Q)
```
Does it mean that `u` is interpolated at the quadrature points and that `FunctionSpace(mesh, "Q", 2)` simply presents functions evaluated at quadrature points, e.g., similar to a `DiscreteField`?

https://github.com/kinnala/scikit-fem/blob/master/skfem/element/discrete_field.py

**Comment by gdmcbain** [comment]
Yes, that's it, nothing new.
