### ISSUE TITLE
hosting papers

### ISSUE THREAD

**Issue by gdmcbain** [kinnala/scikit-fem#435]
While we're discussing documentation again #428 (though not related to the JOSS paper), I was wondering about a good way to host papers using scikit-fem, I'm just finishing off a paper on the Orr&ndash;Sommerfeld equation (primitive as in ex29 but also classical with ElementLineHermite).  I note that this work generated no new scikit-fem issues; everything just worked! :)

i mean hosting in a way that the actual results and figures in the paper could be regenerated for real by the reader; not necessarily interactively, but at least they could access the scripts, download and rerun them.  I imagine that examples like this could be informative for other users or domain-experts as they would generally go into more detail and be much more specialized than is reasonable in docs/examples.

One idea I had was to put the directory tree of the paper in a git branch of scikit-fem.  This would have the advantage that the branch would also contain the contemporaneous version of scikit-fem.  Maybe in a branch on a fork and then make a pull-request here, immediately closed (like #316, demonstrating SLEPc) so that it's visible but without any intention of merging.

Of course I can just host my paper wherever, but perhaps a growing uniform collection of these would be of interest to users.

I assume other FLOSS scientific computing packages already have various implementations of various solutions to this, but haven't seen any yet myself.

**Comment by ahojukka5** [comment]
A one potentially interesting approach would be to have Jupyter notebooks which can be launch in Binder, so basically you can repeat the example in your web browser. We have been demonstrating this in JuliaFEM and it seems to be working,

Check out the demo here: https://github.com/ahojukka5/juliafem-demo

In the background, Binder is creating a docker container which is then launched in a cloud. In principle, it's also possible to make a PowerPoint presentation from that.

**Comment by kinnala** [comment]
> A one potentially interesting approach would be to have Jupyter notebooks which can be launch in Binder, so basically you can repeat the example in your web browser. We have been demonstrating this in JuliaFEM and it seems to be working,
> 
> Check out the demo here: https://github.com/ahojukka5/juliafem-demo
> 
> In the background, Binder is creating a docker container which is then launched in a cloud. In principle, it's also possible to make a PowerPoint presentation from that.

I tried out this approach in a recent paper (under review) and I think it works pretty well.

The paper:
https://arxiv.org/abs/2007.00403

The numerical results:
https://github.com/kinnala/kirchhoff-nitsche-ex1
https://github.com/kinnala/kirchhoff-nitsche-ex2
https://github.com/kinnala/kirchhoff-nitsche-ex3

I'm also archiving these to Zenodo so I can get a citable DOI:
https://zenodo.org/record/3925365#.XxMDQHX7SV4
https://zenodo.org/record/3925367#.XxMDU3X7SV4
https://zenodo.org/record/3925375#.XxMDL3X7SV4

The above Zenodo entries are cited in the paper. Note also how the figures in the paper are generated in the CI run by Github Actions. I'm planning to make it more reproducible via containers after peer review.

**Comment by gdmcbain** [comment]
Thank you both.  Binder does has the advantage of making the examples available even to those that don't have Python installed; this was handy recently in #416.

I like the idiom as in the caption to figure 2:

> The source code for reproducing these results is available in [11].

I hope that catches on.

> I'm planning to make it more reproducible via containers after peer review.

Good idea. I look forward to seeing that and will most likely follow suit.

----

It doesn't look like any work on scikit-fem is required here so I'll close this for now.  Do feel free to jot thoughts or links here to other good ideas or new developments in reproducible publication.  Thanks again.
