### ISSUE TITLE
conforming Crouzeix–Raviart

### ISSUE THREAD

**Issue by gdmcbain** [kinnala/scikit-fem#437]
@bhaveshshrimali, from #436:

> I would like to implement the conforming Crouzeix&ndash;Raviart element as described in [4.13](http://archive.numdam.org/article/M2AN_1973__7_3_33_0.pdf) in the celebrated paper by Crouzeix and Raviart. Is this (i.e. defining the basis) the only step in the FE assembly pipeline that is needed for implementing new elements ?

**Comment by gdmcbain** [comment]
> Is this (i.e. defining the basis) the only step&hellip;?

On looking at `ElementTriRT0` for comparison, it might be necessary to define things analogous to `ElementHdiv.orient` and `.gbasis`.

**Comment by kinnala** [comment]
I'm not completely sure but I think you can define `lambda_1 = x`, `lambda_2 = y` and `lambda_3 = 1 - x - y` on the reference element, use the expressions in (4.13), and then simply use `ElementH1` with `nodal_dofs = 1`, `facet_dofs = 1`, `interior_dofs = 1`.

**Comment by kinnala** [comment]
Is this used for Stokes/incompressible elasticity? What is the corresponding basis for pressure?

**Comment by bhaveshshrimali** [comment]
> I'm not completely sure but I think you can define `lambda_1 = x`, `lambda_2 = y` and `lambda_3 = 1 - x - y` on the reference element, use the expressions in (4.13), and then simply use `ElementH1` with `nodal_dofs = 1`, `facet_dofs = 1`, `interior_dofs = 1`.

I will give it a try.

**Comment by bhaveshshrimali** [comment]
> Is this used for Stokes/incompressible elasticity? What is the corresponding basis for pressure?

Yes. The pressure approximation is the [discontinuous](http://pamies.cee.illinois.edu/Publications_files/JMPS2017b.pdf#page=30&zoom=100,0,0) with the dofs and basis functions as described in (125)

**Comment by kinnala** [comment]
@bhaveshshrimali were you able to get it to work?

**Comment by bhaveshshrimali** [comment]
Hi @kinnala ,
Not yet. Wrote down the basis functions for the 3D cases. Will have to write down for 2D and the corresponding ones for pressure. 
I have two deadlines till October 24. Will get back to asap after that. I will check it by reproducing ex36.

**Comment by YerbaPage** [comment]
> 
> 
> I'm not completely sure but I think you can define `lambda_1 = x`, `lambda_2 = y` and `lambda_3 = 1 - x - y` on the reference element, use the expressions in (4.13), and then simply use `ElementH1` with `nodal_dofs = 1`, `facet_dofs = 1`, `interior_dofs = 1`.

Hi! First thanks a lot for this useful package. It has helped me a lot!

I'm trying to use the nonconforming P1 element to solve Stokes equation with $(P_{1}^{CR}, P_{0})$. 

I tired to build it in this way 
```python
class ElementTriP1CR(ElementHdiv):

    nodal_dofs = 1
    dim = 2
    maxdeg = 1
    dofnames = ['u']
    doflocs = np.array([[0., 0.5],
                        [0.5, 0.],
                        [0.5, 0.5]])
    mesh_type = MeshTri

    def lbasis(self, X, i):
        x, y = X

        if i == 0:
            phi = 1. - 2. * x
            dphi = np.array([-2. + 0. * x, 0. * x])
        elif i == 1:
            phi = 1. - 2. * y
            dphi = np.array([ 0. * x, -2. + 0. * y])
        elif i == 2:
            phi = 2. * x + 2. * y - 1.
            dphi = np.array([2. + 0. * x, 2. + 0. * y])
        else:
            self._index_error()

        return phi, dphi
```
but it didn't work.

Would you please give me some ideas about what else I should define or change?

That would be very helpful to me, thanks!

**Comment by kinnala** [comment]
I'll try it later but at least nodal_dofs should be zero and facet_dofs =
1.

**Comment by kinnala** [comment]
You also need to use `ElementH1` superclass. Actually these names `ElementH1`, `ElementHdiv` and `ElementHcurl` are a bit confusing because the first one means that we use identity transformation when defining the global basis from the local basis. At some point I was planning to rename them but wasn't able to decide on a good naming.

**Comment by kinnala** [comment]
Decided to add this element to the library, see #492

**Comment by YerbaPage** [comment]
> You also need to use `ElementH1` superclass. Actually these names `ElementH1`, `ElementHdiv` and `ElementHcurl` are a bit confusing because the first one means that we use identity transformation when defining the global basis from the local basis. At some point I was planning to rename them but wasn't able to decide on a good naming.

It worked, thanks.

Would you please explain briefly what the other two names `ElementHdiv` and `ElementHcurl` means?

**Comment by kinnala** [comment]
> Would you please explain briefly what the other two names `ElementHdiv` and `ElementHcurl` means?

`ElementHdiv` and `ElementHcurl` use the so-called contravariant and covariant Piola transforms, respectively.

The idea is that whereas the identity transform of `ElementH1` preserves DOFs that are point evaluations, `ElementHdiv` and `ElementHcurl` preserve DOFs that correspond to normal and tangential derivatives. This is important when discretizing Sobolev spaces such as H(div) and H(curl).

**Comment by YerbaPage** [comment]
> 
> 
> > Would you please explain briefly what the other two names `ElementHdiv` and `ElementHcurl` means?
> 
> `ElementHdiv` and `ElementHcurl` use the so-called contravariant and covariant Piola transforms, respectively.
> 
> The idea is that whereas the identity transform of `ElementH1` preserves DOFs that are point evaluations, `ElementHdiv` and `ElementHcurl` preserve DOFs that correspond to normal and tangential derivatives. This is important when discretizing Sobolev spaces such as H(div) and H(curl).

I get it! Thanks!
