### ISSUE TITLE
pacopy goes GPL

### ISSUE THREAD

**Issue by gdmcbain** [kinnala/scikit-fem#451]
It looks like another outbreak of &lsquo;clarify the licensing of the examples&rsquo; #445 arose overnight; following pygmsh #446, pacopy went from [MIT](https://github.com/nschloe/pacopy/blob/2dd70b80ddc3cf8f1ef9328413f27e41f4016125/LICENSE) to GPL, under
* commit &lsquo;add setup.cfg&rsquo; https://github.com/nschloe/pacopy/commit/31369a497ea845e138ff30c53dcffa049b97c8f4#diff-9879d6db96fd29134fc802214163b95a 
* PR &rsquo;modernize&rsquo; nschloe/pacopy#16.

While we could just do as for pygmsh #446 and explicitly GPL exx 23 (Bratu&ndash;Gelfand, using `pacopy.euler_newton`) and 27 (steady Navier&ndash;Stokes, using `pacopy.natural`), I'm inclined to suggest a different path.

I assume that the relicensing is not retrospective, so we could pin to the last MIT version.  There has been [very little development](https://github.com/nschloe/pacopy/issues?q=is%3Aissue+is%3Aclosed) on pacopy since (my) addition of milestones in April 2019 in nschloe/pygmsh#5, which is essential to the practical application of `pacopy.natural` to nonlinear problems.

i had also recently already been thinking anyway of writing a new independent routines for natural parameter and false-transient continuation in the context of JFNK #442 #449 since I don't think `pacopy.natural` is compatible with JFNK, running the Newton iteration itself.  In simple cases like ex10, it's enough to use a simple `for`-loop in the natural parameter (amplitude of boundary deflexion in that case).  The adaptive natural parameter continuation of `pacopy.natural` in ex27 is nice though, so I'll probably copy that from the last MIT version.  Were I to write my own continuation routine, it would almost certaintly be an `Iterator`, avoiding the need for callbacks.

**Comment by kinnala** [comment]
Very abrupt indeed, but I actually think this could be due to meshzoo
dependency, which depends on pygmsh and so on. This again reminds how
careful you have to be.

**Comment by kinnala** [comment]
No, that's only in tests. I'm not sure what caused this.  Hopefully meshio
doesn't follow along.

**Comment by gdmcbain** [comment]
> No, that's only in tests. 

Yes, I was thinking that.  

And even so, in turn meshzoo doesn't depend on anything (not pygmsh), so why meshzoo? 

> I'm not sure what caused this.

No.

> Hopefully meshio doesn't follow along.

Indeed.

**Comment by kinnala** [comment]
Tangentially related: should be build a library of snippets that have only the relevant parts of interfacing to 3rd party libraries?

**Comment by kinnala** [comment]
> I assume that the relicensing is not retrospective, so we could pin to the last MIT version.

I think this also. But I asked the author personally by email whether he thinks this is the case (i.e. misinterpretation of a dependency licensing terms) or not. Let's see if he answers or not.

**Comment by gdmcbain** [comment]
> the last MIT version.

That's [0.1.2](https://pypi.org/project/pacopy/0.1.2); [0.1.3](https://pypi.org/project/pacopy/0.1.3/) is GPLv3+.
