### ISSUE TITLE
factor Mesh.load for files or constructed meshio.Meshes

### ISSUE THREAD

**Issue by gdmcbain** [kinnala/scikit-fem#46]
I started looking at the `skfem.Mesh.boundaries` attribute used in `test_mesh.Loading`.  Very nice!  This will make the top-level scripts much more readable.  

I wanted to improve `examples/ex14.py` in this way but its `skfem.MeshTri` lacked this attribute; an `skfem.Mesh` only gets `boundaries` if constructed by `classmethod Mesh.load` and that takes the name of a file whereas there's no accessible file containing the mesh in the example.  It uses `pygmsh.generate_mesh` which writes the mesh in a `tempfile.NamedTemporaryFile`.

So I could eschew `generate_mesh` in favour of writing `geom.get_code()` to a GEO file and then running Gmsh myself in a `subprocess` to generate the MSH file, but that's verbose and duplicates a lot of what's in `generate_mesh`.

Instead, what about factorizing `Mesh.load` so that everything after the definition of
```python
        meshdata = meshio.read(filename)
```
is delegated to another `classmethod`, say `from_meshio_mesh` and then either `load` calls that or the user if they have a `meshio.Mesh` (say by passing the values returned from `pygmsh.generate_mesh`) can call it directly.

I'll attempt an implementation.

**Comment by kinnala** [comment]
Yes, I don't object. There is still the one TODO in the edge loading that I haven't had time to fix but it doesn't matter.
