### ISSUE TITLE
pinning pacopy 0.1.2

### ISSUE THREAD

**Issue by gdmcbain** [kinnala/scikit-fem#463]
After pacopy went GPL #451, it was pinned at the last prior version 0.1.2 #452 

This seems to have blocked an unrelated new example on hyperelasticity #462 as the tests are now failing with `pip` not being able to find a version; in https://travis-ci.com/github/kinnala/scikit-fem/jobs/376714751 we read

> ERROR: Could not find a version that satisfies the requirement pacopy==0.1.2 (from versions: none)

> ERROR: No matching distribution found for pacopy==0.1.2

> The command "pip install meshio pacopy==0.1.2 pygmsh pyamg flake8" failed and exited with 1 during .

This did not occur during the merging of PRs  #452 #453 #457 #459 #461.

**Comment by gdmcbain** [comment]
https://github.com/kinnala/scikit-fem/pull/462/files does not involve pacopy (or meshio, pygmsh, pyamg, or flake8).

**Comment by gdmcbain** [comment]
I wondered whether this kind of failure might be due to another requirement requiring a different version of pacopy, but I don't think anything else depends on pacopy; meshio, pygmsh, pyamg, & flake8 don't.

**Comment by kinnala** [comment]
This is done, right?

**Comment by gdmcbain** [comment]
Yes.

I.had.been working towards replacing pacopy entirely as part of a switch to scipy.optimize.root #119 but I haven't  been able to get that to reproduce ex27 (steady incompressible Navier&ndasb;Stokes).
