### ISSUE TITLE
remove libsuitesparse?

### ISSUE THREAD

**Issue by gdmcbain** [kinnala/scikit-fem#464]
While looking into the failure to set up the test suite because pacopy 0.1.2 couldn't be found #463 , I noticed that the test suite installs libsuitesparse

https://github.com/kinnala/scikit-fem/blob/2f97ce292d892f7ffd7880c2dc2094029513d55f/.travis.yml#L11

Is this vestigial since `sksparse.cholmod` was removed from ex19 in #447 and replaced with scipy.sparse.linalg.splu #448?

**Comment by ahojukka5** [comment]
This is actually a good example of what happens when the testing is not isolated from the other packages. If writing tests to scikit-fem, it should only use the functionalities of scikit-fem. Otherwise, tests are going to break sooner or later, even without touching the code. Highly undesirable behavior in the mind of someone who has repeatedly corrected hundreds of tests. This is something that we have been doing and learning during JuliaFEM project.

**Comment by gdmcbain** [comment]
Interesting comment, thank you.

I'm not sure.  You write as though tests breaking is a bad thing, but aren't they the canaries in the coalmine?  Breaking tests only slows the acceptance of new code.  Breaking tests are to be preferred over breakages in the field, breakages in downstream packages, or errors in end-users' finite element analyses.

Also when tests break, here, it usually doesn't mean correcting the tests, it means correcting the code.  More often than not, with the tests in question here, that code is not scikit-fem code.   The tests in question (mostly `tests/test_examples.py`) are integration tests or system tests.  I think these serve a very important role beside the unit tests and validation tests in the other subdirectories of `tests`.  

Yes, tests are going to break sooner or later, even without touching the code, when some upstream package changes.  This has already happened more than once with meshio, but this is an important dependency not of scikit-fem's core but of an important subset of users and potential users of scikit-fem; meshio is relied upon for input and output of all but the simplest problems.  meshio has many competing demands on it and evolves in ways that are beyond our control, so it's helpful for us to know as soon as possible when a change in meshio breaks representatively complete finite element analyses using scikit-fem as finite element library.

We could pin old versions of dependencies, but that would mean missing out on upstream bug fixes and new features, both of which are frequent in meshio, in particular.  Would this introduce the problem that there would be a new task of periodically testing when the pin could be updated?

I can see a case for separating tests that isolate scikit-fem from other packages and integration and system tests, but were the latter removed, I think I'd have to set them up independently, and run them regularly myself.  This would have the big disadvantage that it would be removed from the continuous integration workflow, so a change could be inadvertantly introduced into scikit-fem that broke its interaction with one of the select dependencies exercised in the integration and system tests.  That doesn't sound convenient.

Those are my thoughts, but it sounds like you have more experience in this kind of thing.  Am I on the wrong track?  I haven't looked at JuliaFEM, so don't know how well it is integrated into or isolated from its ecosystem (does it handle its own geometry, meshing, input, output, solvers, preconditioners, graphics, logging, &c., &c.); scikit-fem was designed to focus on assembly and leave the auxiliaries to the flourishing ecosystem.
