### ISSUE TITLE
review MeshTet.init_tensor

### ISSUE THREAD

**Issue by gdmcbain** [kinnala/scikit-fem#473]
It appears that the regression in ex09 for build_pc_ilu #469 is due to the local re-implementation of `MeshTet.init_tensor` in https://github.com/kinnala/scikit-fem/commit/8d6446de63f1bcd6548483f195bc53d9c9575c23#diff-7d5249076e12208eb9bff97b642c77ff (2020-07-30).  On current master (and since that commit and release 2.0.0), the `solver_iter_pcg` with `build_pc_ilu` doesn't converge; with `MeshTet` imported from `meshzoo.cube` it does.

I suspect that fixing this fixes #469, though the reference value specified in `tests.test_examples.TestEx09` should be reconsidered too.

**Comment by kinnala** [comment]
I think the connectivity of the new implementation is different (not symmetric with respect to the center planes). But I cannot figure why this would cause nonconvergence. Must look into this in more detail.

**Comment by gdmcbain** [comment]
Right, yes.  I think I was incorrect to launch this issue about `MeshTet.init_tensor` as the cause of the regression in `build_pc_ilu` in ex09 #469; after all, `MeshTet.init_tensor` works fine with PyAMG and AMGCL and the direct solver.  And `build_pc_ilu` (presumably `spilu`) works fine with other meshes (refined `MeshTet()` and `meshzoo.cube`) so it's somehow the combination of `build_pc_ilu` and `MeshTet.init_tensor`.  I'm inclined to close this and resume the more general investigation in #469.

**Comment by gdmcbain** [comment]
I wonder if `solver_iter_pcg` (`scipy.sparse.linalg.cg`) is implicated in the combination of `spilu` and `MeshTet.init_tensor`.  Do other Krylov solvers diverge too?  Could `spilu` fail to preserve symmetry (selfadjointness)?  (I'm just guessing here.)

**Comment by kinnala** [comment]
I modified the parameter of the preconditioner and now it seems to converge.
