### ISSUE TITLE
Pointwise evaluation of a vector

### ISSUE THREAD

**Issue by bhaveshshrimali** [kinnala/scikit-fem#480]
Hi @kinnala ,

Is it possible to do pointwise evalulation of `InteriorBasis` on a set of input points for `ElementHex1` ?
I can see an `interpolator` method, but not sure of what it does. I am trying:
```python3
import numpy as np
from skfem import *
mesh  = MeshHex()
elem = ElementHex1()
velem = ElementVectorH1(elem)
basis = InteriorBasis(mesh, velem,  MappingIsoparametric(mesh, elem), intorder=1)
eval = basis.interpolator(np.random.random(basis.N))
```

but this raises: 

```
Traceback (most recent call last):
  File ".\generateStructuredMesh.py", line 110, in <module>
    eval = basis.interpolator(np.random.random(basis.N))
  File "C:\Users\bshri\AppData\Local\Programs\Python\Python37\lib\site-packages\skfem\assembly\basis\interior_basis.py", line 141, in interpolator
    finder = self.mesh.element_finder()
  File "C:\Users\bshri\AppData\Local\Programs\Python\Python37\lib\site-packages\skfem\mesh\mesh.py", line 342, in element_finder
    raise NotImplementedError("element_finder not implemented "
NotImplementedError: element_finder not implemented for the given Mesh type.
```

Is this something that you put there for future implementation? 

https://github.com/kinnala/scikit-fem/blob/884a427043577233584ea4257dea6f9c2f599d64/skfem/mesh/mesh.py#L339-L343

**Comment by gdmcbain** [comment]
That's right.  There was some discussion of this in July and in August in the context of another `Mesh` not having its `element_finder` implemented yet: `MeshLine.element_finder` #417.  I think that implementing `element_finder` for all subclasses of `Mesh` is an important goal.

**Comment by bhaveshshrimali** [comment]
Thanks @gdmcbain !! If required, I can close this and the discussion be continued in #417

**Comment by gdmcbain** [comment]
Well this one is about `MeshHex.element_finder` which might be a bit harder than `MeshLine.element_finder`, though discussion in #417 did hint that it might be possible to generalize octrees to provide a solution independent of dimension; I do find that kind of dimension-independent code appealing, but having any implementation is the priority.

**Comment by gdmcbain** [comment]
Another little thing that occurred to me between #417 and now is whether it might be better to reverse the order of the arguments in `InteriorBasis.interpolator`.  Currently it takes a solution vector and returns a function from points to values.  In the application to an unsteady solution on a fixed `InteriorBasis`, it's common to have some fixed &lsquo;probe&rsquo; points at which the evolution of the signal is recorded.  Similarly I suppose for parametric studies in which e.g. the Reynolds number is varied.

From the way `interpolator` is written, I don't think it really depends on having the solution vector first.

**Comment by kinnala** [comment]
I'm pretty busy with a grant proposal before Wednesday next week but after that I hope to spend some time on this.

**Comment by kinnala** [comment]
One idea we could try is to put `m.p.T` into https://docs.scipy.org/doc/scipy/reference/generated/scipy.spatial.KDTree.html and then query for, e.g., 10 closest points from `tree = KDTree(m.p.T)` via `tree.query([x, y, z], 10)`, find the corresponding elements from `m.t`, and check which contains `[x, y, z]`.

**Comment by kinnala** [comment]
Actually, I suggest that we directly put the midpoints of the elements into the KDTree to simplify a bit. Then what is remaining is answering to the local question: "Is `[x, y, z]` inside `i`'th element?".

**Comment by kinnala** [comment]
Here is example:
```python
from scipy.spatial import KDTree
from skfem import MeshTet
m = MeshTet()
m.refine(5)
tree = KDTree(np.mean(m.p[:, m.t], axis=1).T)  # midpoints of elements
ix = tree.query([0.1, 0.1, 0.1], 5)[1]  # find five candidate elements close to (0.1, 0.1, 0.1)
X = mapping.invF(np.array([[0.1], [0.1], [0.1]])[:, None], ix)  # find corresponding local points
inside = (X[0]>0)*(X[1]>0)*(X[2]>0)*(1-X[0]-X[1]-X[2]>0)  # find which of those are inside the reference element
```
Running in ipython gives
```
In [77]: inside                                                                                              
Out[77]: 
array([[ True],
       [False],
       [False],
       [False],
       [False]])
```

**Comment by kinnala** [comment]
An additional remark: inverse mapping of `MappingIsoparametric` will clip the results to the unit cube for robustness so the above approach might require some tuning.

**Comment by gdmcbain** [comment]
Very interesting.  Thank you!  

> This isn't bulletproof but should work for reasonable meshes.

I wonder whether this is related to a specific property of the mesh, like the Delaunay property (circumspheres of cells not containing stray vertices), but not that.  And are the centroids best, or the incentres?  Or one of the 39683 (!) other centres defined in the [*Encyclopedia of Triangle Centres*](https://faculty.evansville.edu/ck6/encyclopedia/ETC.html)?

**Comment by kinnala** [comment]
There is now a preliminary implementation for tets and 1D meshes available for testing in #487 .

**Comment by kinnala** [comment]
Continuing to track at #503

**Comment by kinnala** [comment]
`MeshHex.element_finder` will arrive to master after #556 is merged.
