### ISSUE TITLE
Indexing error in find_dofs

### ISSUE THREAD

**Issue by mjziebarth** [kinnala/scikit-fem#481]
Hi,

first off, great library: Indeed fills an important niche, thanks for creating!

While using it, being new to finite element methods, I have encountered an error that I am not sure how to fix (whether it's a wrong use on my end or a problem with the code). When trying to implement Dirichlet boundary conditions (following example 14) in a MeshTet, I am encountering a numpy indexing error.

My script condenses to the following:
```python
m = MeshTet3D(p=some_nodes, t=some_elements, boundaries=some_boundaries)
e = ElementTetP1()
basis = InteriorBasis(m, e)
surface_basis = FacetBasis(m, e, facets=m.boundaries["top"])
surface_dofs = surface_basis.find_dofs()['all'].all()
```
The `boundaries` dict contains, among others, an array of faces belonging to the top side. Things run smoothly up to the `surface_basis.find_dofs()` call, where the following error is raised:
```
~/.local/lib/python3.8/site-packages/skfem/mesh/mesh3d/mesh3d.py in boundary_edges(self)
     39                               facets]))
     40                    for itr in range(self.facets.shape[0])])).T, axis=1)
---> 41         return np.nonzero((self.edges.T[:, None] == boundary_edges)
     42                           .all(-1).any(-1))[0]
     43 
AttributeError: 'bool' object has no attribute 'all'
```
The error occurs because the shapes of `self.edges.T[:,None]`, `(180751, 1, 2)`, and `boundary_edges`, `(107076, 2)`, do not match for an elementwise comparison. From a quick skim of the code, I assume that some sort of element comparison is taking place in that function, but I am not sure about that (without some in depth study of the source). I thought to open this issue because maybe there is something fundamentally wrong in my code snipped above and I hope it's not too stupid, or otherwise it might be a bug.

Thanks in advance,
Malte

**Comment by kinnala** [comment]
I might have an idea what it is: can you try `basis.find_dofs` instead?

**Comment by mjziebarth** [comment]
Thanks for the quick reply!
I tried it out, unfortunately the same error appears.

I will try to dig deeper to find the root of this. Is there some way that I could validate that the objects are properly initialized?

**Comment by kinnala** [comment]
Can you run this with the Python debugger and print the call stack with `where`?

Something like `ipython test.py -m pdb` then in the resulting prompt press `c` and wait until the execution halts to the error. Then write `where` and paste the output here.

**Comment by kinnala** [comment]
A better option would be that you could share a mesh which causes this issue with a minimal working example but I'm not sure if you are able to do that.

**Comment by kinnala** [comment]
Additional remarks:
- if you want to find all boundary DOF's, you can also simply call `basis.find_dofs()` without parameters.
- which version are you using?

You can find the version as follows:
```
In [1]: from skfem import __version__
In [2]: __version__
Out[2]: '2.0.0'
```
Mention also if you are using the version from the source code repository directly.

**Comment by kinnala** [comment]
The following runs fine on the master branch:
```

from skfem import *
m = MeshTet()
m.define_boundary("top", lambda x: x[2] == 1.0)
e = ElementTetP1()
basis = InteriorBasis(m, e)
surface_basis = FacetBasis(m, e, facets=m.boundaries["top"])
surface_dofs = surface_basis.find_dofs()
```
Does it run on your computer?

**Comment by mjziebarth** [comment]
I am running the latest version (2.0.0) from PyPI. Your example also runs fine:
> The following runs fine when using the master branch:
> 
> ```python
> from skfem import *
> m = MeshTet()
> m.define_boundary("top", lambda x: x[2] == 1.0)
> e = ElementTetP1()
> basis = InteriorBasis(m, e)
> surface_basis = FacetBasis(m, e, facets=m.boundaries["top"])
> surface_dofs = surface_basis.find_dofs()
> ```
> 
> Does it run on your computer?

While building a smaller example to share here (which runs fine!), I think I might have found the root of the error:
An array of size (180751, 107076, 2) is just to large for my RAM (that would be about 36GB for a bool array and I'm working on a notebook with 8GB). Instead of raising a memory error, however, the comparison just silently fails and returns a single bool. Not something I would have expected, else I would have checked that earlier..

I will find a way to get along with that and at some point switch to a larger machine. Thanks for the quick help and feedback!

**Comment by kinnala** [comment]
That's actually a good point, I think we do not want to create such a large array because the memory runs out easily. I think there is room for optimization here. I'll open another issue.

**Comment by kinnala** [comment]
Since you are using linear elements, as a workaround you should be able to dig those DOF-numbers directly from the mesh structure. E.g., if you are assembling only scalar problems, just use the indices `boundary_dofs = m.boundary_nodes()`.

**Comment by kinnala** [comment]
Here are some pointers what you might want to do: https://scikit-fem.readthedocs.io/en/latest/bcs.html#indexing-of-the-degrees-of-freedom

**Comment by kinnala** [comment]
There is now a new version available with some optimizations to `boundary_edges`: https://pypi.org/project/scikit-fem/

**Comment by mjziebarth** [comment]
Thanks a lot for coming back so quickly!

Some feedback: I tested the new version, it roughly halves the required memory. Still a bit too large (19.3 GB) to
run on the notebook, but should run on the bigger machine.

In my particular case, I have already circumvented the problem following your advice about using the mesh structure. Thanks!

**Comment by kinnala** [comment]
Alright, seems that I need to look into it further. I hope it doesn't anymore stem from `boundary_edges` because I was able to reduce the search space significantly.

The issue is most likely related to some recent changes to `find_dofs` done in 2.0.0.

**Comment by kinnala** [comment]
Ok it's still there. What a tricky issue. I need to meditate a bit.

**Comment by kinnala** [comment]
Alright, now I managed to run this with 10 million tets and less than 11 gigs of memory. Hopefully it's enough for you, it kind of starts to touch the boundaries of this library.
