### ISSUE TITLE
scikit-fem is a available as a conda package

### ISSUE THREAD

**Issue by tlestang** [kinnala/scikit-fem#488]
Hi there,
This is not exactly an issue - I just wanted to chime in and say that a few months ago scikit-fem was made available as a conda package through conda-forge (https://anaconda.org/conda-forge/scikit-fem/files).

I'm working on [PyBaMM](https://github.com/pybamm-team/PyBaMM) - which uses scikit-fem - and we decided to make PyBaMM available as a conda package through conda-forge: part of the work was to also make scikit-fem available as a conda package.

This means Anaconda (and miniconda) users should be able to 
```
conda install -c conda-forge scikit-fem
```
The repo (conda-forge feedstock) is here: https://github.com/conda-forge/scikit-fem-feedstock and I am currently maintaining it.

**Comment by kinnala** [comment]
Thanks! I added a badge to the README.
