### ISSUE TITLE
how to compute the flux through a part of the boundary

### ISSUE THREAD

**Issue by gdmcbain** [kinnala/scikit-fem#49]
A common postprocessing operation is the computation of the flux through a part of the boundary which has had an isopotential boundary condition imposed.  I haven't quite worked out how to evaluate this.

I have in a branch of [examples/ex13.py](https://github.com/gdmcbain/scikit-fem/blob/flux/examples/ex13.py) (which is atop #47) computed the gradient of the potential using `derivative`, but haven't figured out how to then integrate the normal component of this over just a part of the boundary, say that corresponding to `mesh.boundaries['ground'].facets`.

Is there a facility for restricting a `linear_form` to a `Submesh`?

**Comment by kinnala** [comment]
Currently there is not, used tobe in the old Python 2.7 version, but assembly is very differentnow. 

This is a good idea. I see two possibilities:

1) Additional parameter to FacetBasis and InteriorBasis constructors. Then the resulting basis would be nonzero only on the Submesh.

2) Additional parameter to asm.

Currently I favor 1) but I'll think this through later today or this week.

**Comment by kinnala** [comment]
Submesh does not really contain enough information to perform the whole assembly. It is only a tuple of index arrays. I guess one could include a reference to the original object from which the Submesh is derived.

**Comment by kinnala** [comment]
One can now give `Submesh` to `FacetBasis` constructor via the keyword argument `submesh`.

The resulting `FacetBasis` is nonzero only on the submesh.

**Comment by gdmcbain** [comment]
Awesome!  Thank you.  I have extended ex13 to demonstrate this. #56
