### ISSUE TITLE
Testing convergence of P2 element

### ISSUE THREAD

**Issue by YerbaPage** [kinnala/scikit-fem#501]
Hi! Thanks again for this fantastic library and your help!

I was trying to solve a Poisson equation with the Dirichlet boundary condition u=0 and got results as follows:
- Using P1 element: L2 convergence was 2, H1 convergence was 1
- Using P2 element: L2 convergence was 1, H1 convergence was 0.5

The first result seems good but the second was strange. I guess I was right (maybe?) defining exact value of u and forms according the first result. 

I tested with $u=sin(\pi x)sin(\pi y)$ and the only change I made switching from P1 element to P2 was in `element = ElementTriP2()`. 

I'm not sure what else I should change. I studied the codes in `test_convergence.py` but still failed to find my problem when testing P2 element. 

Could you give me some advice?

Here is my code
```python
from skfem import *
import numpy as np
from skfem.utils import solver_iter_krylov
from skfem.helpers import d, dd, ddd, dot, ddot, grad, dddot, prod
from skfem.models.poisson import *
from skfem.assembly import BilinearForm, LinearForm
pi = np.pi
sin = np.sin
cos = np.cos
exp = np.exp

# exact value of u and du

def exact_u(x, y):
    return sin(pi * x) * sin(pi * y)

def dexact_u(x, y):
    dux = pi * cos(pi * x) * sin(pi * y)
    duy = pi * cos(pi * y) * sin(pi * x)
    return dux, duy

# errors

@Functional
def L2uError(w):
    x, y = w.x
    return (w.w - exact_u(x, y))**2


def get_DuError(basis, u):
    duh = basis.interpolate(u).grad
    x = basis.global_coordinates().value
    dx = basis.dx  # quadrature weights
    dux, duy = dexact_u(x[0], x[1])
    return np.sqrt(np.sum(((duh[0] - dux)**2 + (duh[1] - duy)**2) * dx))

# forms

@LinearForm
def f_load(v, w):
    pix = pi * w.x[0]
    piy = pi * w.x[1]
    return (2 * pi**2 * sin(pix) * sin(piy)) * v


@BilinearForm
def laplace(u, v, w):
    return dot(grad(u), grad(v))

# solving

m = MeshTri()

for i in range(1, 8):
    m.refine()
    element = ElementTriP2()
    basis = InteriorBasis(m, element, intorder=3)

    K1 = asm(laplace, basis)
    f1 = asm(f_load, basis)

    uh = solve(*condense(K1, f1, D=m.boundary_nodes()),
               solver=solver_iter_krylov(tol=1e-8))
    
    U = basis.interpolate(uh).value

    L2u = np.sqrt(L2uError.assemble(basis, w=U))
    Du = get_DuError(basis, uh)
    H1u = Du + L2u
    print('L2: ', L2u)
    print('H1: ', H1u)
``` 

and the result was:
> L2:  0.3701821308162362
H1:  1.8337156693985683
L2:  0.15740572307705145
H1:  1.2502164229785424
L2:  0.07479121383890937
H1:  0.8525347535661557
L2:  0.03703703290581105
H1:  0.5891783044781566
L2:  0.018522289815901757
H1:  0.40997857616261413
L2:  0.009274842111763961
H1:  0.28649644653428563
L2:  0.004642509304282054
H1:  0.20082649383661721

Thanks for your help!

**Comment by kinnala** [comment]
I didn't try it out, but I think the issue is in how you set the Dirichlet
boundary condition.

m.boundary_nodes() returns only mesh node indices. But P2 element has DOFs
on the edges so it's not enough to se value to zero at mesh nodes only. You
should use basis.get_dofs() instead to find the DOF indices for condense. I
hope it helps.

**Comment by YerbaPage** [comment]
> 
> I didn't try it out, but I think the issue is in how you set the Dirichlet boundary condition. m.boundary_nodes() returns only mesh node indices. But P2 element has DOFs on the edges so it's not enough to se value to zero at mesh nodes only. You should use basis.get_dofs() instead to find the DOF indices for condense. I hope it helps.

It's working now! Thanks!
