### ISSUE TITLE
Computing curl for ElementTriMorley

### ISSUE THREAD

**Issue by YerbaPage** [kinnala/scikit-fem#505]
Hi, It's me again! Thanks so much for this library and your help!

Recently I'm trying to assemble BilinearForm like (curl u, curl v) for Morley element. I tried to implement it this way:
``` python
m = MeshTri()
m.refine(5)

@BilinearForm
def zv_load(u, v, w):
    return dot(curl(u), curl(v))

element = ElementTriMorley()
basis = InteriorBasis(m, element)

K = asm(zv_load, basis)
```

But the following error is raised:
```
~\Anaconda3\lib\site-packages\skfem\helpers.py in curl(u)
     31     if u.curl is not None:
     32         return u.curl
---> 33     raise NotImplementedError
     34 
     35 

NotImplementedError: 
```

I'm wondering whether there are some problems in my codes or there are some other things that we could implement? Could you give me any hint of what I could do?

Thanks in advance!

**Comment by kinnala** [comment]
The helper "curl" is implemented currently only for H(curl)-conforming
elements. But since Morley is a two-dimensional element, what do you
exactly mean by "curl" in 2D?

**Comment by gdmcbain** [comment]
Maybe something like **rot** _&psi;_ = **curl** (_&psi;_ **k**)?  That gives the two-dimensional velocity from its stream-function, as in

https://github.com/kinnala/scikit-fem/blob/4ba1e06a01856e825d8d2f9cdfcd5742c5376f66/docs/examples/ex20.py#L73-L74

**Comment by gdmcbain** [comment]
&hellip;or, as in #506,

https://github.com/kinnala/scikit-fem/blob/dece91061fec31e0dbe13d69bf549e17cc195e0b/skfem/models/general.py#L20-L23

https://github.com/kinnala/scikit-fem/blob/dece91061fec31e0dbe13d69bf549e17cc195e0b/docs/examples/ex20.py#L71-L75

**Comment by kinnala** [comment]
> Maybe something like **rot** _ψ_ = **curl** (_ψ_ **k**)? That gives the two-dimensional velocity from its stream-function, as in
> 
> https://github.com/kinnala/scikit-fem/blob/4ba1e06a01856e825d8d2f9cdfcd5742c5376f66/docs/examples/ex20.py#L73-L74

So basically extending https://github.com/kinnala/scikit-fem/blob/master/skfem/helpers.py#L31 by something like
```python
if u.grad is not None:
    rot_grad = np.zeros_like(u.grad)
    return np.array([rot_grad[1], -rot_grad[0]])
```
?

**Comment by kinnala** [comment]
I mean,
```python
if u.grad is not None:
    if u.grad.shape[0] == 2:
        rot_grad = np.zeros_like(u.grad)
        rot_grad[0] = u.grad[1]
        rot_grad[1] = -u.grad[0]
        return rot_grad
    elif u.grad.shape[0] == 3:
        # something else ...
```

**Comment by YerbaPage** [comment]
> Maybe something like **rot** _ψ_ = **curl** (_ψ_ **k**)? That gives the two-dimensional velocity from its stream-function, as in
> 
> https://github.com/kinnala/scikit-fem/blob/4ba1e06a01856e825d8d2f9cdfcd5742c5376f66/docs/examples/ex20.py#L73-L74

Yes I'm trying to get things like (u_y, -u_x).

Thanks for your ideas! 

l'll try them and come back soon!

**Comment by kinnala** [comment]
The above PR #507 enables running the code in your original post:
```python
In [5]: m = MeshTri() 
   ...: m.refine(5) 
   ...:  
   ...: @BilinearForm 
   ...: def zv_load(u, v, w): 
   ...:     return dot(curl(u), curl(v)) 
   ...:  
   ...: element = ElementTriMorley() 
   ...: basis = InteriorBasis(m, element) 
   ...:  
   ...: K = asm(zv_load, basis)                                               

In [6]: K                                                                     
Out[6]: 
<4225x4225 sparse matrix of type '<class 'numpy.float64'>'
	with 47561 stored elements in Compressed Sparse Row format>
```

**Comment by YerbaPage** [comment]
> The above PR #507 enables running the code in your original post:
> 
> ```python
> In [5]: m = MeshTri() 
>    ...: m.refine(5) 
>    ...:  
>    ...: @BilinearForm 
>    ...: def zv_load(u, v, w): 
>    ...:     return dot(curl(u), curl(v)) 
>    ...:  
>    ...: element = ElementTriMorley() 
>    ...: basis = InteriorBasis(m, element) 
>    ...:  
>    ...: K = asm(zv_load, basis)                                               
> 
> In [6]: K                                                                     
> Out[6]: 
> <4225x4225 sparse matrix of type '<class 'numpy.float64'>'
> 	with 47561 stored elements in Compressed Sparse Row format>
> ```

It's so kind of you to give such quick response! I've added codes you mentioned and it's running well! 

Now I'm working on assembling some other forms before testing my result, thanks again!

**Comment by kinnala** [comment]
This extension to curl was merged to master in #506 .

**Comment by YerbaPage** [comment]
Thank you so much for your advice! I've just finished my experiment and the convergence was consistent with the theoretical result!

**Comment by YerbaPage** [comment]
Hi! Thanks again for your previous help! I'm here with another question : ) 

I'm now trying to solve a Stokes equation with the nonconforming CR element as in #492 for u and a P0 element for pressure. And I want to set the normal component of u on boundary to be zero. I tired to build it in this way: 

```python
element = {'phi': ElementVectorH1(ElementTriCR()), 'p': ElementTriP0()}
basis = {variable: InteriorBasis(m, e, intorder=intorder) for variable, e in element.items()}  

dofs = basis['phi'].find_dofs({
    'left': m.facets_satisfying(lambda x: x[0] == 0),
    'right': m.facets_satisfying(lambda x: x[0] == 1),
    'top': m.facets_satisfying(lambda x: x[1] == 1),
    'buttom': m.facets_satisfying(lambda x: x[1] == 0)
})

D = np.concatenate((dofs['left'].facet['u^n'], dofs['right'].facet['u^n'],
                    dofs['top'].facet['u^n'], dofs['buttom'].facet['u^n']))
```
but got a KeyError as follows
```
KeyError                                  Traceback (most recent call last)
<ipython-input-37-fa4a0dda600a> in <module>
     10 })
     11 
---> 12 D = np.concatenate((dofs['left'].facet['u^n'], dofs['right'].facet['u^n'],
     13                     dofs['top'].facet['u^n'], dofs['buttom'].facet['u^n']))

KeyError: 'u^n'
```
I guess I may be wrong defining dofs and have changed the 'facets' and 'nodels' for many times but it didn't work.

Would you mind pointing out the problem here? That would very helpful! 
Thanks in advance!!

**Comment by gdmcbain** [comment]
I'm away from the terminal at the moment but is the facet degree of freedom called 'u' rather than 'u^n'?

https://github.com/kinnala/scikit-fem/blob/e4c0a4f0e5593502a7cebf45461e176f9668ff91/skfem/element/element_tri/element_tri_cr.py#L12

**Comment by kinnala** [comment]
There is an attempt to document these keys here: https://scikit-fem.readthedocs.io/en/latest/bcs.html#finding-degrees-of-freedom

But the documentation should be improved element-by-element. My plan is to create better docstrings for each element that explain what dofnames are available.

**Comment by YerbaPage** [comment]
Thanks for your quick reply.

I've read that part of the document when writing the codes and I guess I understand better the usage of 'u^n' and 'u' now.

Let me denote the point value of u by (u1, u2) and my aim is to make the normal component (u1, u2) dot n on boundary to be zero

**Comment by YerbaPage** [comment]
I'm not sure how `ElementVectorH1()` works (looking into it) and I guess the values are stored like [u1x, u1y, u2x, u2y, ...]? (x and y stands for two components of u and 1 2 ... stands for things like doflocs?)

**Comment by YerbaPage** [comment]
I found these codes and I'm thinking about what I can do!
https://github.com/kinnala/scikit-fem/blob/e4c0a4f0e5593502a7cebf45461e176f9668ff91/skfem/element/element_vector_h1.py#L19-L21

**Comment by YerbaPage** [comment]
```python
D = np.concatenate((dofs['left'].facet['u^1'], dofs['right'].facet['u^1'],
                    dofs['top'].facet['u^2'], dofs['buttom'].facet['u^2']))
```
This piece of code is running. I guess it will work if I'm correct with how components are stored.

**Comment by YerbaPage** [comment]
> 
> 
> There is an attempt to document these keys here: https://scikit-fem.readthedocs.io/en/latest/bcs.html#finding-degrees-of-freedom
> 
> But the documentation should be improved element-by-element. My plan is to create better docstrings for each element that explain what dofnames are available.

I find this in the documents you mentioned when reading it again! So sorry that I didn't understand them well.

**Comment by kinnala** [comment]
> Let me denote the point value of u by (u1, u2) and my aim is to set the normal component ((u1, u2) dot n) on boundary to be zero.

If you need to set the normal component to zero but the tangential component can be free, then it can be pretty tricky in general domains. (In square domains it is simpler.)

This ((u1, u2) dot n = 0) can be interpreted as an additional linear constraint between u1 and u2 at each degree-of-freedom belonging to the boundary. We do not (yet?) have any built in tools for these kind of boundary conditions but you can try Lagrange multipliers or penalty methods. If you need it in general domains, I can try to think about it.

**Comment by kinnala** [comment]
Alright, I think you can further augment the linear system with 
```python
@BilinearForm
def constr_bilinf(u, lambda, v, mu, w):
    return dot(u, w.n) * mu
```
integrated over the boundary which leads to a linear system of the form
```
K = [
    [A, B.T, C.T],
    [B, 0, 0],
    [C, 0, 0],
]
```
where `A` and `B` are from standard Stokes and `C` corresponds to `constr_bilinf`. I haven't tried it out but I think if `mu` corresponds to `ElementTriP0()` it should work.

**Comment by YerbaPage** [comment]
> 
> 
> > Let me denote the point value of u by (u1, u2) and my aim is to set the normal component ((u1, u2) dot n) on boundary to be zero.
> 
> If you need to set the normal component to zero but the tangential component can be free, then it can be pretty tricky in general domains. (In square domains it is simpler.)
> 
> This ((u1, u2) dot n = 0) can be interpreted as an additional linear constraint between u1 and u2 at each degree-of-freedom belonging to the boundary. We do not (yet?) have any built in tools for these kind of boundary conditions but you can try Lagrange multipliers or penalty methods. If you need it in general domains, I can try to think about it.

Yeah. I'm currently only testing example on a unit square so I just tried to set `D` like this
```python
D = np.concatenate((dofs['left'].facet['u^1'], dofs['right'].facet['u^1'],
                    dofs['top'].facet['u^2'], dofs['buttom'].facet['u^2']))
```
Thank you for your nice advice! Actually I'm testing a case imposing penalty for tangential component and setting D for normal component, but I met some problem in the BilinearForm part.

**Comment by YerbaPage** [comment]
Would you mind taking a look at this? I'm not sure whether it's right to define penalty <img src="https://render.githubusercontent.com/render/math?math=(%20\partial_{n}%20(\phi%20\cdot%20t),%20\psi%20\cdot%20t)"> in this way: 

(possibly wrong according to my numerical result)

```python
@BilinearForm
def penalty_1(u, v, w):
    w_t = np.array([-w.n[1], w.n[0]])
    return ((dot(d(u)[0], w.n)*w_t[0]) + (dot(d(u)[1], w.n)*w_t[1])) * dot(v, w_t)

```
This is a part of my penalty for the tangential component of u. And I integrated it over the boundary with `FacetBasis` for `ElementVectorH1(ElementTriCR())`

I've tried a lot to find the problem with my codes but I'm still not sure about this part. It would be so nice of you to give me some advice!

**Comment by kinnala** [comment]
I'm not sure. Does this give the same result?
```python
@BilinearForm
def penalty_1(u, v, w):
    w_t = np.array([-w.n[1], w.n[0]])
    return ddot(d(u), prod(w.n, w_t)) * dot(v, w_t)
```

**Comment by YerbaPage** [comment]
I get the same result with:
```python
@BilinearForm
def penalty_1(u, v, w):
    w_t = np.array([-w.n[1], w.n[0]])
    return -ddot(d(u), prod(w_t, w.n)) * dot(v, w_t)
```
I guess this is the right way with your useful module `skfem.helpers`

**Comment by kinnala** [comment]
Yes, it's currently the most concise way to write it. I'm not fully happy though because using `prod(...)` implies creating a temporary higher order tensor. This can be circumvented with `np.einsum(...)` but the syntax is not as clear as I'd hope. I'll most likely create a short convenience wrapper for `np.einsum(...)` at some point which simplifies the syntax.

**Comment by YerbaPage** [comment]
Hi! Thanks so much for your previous help and I'm here with some new questions:

I'm trying to evaluate convergence by comparing a solution vector `u` with a `u^N` from a much finer grid (because the real solution is unknown). 

I've found the `interpolator()` function from `interior_basis.py` to return pointwise values but still need gradients and Hessian. Thinking about building functions like `interpolator_grad()` and `interpolator_hess()`, I tried to learn from `interpolate()` in `basis.py` but was confused about the variables and also the index of `self.basis`.

Would you mind giving me some suggestions? Thanks in advance!

**Comment by kinnala** [comment]
First I'd try projecting the derivative onto a different finite element basis. Because Morley is `P2`, it's derivative is `P1`, so something like
```python
basis = InteriorBasis(mesh, ElementTriMorley())
dbasis = InteriorBasis(mesh, ElementTriDG(ElementTriP1()))
dx = project(x, basis_from=basis, basis_to=dbasis, diff=0)
dy = project(x, basis_from=basis, basis_to=dbasis, diff=0)
```
Now you could use `dbasis.interpolator` with `dx` and `dy`.

**Comment by YerbaPage** [comment]
> First I'd try projecting the derivative onto a different finite element basis. Because Morley is `P2`, it's derivative is `P1` discontinuous, so something like
> 
> ```python
> basis = InteriorBasis(mesh, ElementTriMorley(), intorder=2)
> dbasis = InteriorBasis(mesh, ElementTriDG(ElementTriP1()), intorder=2)
> dx = project(x, basis_from=basis, basis_to=dbasis, diff=0)
> dy = project(x, basis_from=basis, basis_to=dbasis, diff=1)
> ```
> 
> Now you could use `dbasis.interpolator` with `dx` and `dy`.

Thanks a lot for your help! They worked perfectly although I failed to accelerate the interpolating process. Interpolating over the whole fine mesh took quite a long time. 
Sorry for my late reply after finishing because it took a long time and thanks again!
