### ISSUE TITLE
ElementLineP0 unavailable in latest release

### ISSUE THREAD

**Issue by gdmcbain** [kinnala/scikit-fem#518]
The [latest release](https://github.com/kinnala/scikit-fem/releases/latest), [2.2.3](https://github.com/kinnala/scikit-fem/releases/tag/2.2.3), is from 2020-10-16 and predates #509; hence
> AttributeError: module 'skfem' has no attribute 'ElementLineP0'

**Comment by gdmcbain** [comment]
I guess that according to [Semantic Versioning](https://semver.org/spec/v2.0.0.html), this is minor, since there's new functionality, but it's all backward-compatible.

**Comment by kinnala** [comment]
Here it is in 2.3.0: https://github.com/kinnala/scikit-fem-release-tests/actions/runs/381070118
