### ISSUE TITLE
Point source vector / old scikit-fem version

### ISSUE THREAD

**Issue by jwittke** [kinnala/scikit-fem#561]
Hey,
I just want to start my rather older code which uses a point source function. It was developed with an older version of
scikit-fem version but with the actual version it doesn't run anymore.

Any tips on how to correct the function below, to make it work with the new version?

    def dc_point_sources(basis, amplitude, point):
        pt = np.vstack([np.array([point]), np.array([0.0])])
        tris = find_element(basis.mesh, point)
        y = np.zeros(basis.N)

        pts = basis.mapping.invF(pt[:, :, np.newaxis], tind=tris)

        for k in range(basis.Nbfun):
            phi = basis.elem.gbasis(basis.mapping, pts, k, tind=tris)
            y[basis.element_dofs[k, tris]] += phi[0].flatten()

        return y * amplitude / 2.

Tanks,
Jan

**Comment by kinnala** [comment]
What kind of error you get? There are some things missing for me to run it myself.

One idea is that it could've stopped working after `elem.gbasis` started returning tuples in `1.0.0`. So maybe changing `phi[0].flatten()` to `phi[0][0].flatten()` works?

**Comment by jwittke** [comment]
Running gave me the error:

    y[basis.element_dofs[k, tris]] += phi[0].flatten()
    AttributeError: 'DiscreteField' object has no attribute 'flatten'

Changing `phi[0].flatten() `to `phi[0][0].flatten()` solves the problem.

Thanks

**Comment by gdmcbain** [comment]
Is the point-source vector just the transpose of the probe matrix #601?
