### ISSUE TITLE
[question] Neumann BC for elasticity problem

### ISSUE THREAD

**Issue by gittsoy** [kinnala/scikit-fem#565]
Hello.

Thanks for your nice library. I'm trying to implement Neumann BC for the linear elasticity problem
 
<img src="https://render.githubusercontent.com/render/math?math=\int_V \boldsymbol{\sigma(u)}: \boldsymbol{\varepsilon(v)} \mathrm{d}V =  \int_{\partial V} \mathbf{t}\cdot\boldsymbol{v} \mathrm{d}S">

where t is the surface force defined on the part of the outer boundary. But i didn't find an exact way to do it in the documentation. I studied several examples and issues and came to the following solution: 

```python
import numpy as np
from skfem import *
from skfem.models.elasticity import *
from skfem.visuals.matplotlib import *

m = MeshTri.init_tensor(np.linspace(0, 10, 20), np.linspace(0, 2, 10))

e1 = ElementTriP1()
mapping = MappingIsoparametric(m, e1)

e = ElementVectorH1(e1)
gb = InteriorBasis(m, e, mapping, 1)

E = 7.3e4
nu = 0.34
Lambda, mu = lame_parameters(E, nu)

K = asm(linear_elasticity(Lambda, mu), gb)

pu = -1.0 # MPa
def load_func(x, y):
    return pu * (2.0 * x - 1.0)

# Neumann boundary condition
@LinearForm
def loadingN(v, w):
    return load_func(*w.x) * v.value[1]

top_facets=m.facets_satisfying(lambda x: x[1] == 2.)
top_basis = FacetBasis(m, e, facets=top_facets)

rpN = asm(loadingN, top_basis)

clamped = gb.get_dofs(lambda x: x[0] == 0.0).all()
free = gb.complement_dofs(clamped)

u = solve(*condense(K, rpN, I=free)) 

m = MeshTri(m.p + u[gb.nodal_dofs], m.t)
draw(m)
print("min/max u1:", min(u[gb.nodal_dofs][0]), max(u[gb.nodal_dofs][0]))
print("min/max u2:", min(u[gb.nodal_dofs][1]), max(u[gb.nodal_dofs][1]))

x=u
C = linear_stress(Lambda, mu)
# post processing
s = {}
e_dg = ElementTriDG(ElementTriP1())

for itr in range(2):
    for jtr in range(2):

        @BilinearForm
        def proj_cauchy(u, v, w):
            return C(sym_grad(u))[itr, jtr] * v

        @BilinearForm
        def mass(u, v, w):
            return u * v

        ib_dg = InteriorBasis(m, e_dg)

        s[itr, jtr] = solve(asm(mass, ib_dg),
                            asm(proj_cauchy, gb, ib_dg) @ x)

s[2, 2] = 0 # General plane stress

vonmises = np.sqrt(.5 * ((s[0, 0] - s[1, 1]) ** 2 +
                          (s[1, 1] - s[2, 2]) ** 2 +
                          (s[2, 2] - s[0, 0]) ** 2 +
                          6. * s[0, 1]**2))

ax = plot(ib_dg, vonmises, shading='gouraud') 
draw(m, ax=ax)
print("min/max vonmises:", min(vonmises), max(vonmises))
```

Сould you tell me if I'm doing it right? or there is another way described in the documentation.

**Comment by kinnala** [comment]
This is the relevant part:
```python
pu = -1.0 # MPa
def load_func(x, y):
    return pu * (2.0 * x - 1.0)

# Neumann boundary condition
@LinearForm
def loadingN(v, w):
    return load_func(*w.x) * v.value[1]

top_facets=m.facets_satisfying(lambda x: x[1] == 2.)
top_basis = FacetBasis(m, e, facets=top_facets)

rpN = asm(loadingN, top_basis)
```
If you want, it can be generalized slightly to
```python
from skfem.helpers import dot

def trac(x, y):
    pu = -1.
    return np.array([0. * x, pu * (2. * x - 1.)])

@LinearForm
def loadingN(v, w):
    return dot(trac(*w.x), v)

top_facets = m.facets_satisfying(lambda x: x[1] == 2.)
top_basis = FacetBasis(m, e, facets=top_facets)

rpN = asm(loadingN, top_basis)
```
The small difference is that this allows specifying arbitrary traction vector `trac`; not just `y`-component.

**Comment by kinnala** [comment]
Just adding a note that this part is not necessary:
```python
mapping = MappingIsoparametric(m, e1)
```
With simplical elements I suggest that you use `MappingAffine(m)` for better performance.

**Comment by gittsoy** [comment]
Thank you very much for the quick response, i'm glad there is no mistake. I will use your generalized version.
I also wanted to ask about von mises stress calculation. I used the code from example 4 

```python
C = linear_stress(Lambda, mu)
# post processing
s = {}
e_dg = ElementTriDG(ElementTriP1())

for itr in range(2):
    for jtr in range(2):

        @BilinearForm
        def proj_cauchy(u, v, w):
            return C(sym_grad(u))[itr, jtr] * v

        @BilinearForm
        def mass(u, v, w):
            return u * v

        ib_dg = InteriorBasis(m, e_dg)

        s[itr, jtr] = solve(asm(mass, ib_dg),
                            asm(proj_cauchy, gb, ib_dg) @ x)

s[2, 2] = 0 # General plane stress

vonmises = np.sqrt(.5 * ((s[0, 0] - s[1, 1]) ** 2 +
                          (s[1, 1] - s[2, 2]) ** 2 +
                          (s[2, 2] - s[0, 0]) ** 2 +
                          6. * s[0, 1]**2))
```

But i do not fully understand how it works. Is it also correct for my example? 
Is it possible to define stress tensor as a linear form and pass interpolated solution x=basis.interpolate(u) as an argument?

**Comment by kinnala** [comment]
Here the idea is to calculate each component of the Cauchy stress tensor separately via L^2-projection; that's where the two for-loops come from. This is quite old school way of doing it (from two years ago) but still works. There could be a more straightforward way of doing it using some of the new features but I haven't thought about it too much because this approach still works well.

**Comment by gittsoy** [comment]
Ok, thanks for the help :) So I think this issue can be closed.

**Comment by tianyikillua** [comment]
As @gdmcbain [mentioned](https://github.com/kinnala/scikit-fem/issues/564#issuecomment-782333737), maybe you can try this to compute stress tensors on Gauss points
```python
u_gp = gb.interpolate(u)
eps_gp = 0.5 * (u_gp.grad + u_gp.grad.transpose(1, 0, 2, 3))
C = linear_stress(Lambda, mu)
sig_gp = C(eps_gp)
```

I tried yesterday and it works perfectly and gives the same results. I haven't yet compared the performance yet.
