### ISSUE TITLE
Inhomogeneous boundary condition for Biharmonic equation

### ISSUE THREAD

**Issue by YerbaPage** [kinnala/scikit-fem#566]
Hi!
Thanks for your previous help. 

I'm trying to solve a Biharmonic equation on [0,1] × [0,1] with the Morley element. The real solution I want to test is $u = xy$. 
I tried to impose the boundary conditions in this way after reading ex02 and ex14:

```python
import numpy as np
from skfem import *
from skfem.helpers import *
from skfem.assembly import BilinearForm, LinearForm
from skfem.visuals.matplotlib import draw, plot, show

def exact_u(x, y):
    return x*y

def dexact_u(x, y):
    dux = y
    duy = x
    return dux, duy

def exact_un(x, y):
    nx = -1 * (x == 0) + 1 * (x == 1)
    ny = -1 * (y == 0) + 1 * (y == 1)
    dux, duy = dexact_u(x, y)
    return nx * dux + ny * duy

m = MeshTri()
m.refine(3)
element = ElementTriMorley()

basis = InteriorBasis(m, element)
K = asm(BilinearForm(lambda u, v, w: ddot(dd(u), dd(v))), basis)
f = asm(LinearForm(lambda v, w: 0 * v), basis)

# all boundary dofs
boundary_dofs = basis.find_dofs()['all'].all()
# nodal dofs on boundary
boundary_dofs_u = np.array([i for i in boundary_dofs if i in basis.nodal_dofs[0]])
# facet dofs on boundary
boundary_dofs_un = np.array([i for i in boundary_dofs if i in basis.facet_dofs[0]])

uh0 = np.zeros(basis.N)
# boundary condition for 'u'
uh0[boundary_dofs_u] = exact_u(basis.doflocs[0][boundary_dofs_u], basis.doflocs[1][boundary_dofs_u])
# boundary condition for 'u_n'
uh0[boundary_dofs_un] = exact_un(basis.doflocs[0][boundary_dofs_un], basis.doflocs[1][boundary_dofs_un])

uh0 = solve(*condense(K, f, uh0, D=boundary_dofs_u))

```
The result seemed close after imposing the Dirichlet boundary condition but got worse with the Neumann boundary condition I added. I tried to check the values of exact_un and indexes of facet dofs I chose but didn't find the bug.

Could you take a look at this? Thanks in advance!

**Comment by kinnala** [comment]
> ```python
> uh0 = solve(*condense(K, f, uh0, D=boundary_dofs_u))
> ```
I think you want to have here `D=np.concatenate((boundary_dofs_u, boundary_dofs_un))`.

**Comment by YerbaPage** [comment]
> 
> 
> > ```python
> > uh0 = solve(*condense(K, f, uh0, D=boundary_dofs_u))
> > ```
> 
> I think you want to have here `D=np.concatenate((boundary_dofs_u, boundary_dofs_un))`.
> 
> Edit: Or simply `D=boundary_dofs`.

Ops, sorry that I posed the codes I used to only impose Dirichlet BC by mistake.

I used 
```python
uh0 = solve(*condense(K, f, uh0, D=boundary_dofs_u))
```
to impose Dirichlet BC and the result is convergent.

But when I changed into 
```python
uh0 = solve(*condense(K, f, uh0, D=boundary_dofs))
```
to impose both Dirichlet and Neumann BC, the result goes worse.

**Comment by YerbaPage** [comment]
I used this piece of codes to calculate the L2 error of the solution:
```python
L2_Error = np.sqrt(Functional(lambda w: (w.w - exact_u(w.x[0], w.x[1]))**2).assemble(basis, w=basis.interpolate(uh0).value))
print(L2_Error)
```
It shows that the solutions from the two ways are both divergent.

**Comment by YerbaPage** [comment]
I also tested those codes for a solution `u = (xy(1 - x)(1 - y)) ^2` with homogeneous boundary conditionby changing:

```python
def exact_u(x, y):
    return (x * y * (1 - x) * (1 - y))**2
    # return (x * y * (1 - x) * (1 - y))**2 + 100


def dexact_u(x, y):
    dux = (y * (1 - y))**2 * (4 * x**3 - 6 * x**2 + 2 * x)
    duy = (x * (1 - x))**2 * (4 * y**3 - 6 * y**2 + 2 * y)
    return dux, duy
```
and defining `f` with:

```python
@LinearForm
def f_load(v, w):
    x, y = w.x
    return (24 * ((x**2 - x + 1)**2 + (y**2 - y + 1)**2 + 12 * (x - 1) *
                  (y - 1) * x * y) - 40) * v

f = asm(f_load, basis)
```
And the solution was convergent with and without that constant 100 I added to `exact_u`.

**Comment by kinnala** [comment]
I tried plotting the difference of `uh0` and `exact_u` in the first example:
![Figure_1](https://user-images.githubusercontent.com/973268/108623792-7c31b880-7449-11eb-827c-693201a0a6e2.png)

**Comment by kinnala** [comment]
This has to have something to do with the fact that the typical integration by parts formula used with biharmonic equations assumes zero boundary values. I just cannot figure out exactly what's going on right now. I need to think about it a bit further.

**Comment by kinnala** [comment]
Now it looks better, by initializing `uh0` like this:
```python
uh0 = project(lambda x, y: x * y, basis_to=basis)
```
I'm not still sure why the another approach is not working.

**Comment by kinnala** [comment]
Alright, there is a caveat which I did not remember. It seems that the unit normal vectors used when initializing the DOFs are not consistently outward normals. This explains the behaviour. Now the remaining question is that should we fix it?

**Comment by YerbaPage** [comment]
> Now it looks better, by initializing `uh0` like this:
> 
> ```python
> uh0 = project(lambda x, y: x * y, basis_to=basis)
> ```
> 
> I'm not still sure why the another approach is not working.

Could you attach the codes you used? I tried to replace `uh0 = np.zeros(basis.N)` by `uh0 = project(lambda x, y: x * y, basis_to=basis)` b ut didn't see the difference here. I'm not sure whether there need to be some other changes or I've changed somewhere but didn't notice.

**Comment by kinnala** [comment]
This appears to give zero L2 error which I think is expected because P2 represents this solution exactly:
```python
import numpy as np
from skfem import *
from skfem.helpers import *
from skfem.assembly import BilinearForm, LinearForm
from skfem.visuals.matplotlib import draw, plot, show

def exact_u(x, y):
    return x*y

def dexact_u(x, y):
    dux = y
    duy = x
    return dux, duy

def exact_un(x, y):
    nx = -1 * (x == 0) + 1 * (x == 1)
    ny = -1 * (y == 0) + 1 * (y == 1)
    dux, duy = dexact_u(x, y)
    return nx * dux + ny * duy

m = MeshTri.init_sqsymmetric()
m.refine(3)
element = ElementTriMorley()

basis = InteriorBasis(m, element)
K = asm(BilinearForm(lambda u, v, w: ddot(dd(u), dd(v))), basis)
f = asm(LinearForm(lambda v, w: 0 * v), basis)

# all boundary dofs
boundary_dofs = basis.find_dofs()['all'].all()

uh0 = project(lambda x, y: x * y, basis_to=basis)

uh0 = solve(*condense(K, f, uh0, D=boundary_dofs))

L2_Error = np.sqrt(Functional(lambda w: (w.w - exact_u(w.x[0], w.x[1]))**2).assemble(basis, w=basis.interpolate(uh0)))
print(L2_Error)

pbasis = basis.with_element(ElementTriP1())
y = project(uh0, basis_from=basis, basis_to=pbasis)

plot(pbasis, y-exact_u(*m.p), Nrefs=3, colorbar=True)
show()
```

**Comment by YerbaPage** [comment]
> Alright, there is a caveat which I did not remember. It seems that the unit normal vectors used when initializing the DOFs are not consistently outward normals. This explains the behaviour. Now the remaining question is that should we fix it?

I've found my bug and the result goes well now. I think it would be better if we use outward vectors to initialize the DOFs. 

I tried to study the codes in `element_global.py` but I'm not sure how to fix it.

**Comment by kinnala** [comment]
> I think it would be good if we use outward vectors to initialize the DOFs.
> I tried to study the codes in `element_global.py` but I'm not sure how to fix it.

Let's open another issue for that. It's not completely obvious how to do this because `ElementGlobal` uses its own ordering independent of `Mapping`. The reason why it's done like this currently is to make sure that normals for the internal DOFs between two elements point to same directions. That's required for conformity, but boundary normals are not taken into account at all.
