### ISSUE TITLE
ElementTetP2 as nodal basis

### ISSUE THREAD

**Issue by kinnala** [kinnala/scikit-fem#57]
For some reason, `ElementTetP2` is also constructed via hierarchic basis. Make it use nodal basis instead.

**Comment by kinnala** [comment]
It is very inconvenient to set inhomogeneous boundary conditions if the basis is not nodal. Moreover, one would expect a vector of ones to correspond the function f(x)=1 in all the standard bases.

**Comment by gdmcbain** [comment]
> Moreover, one would expect a vector of ones to correspond the function f(x)=1 in all the standard bases.

This nodal interpolation property is a nice property but a counterexample is the one-dimensional Hermite elements for which the discretization of unity looks like `[1, 0, …, 1, 0, …, …]`.  Inhomogeneous conditions for these are reasonably straightforward but somewhat peculiar to them. I wonder whether this indicates that the imposition of such boundary conditions should be encapsulated in a function (something like `condense`) and be the responsibility of the Basis (being the combination of Mesh, Element, & Mapping).

But yes, for the 'standard' bases, yes; it would be surprising for the ten-noded tetrahedral element not to be Lagrangian.

**Comment by kinnala** [comment]
I have thought about automatizing essential BC's quite profoundly when I was working with fourth-order problems in academia. It seems that this is in general a harder problem than you would initially guess.

A particularly tough example is given by the 21 DOF Argyris element in L-shaped domain. Finding correct DOF's to eliminate at the L-corner point is hard even for an expert, and the logic behind it seems to include the problem geometry. 

I concluded that automation of essential BC's is probably not possible for general elements, and not even for all elements supported by scikit-fem. At least, it's not going to be an easy task.

**Comment by gdmcbain** [comment]
Ah.  I shouldn't be surprised that something easy in one dimension doesn't work at all in two or three.  Thanks.

**Comment by kinnala** [comment]
@gdmcbain Can you confirm that this change didn't interfere with your new example? I understood that you use only zero boundary values there.

**Comment by kinnala** [comment]
Here are the lines of Mathematica I used:
```
In[43]:= g                                                                      

Out[43]= {#1 /. {x -> 0, y -> 0, z -> 0} & , #1 /. {x -> 1, y -> 0, z -> 0} & , 
 
>    #1 /. {x -> 0, y -> 1, z -> 0} & , #1 /. {x -> 0, y -> 0, z -> 1} & , 
 
>    #1 /. {x -> 0.5, y -> 0, z -> 0} & , 
 
>    #1 /. {x -> 0.5, y -> 0.5, z -> 0} & , 
 
>    #1 /. {x -> 0, y -> 0.5, z -> 0} & , #1 /. {x -> 0, y -> 0, z -> 0.5} & , 
 
>    #1 /. {x -> 0.5, y -> 0, z -> 0.5} & , 
 
>    #1 /. {x -> 0, y -> 0.5, z -> 0.5} & }

In[44]:= f                                                                      

                                      2   2   2
Out[44]= {1, x, y, z, x y, y z, x z, x , y , z }

In[45]:= (Outer[#1[#2]&, g, f] // Inverse // Transpose) . Transpose[{f}] // Fort
ranForm                                                                         
                                                                                
Out[45]//FortranForm=                                                           
         List(List(1. - 3.*x + 2.*x**2 - 3.*y + 4.*x*y + 2.*y**2 - 3.*z + 
     -     4.*x*z + 4.*y*z + 2.*z**2),List(0. - 1.*x + 2.*x**2),
     -   List(0. - 1.*y + 2.*y**2),List(0. - 1.*z + 2.*z**2),
     -   List(0. + 4.*x - 4.*x**2 - 4.*x*y - 4.*x*z),List(0. + 4.*x*y),
     -   List(0. + 4.*y - 4.*x*y - 4.*y**2 - 4.*y*z),
     -   List(0. + 4.*z - 4.*x*z - 4.*y*z - 4.*z**2),List(0. + 4.*x*z),
     -   List(0. + 4.*y*z))

In[46]:= D[(Outer[#1[#2]&, g, f] // Inverse // Transpose) . Transpose[{f}], {x,1
}] // FortranForm                                                               

Out[46]//FortranForm= 
         List(List(-3. + 4.*x + 4.*y + 4.*z),List(-1. + 4.*x),List(0),List(0),
     -   List(4. - 8.*x - 4.*y - 4.*z),List(4.*y),List(-4.*y),List(-4.*z),
     -   List(4.*z),List(0))

In[47]:= D[(Outer[#1[#2]&, g, f] // Inverse // Transpose) . Transpose[{f}], {y,1
}] // FortranForm                                                               

Out[47]//FortranForm= 
         List(List(-3. + 4.*x + 4.*y + 4.*z),List(0),List(-1. + 4.*y),List(0),
     -   List(-4.*x),List(4.*x),List(4. - 4.*x - 8.*y - 4.*z),List(-4.*z),
     -   List(0),List(4.*z))

In[48]:= D[(Outer[#1[#2]&, g, f] // Inverse // Transpose) . Transpose[{f}], {z,1
}] // FortranForm                                                               

Out[48]//FortranForm= 
         List(List(-3. + 4.*x + 4.*y + 4.*z),List(0),List(0),List(-1. + 4.*z),
     -   List(-4.*x),List(0),List(-4.*y),List(4. - 4.*x - 4.*y - 8.*z),
     -   List(4.*x),List(4.*y))
```

**Comment by gdmcbain** [comment]
Very interesting. I don't have Mathematica but will try to reproduce this in SymPy,  Maxima, Emacs Calc, or similar, when I get back to Sydney.

**Comment by gdmcbain** [comment]
The Bratu—Gelfand example #126 had homogeneous boundary conditions but I think I only implemented it in P1. The backward facing step does have inhomogeneous Dirichlet data. That needs P2 velocity for Taylor—Hood Navier—Stokes elements.

**Comment by kinnala** [comment]
I'm sorry I forgot to mention the commit I meant. So here I made modifications to ElementTetP2: https://github.com/kinnala/scikit-fem/commit/e5c9dfcd71261e9b9fc209714f2203d59d21dbe5 I hope these modifications did not break any of your newer examples that are not yet in the test suite.
