### ISSUE TITLE
flip interpolator

### ISSUE THREAD

**Issue by gdmcbain** [kinnala/scikit-fem#572]
Currently [`InteriorBasis.interpolator`](https://github.com/kinnala/scikit-fem/blob/d14d6d8398c48c86c86d353b8822acbfef830be0/skfem/assembly/basis/interior_basis.py#L131-L146) is curried, taking first the `ndarray` of a finite element function's degrees of freedom and then the `ndarray` of the coordinates of some absciss&aelig;.

If one runs a long unsteady simulation with many time-steps on the same mesh (i.e. same `InteriorBasis`), it's common to &lsquo;probe&rsquo; a fixed array of points and record the interpolated solution there; e.g. gdmcbain/fenics-tuto-in-skfem#26 which is a two-dimensional incompressible Navier&ndash;Stokes problem with 5000 time-steps in which the `ElementTriP1` pressure is logged at two points.  Using `InteriorBasis.interpolator` would require a new interpolator at each time-step.  If one could [flip](https://toolz.readthedocs.io/en/latest/api.html?highlight=flip#toolz.functoolz.flip) `interpolator` so that it was defined for its `InteriorBasis` on a fixed array of points and then took a solution `ndarray`, it would just be a matter of calling the same flipped interpolator on each new snapshot.

I think most of the uses in the suite of examples to date just call it once, so it wouldn't make much difference to them whether the method were curried either way or uncurried, but I can imagine cases in which the current currying is desirable; e.g. tracing an [integral curve](https://en.wikipedia.org/wiki/Integral_curve) on a vector solution.

The current version of the unsteady Navier&ndash;Stokes problem has a hardcoded flip of `interpolate`, a function [`probe`](https://github.com/gdmcbain/fenics-tuto-in-skfem/blob/3c1b7910286847d8964d041b10c9c622ef95383f/08_navier_stokes_cylinder/st08_navier_stokes_cylinder_pyamg.py#L49-L64), but since it seems like a reasonably common thing to want to do, I intend to think about how to refactor the existing method in scikit-fem to provide both orders of currying.

**Comment by kinnala** [comment]
Cool! Is it enough to have two keyword arguments, e.g.,
```python
def interpolator(self, solution: Optional[ndarray] = None, points: Optional[ndarray] = None):
    if solution is not None and points is None:
        # return original interpolator
    if solution is None and points is not None:
        # return "probe"
    raise Exception
```

**Comment by gdmcbain** [comment]
Yeah, we could do that; type-wise it might be funny rhough. I mean literally in present Python the missing type would be the same either way, just `ndarray`, sunce that covers both `solution` and `points` but conceptually they're quite different. The new one with the solution missing returns a linear form on solutions. So I was thinking of giving it a different name ('probe'?) to make this distinction more plain, but to share internal implementations.

**Comment by kinnala** [comment]
Sure that's probably better. I expect `numpy.typing` to improve in the future and at some point we can hopefully be more explicit about the dtypes and shapes of the inputs.
