### ISSUE TITLE
Example 36 - Nearly Incompressible Hyperelasticity: XDMF Export (Meshio Error)

### ISSUE THREAD

**Issue by adtzlr** [kinnala/scikit-fem#581]
Hi,

in [Example 36](https://github.com/kinnala/scikit-fem/blob/master/docs/examples/ex36.py), line 256, I had to transpose the mesh points to be able to export the XDMF file.

Code as is

```python
        Mesh(mesh.p, cells={"tetra": mesh.t.T},
```

should be changed to

```python
        Mesh(mesh.p.T, cells={"tetra": mesh.t.T},
```

Best regards, 
Andreas

**Comment by adtzlr** [comment]
One additional information:

```python
print(pkg_resources.get_distribution('scikit-fem').version)
2.5.0
```

**Comment by kinnala** [comment]
Makes sense, `meshio` usually expects one point per row.

**Comment by kinnala** [comment]
I wonder why this example is not using `Mesh.save`...

**Comment by adtzlr** [comment]
I'm new to scikit-fem and I'm just diving through the examples - so I can't help you on that :blush:

**Comment by kinnala** [comment]
Don't worry! Just a reminder for myself to look into it.

Feel free to report any inconsistencies in the documentation or propose improvements.

**Comment by gdmcbain** [comment]
I don't think that this has ever worked:

https://github.com/kinnala/scikit-fem/blob/e0703948a5d5ed18f78c935a9d6929f76a104648/docs/examples/ex36.py#L253

Also there's no need to transpose the scalar pressure

https://github.com/kinnala/scikit-fem/blob/e0703948a5d5ed18f78c935a9d6929f76a104648/docs/examples/ex36.py#L259

**Comment by gdmcbain** [comment]
Actually transposing the pressure might work but better is to flatten or squeeze the `nodal_dofs`, as in 

https://github.com/kinnala/scikit-fem/blob/e0703948a5d5ed18f78c935a9d6929f76a104648/docs/examples/ex18.py#L119
