### ISSUE TITLE
Why do I have to initialize the deformation gradient with zeros?

### ISSUE THREAD

**Issue by adtzlr** [kinnala/scikit-fem#590]
Why do I have to initialize the deformation gradient with zeros, add the ones to the diagonal terms and finally add the displacement gradient? I mean I tried to write down

```python
F = grad(u)
for i in range(3):
    F[i, i] += 1.
```

instead of

```python
F = zeros_like(grad(u))
for i in range(3):
    F[i, i] += 1.
F += grad(u)
```

but this seems to give a different result. Honestly, I do not understand why. Do you have any explanation for that? (I took the code snippet from example 36) 

In addition to that,I find the different import statements for math helpers a bit confusing - although I understand why they are necessary. I mean these imports:

```python
from numpy import (einsum, linalg as nla, zeros,
                   zeros_like, concatenate, split as npsplit,
                   hstack, abs as npabs, arange, sqrt)
from skfem.helpers import grad, transpose, det, inv
```

In the beginning I did not understand why I can't use `det` and `inv` from `numpy.linalg` but then I realized the special structure of the arrays `(3,3,n,m)`. I think this shape is used in order to obtain a reasonable performance with Python/NumPy 😄 

Anyway, I'll experiment with the examples and I hope Github Issues are the right place to ask.
Thanks and with best regards, 
Andreas

**Comment by kinnala** [comment]
I tried it out with a debugger by adding
```python
import pdb; pdb.set_trace()
```
after the lines you mention.
```python
(Pdb) FF = grad(u)
(Pdb) FF[0, 0] += 1.
(Pdb) FF[1, 1] += 1.
(Pdb) FF[2, 2] += 1.
(Pdb) (FF-F).sum()
0.0
```
I don't see any difference here.

**Comment by kinnala** [comment]
> In the beginning I did not understand why I can't use `det` and `inv` from `numpy.linalg` but then I realized the special structure of the arrays `(3,3,n,m)`. I think this shape is used in order to obtain a reasonable performance with Python/NumPy 

This is correct. Here is some information related to the forms: https://scikit-fem.readthedocs.io/en/latest/forms.html#helpers-are-useful-but-not-necessary

**Comment by kinnala** [comment]
> In addition to that,I find the different import statements for math helpers a bit confusing - although I understand why they are necessary. I mean these imports:
> 
> ```python
> from numpy import (einsum, linalg as nla, zeros,
>                    zeros_like, concatenate, split as npsplit,
>                    hstack, abs as npabs, arange, sqrt)
> from skfem.helpers import grad, transpose, det, inv
> ```

Yeah, I think more typical would be to have `import numpy as np` and then use `np.einsum` and so on. This example was not written by me but maybe I will update it at some point.

**Comment by adtzlr** [comment]
Thanks for your investigations. I modified the mentioned lines in function F1 of example 36 but I did not change the calculation of the deformation gradient in the other functions. Then the solution did not converge anymore. I will have a look at it again tomorrow and hopefully provide some code for reproduction.

**Comment by adtzlr** [comment]
Here is the output I get with the unmodified Example 36 taken from the docs folder:

```python
1, norm_du: 15.945909822097681, norm_dp: 5.921076520330817
2, norm_du: 5.598466873920148, norm_dp: 7.5338746879470735
3, norm_du: 1.0735307535449552, norm_dp: 3.52864022713699
4, norm_du: 0.08852224392032632, norm_dp: 0.4692554732052099
5, norm_du: 0.005475563449509868, norm_dp: 0.013662254425980746
6, norm_du: 7.064329920208044e-05, norm_dp: 0.0002627006123853513
7, norm_du: 1.5250880685127334e-08, norm_dp: 9.71235752142727e-08
8, norm_du: 2.0704928782384954e-15, norm_dp: 7.487594363769038e-15
```

If I modify Function `F1` in it to

```python
def F1(w):
    u = w["disp"]
    p = w["press"]
    #F = zeros_like(grad(u))
    F = grad(u)
    for i in range(3):
        F[i, i] += 1.
    #F += grad(u)
    J = det(F)
    Finv = inv(F)
    return p * J * transpose(Finv) + mu * F
```

the solution does not converge anymore. I get this output instead:

```python
1, norm_du: 265473.40320451476, norm_dp: 299546.07524476666
2, norm_du: 90483.89305264289, norm_dp: 101839.45523656483
3, norm_du: 101958.09998693928, norm_dp: 76422.94872722038
4, norm_du: 2184968.3522374863, norm_dp: 795916.5493081902
5, norm_du: 738306.5995066894, norm_dp: 273316.3415609701
6, norm_du: 489525.8807993895, norm_dp: 179562.88411103134
7, norm_du: 355507.7170372445, norm_dp: 119642.89531935522
8, norm_du: 230109.72562298647, norm_dp: 78772.38589782098
9, norm_du: 154052.93993635778, norm_dp: 51718.8543437011
10, norm_du: 101698.800712649, norm_dp: 39334.79494817416
11, norm_du: 541049.8794640927, norm_dp: 83827.73033857255
12, norm_du: 814851.6566838606, norm_dp: 54564.865595477415
```

So I assumed I can't "initialize" `F` with `grad(u)`...

My sckit-fem version (from pip) is
```python
print(pkg_resources.get_distribution('scikit-fem').version)
>>> 2.5.0
```

and I use Python 3.8 with Anaconda on Win10.

**Comment by kinnala** [comment]
This is a classical mistake when using numpy. I did not notice it first but now it's obvious.

One should write
```python
F = grad(u).copy()
```
instead.

**Comment by adtzlr** [comment]
Oh wow, thanks @kinnala !

**Comment by kinnala** [comment]
I made some improvements to this example here: https://github.com/kinnala/scikit-fem/pull/589/commits/f224989ee5027553281f26fa427b6cd4e38e3ec9

Sorry for doing it in a relatively unrelated branch. However, it should address everything pointed out here.
