### ISSUE TITLE
pytest

### ISSUE THREAD

**Issue by nschloe** [kinnala/scikit-fem#597]
Rather than a bug, this is more of a hint from dev to dev (and I'll immediately close this as well). A while ago, I switched from python-unittest to pytest and I'm not looking back. Definitely worth checking out if you haven't yet. It's way more popular too, at least [according to stackoverflow](https://github.com/nschloe/stacktags#python-testing).

**Comment by gdmcbain** [comment]
Yes, although not in the standard library, I believe it is already the de facto standard.
