### ISSUE TITLE
Mesh2D.save puts points in yz-plane

### ISSUE THREAD

**Issue by gdmcbain** [kinnala/scikit-fem#60]
While investigating the `MeshTri` returned by `refinterp` #59 , I was puzzled to find that `save` prepends rather than appends zero coordinates; i.e. it puts it into the *yz*-plane rather than the *xy*-plane.

See https://github.com/kinnala/scikit-fem/blame/master/skfem/mesh/mesh2d/mesh2d.py#L191
```python
        # a row of zeros required in 2D
        p = np.vstack((np.zeros(self.p.shape[1]), self.p))
```

Is that intentional?

**Comment by kinnala** [comment]
I think that embedding into R^3 was done due to vtk export. But yz-plane sounds strange indeed.

**Comment by gdmcbain** [comment]
Yes, something to do with VTK, but maybe not too serious.
```python
meshio.write('M2.vtk', meshio.Mesh(M.p.T, {'triangle': M.t.T}))
```
> WARNING:root:VTK requires 3D points, but 2D points given. Appending 0 third component.

**Comment by kinnala** [comment]
Originally scikit-fem used pyevtk so it might be a remnant. I think it can be freely removed.
