### ISSUE TITLE
mpl plot options

### ISSUE THREAD

**Issue by nschloe** [kinnala/scikit-fem#607]
After having computed a solution in for 1D meshes, one can plot the result via
```python
skfem.visuals.matplotlib.plot(basis, coeffs)
```
![Figure_1](https://user-images.githubusercontent.com/181628/113306973-ec631200-9304-11eb-979e-2ca5610f4e77.png)

I'd be great if this function would accept and format a few args and kwargs to the internal `plt.plot`. I'm specifically looking for the style (e.g., `-b`) and the `label`. (Note how the label is missing in the above plot for the FEM function and how the "samples" aren't even visible because of the thick markers.)

**Comment by gdmcbain** [comment]
I see. I had thought that `**kwargs` were passed on but i see that they aren't 

https://github.com/kinnala/scikit-fem/blob/3369c040005c90e7edd925694620c8bfd1048286/skfem/visuals/matplotlib.py#L155

Would that do?

**Comment by gdmcbain** [comment]
I think I mostly only use the wrapper for quick demos while for anything archival I usually end up resorting to matplotlib directly, as in https://github.com/kinnala/scikit-fem/blob/3369c040005c90e7edd925694620c8bfd1048286/docs/examples/ex16.py#L45

**Comment by nschloe** [comment]
That works too. I'm using
```python
plt.plot(basis.mesh.p[0], coeffs[basis.nodal_dofs[0]], "-", label="my label")
```
now.
