### ISSUE TITLE
saving solution as SVG results in huge file

### ISSUE THREAD

**Issue by nschloe** [kinnala/scikit-fem#608]
When saving a solution of a 1D problem with 1000 dofs as an SVG, the file will be a whopping 116MB large. I suppose there's something wrong with `plot`?

MWE:
```python
from skfem import *
from skfem.models.poisson import laplace, unit_load

m = MeshLine().refined(10)

e = ElementLineP1()
basis = InteriorBasis(m, e)

A = asm(laplace, basis)
b = asm(unit_load, basis)

x = solve(*condense(A, b, I=m.interior_nodes()))

if __name__ == "__main__":
    from os.path import splitext
    from sys import argv
    from skfem.visuals.matplotlib import plot, savefig

    plot(m, x, shading='gouraud', colorbar=True)
    savefig("test_solution.svg")
```

**Comment by kinnala** [comment]
Thanks for the report. Seems that there is a bug in the indentation which causes `ax.plot` to run as many times as there are elements.

**Comment by kinnala** [comment]
Indentation of this line should be reduced by one: https://github.com/kinnala/scikit-fem/blob/master/skfem/visuals/matplotlib.py#L155
