### ISSUE TITLE
RTD build error

### ISSUE THREAD

**Issue by kinnala** [kinnala/scikit-fem#61]
Log is here:

https://readthedocs.org/api/v2/build/7863347.txt

Currently cannot find any real reason for the build failure. Gotta investigate more.

**Comment by gdmcbain** [comment]
No, there's nothing obvious in that report, is there.

Is this since 10bfc9b943e47a3ef0ba69ae46d544cadbee8623 ?  I did include some special Unicode characters in a `print`-string. Could that have been it?
```python
     print('ψ0 = {} (cf. exact = 1/64 ≐ {})'.format(Psi0, 1/64)) 
```

**Comment by kinnala** [comment]
Yes, it's after I added the new example. I still didn't figure it out. Since there are no error messages, I probably have to just remove parts of the example and try whether it compiles. It works on my local machine well enough.,

**Comment by kinnala** [comment]
I'm now planning the switch to hosting static Sphinx generated HTML-files in a separate repository using Github Pages. The code for generating the docs will remain here but the build directory will be in a separate repository, e.g. scikit-fem-docs. Through GH pages, this will be hosted at https://kinnala.github.io/scikit-fem-docs/.

**Comment by kinnala** [comment]
This is now done.
