### ISSUE TITLE
interpolate Morley

### ISSUE THREAD

**Issue by gdmcbain** [kinnala/scikit-fem#62]
The problem is to interpolate a function defined on Morley elements at a specified (*x, y*) point which isn't necessarily a node; e.g. the deflection at the centre of the Kirchhoff plate in ex02, or the value of the stream-function at the centre of the circular-cylindrical cavity in ex18.

Attempting `MeshTri.interpolator` with the `MeshTri` returned by `refinterp` fails #59; the mesh is invalid, having duplicate points.

I think interpolation involves two steps:
1. Find the element (if any) that contains the point.
1. Evaluate the function based on the local basis functions of that element and the elemental degrees of freedom.

and I suspect that in general the first is the harder.  

Thus far, this operation is only implemented in scikit-fem as `MeshTri.interpolator` (P1) and `MeshTri.const_interpolator` (P0) and makes use of :
* [`matplotlib.tri.Triangulation`](https://matplotlib.org/api/tri_api.html?highlight=matplotlib%20tri%20triangulation#matplotlib.tri.Triangulation),
* [`matplotlib.tri.LinearTriInterpolator`](https://matplotlib.org/api/tri_api.html?highlight=matplotlib%20tri%20triangulation#matplotlib.tri.LinearTriInterpolator)
* [`matplotlib.tri.Triangulation.get_trifinder`](https://matplotlib.org/api/tri_api.html?highlight=matplotlib%20tri%20triangulation#matplotlib.tri.Triangulation.get_trifinder)

Perhaps the [`TriFinder`](https://matplotlib.org/api/tri_api.html?highlight=matplotlib%20tri%20triangulation#matplotlib.tri.TriFinder) might be factored out of those so that it could also be used for other elements defined on linear simplicial meshes; e.g., besides Morley, also affine P2.  Looking ahead, with `MeshQuad._splitquads`, perhaps quadrilateral meshes too.

**Comment by kinnala** [comment]
Next, one should use Mapping.invF and Element.gbasis, quite similarly as here: 

https://github.com/kinnala/scikit-fem/blob/167ba29e586c1a2efa7246de6518bc109adf4e80/skfem/assembly/global_basis/facet_basis.py#L99

Instead of leaving the different evaluated basis functions separate (as is done in the previous url), we should sum their values similarly as in GlobalBasis.interpolate.

**Comment by gdmcbain** [comment]
Thanks for the tips; I haven't fully understood the machinery here but continuing to scratch around:

```python
ex02.x[ex02.ib.element_dofs[:, 8]]
```
is
> array([ 2.33941283e-04,  2.30040321e-04,  2.55625370e-04,  3.45343932e-04, -2.10424724e-04, -9.12993610e-05])

and
```python
 ex02.x[ex02.ib.element_dofs[:, 8]] @ [ex02.ib.basis[0][i][8] for i in range(ex02.ib.Nbfun)]
```
is
> array([0.00023885, 0.00023825, 0.00025078])

which might be the ordinates at the three quadrature points of the element containing (0.5, 0.5).

I think the first three Morley degrees of freedom are also nodal ordinates which looks about right too.

**Comment by kinnala** [comment]
Yes. I apologize, these parts of the library are not yet fully documented as I wanted to improve the documentation of user-facing parts.

**Comment by gdmcbain** [comment]
> which looks like the local coordinates of the point in the reference element.

Confirming that with a further experiment, computing the local coordinates of a global point in all of the elements and seeing for which it lies in the reference triangle _&xi;_ &ge; 0, _&eta;_ &ge; 0, _&xi;_ + _&eta;_ &le; 1.
```python
from functools import reduce
import numpy as np
import ex02

xieta = ex02.mapp.invF(np.array((.5, .5)).reshape(-1, 1, 1))[:, :, 0]
elements = np.nonzero(reduce(np.logical_and, [xieta[0, :] >= 0, xieta[1, :] >= 0, xieta[0, :] + xieta[1, :] <= 1]))
reduce(np.intersect1d, ex02.m.t[:, elements].T)
```
returns `array([4])` and indeed
```python
ex02.m.p[:, reduce(np.intersect1d, ex02.m.t[:, elements].T)]
```
is `array([[0.5], [0.5]])`.

**Comment by kinnala** [comment]
Yes, it looks like it could work for any triangular element and also could be vectorized to work with multiple points and multiple triangles at once.

I'll consider whether to replace MeshTri.interpolator or do something else.

**Comment by gdmcbain** [comment]
Yes, on that vectorization to multiple elements, I had wanted to pass the elements containing the specified points as the `tind` keyword instead of omitting that, letting it default to all the elements, and then extracting the ones (one) of interest by indexing:

https://github.com/kinnala/scikit-fem/commit/672a50ce429b970b2b5c0a5fbb43179906492299#diff-a4c8fc413d1defaa1a6464dbfbce0f52R64

```python
    psi0 = (np.hstack([element.gbasis(mapping, local_point, k)[0][triangle]
                                for k in range(ib.Nbfun)])
```

but I couldn't work out yet the shape wanted for `tind`.

**Comment by kinnala** [comment]
This is work in progress:
```python
points = np.array([[0.45, 0.78], [0.23, 0.55]]).T
triangulation = Triangulation(mesh.p[0, :], mesh.p[1, :], mesh.t.T)
triangles = triangulation.get_trifinder()(points[:, 0], points[:, 1])
local_point = mapping.invF(points[:, :, np.newaxis], tind=triangles)
```

**Comment by kinnala** [comment]
Maybe this would work:

```python
def interpolator(mesh, basis, dofs):
    from matplotlib.tri import Triangulation
    
    triang = Triangulation(mesh.p[0, :], mesh.p[1, :], mesh.t.T)
    finder = triang.get_trifinder()
    
    def interpfun(x):
        tris = finder(*x)
        pts = basis.mapping.invF(x[:, :, np.newaxis], tind=tris)
        w = np.zeros(x.shape[1])
        for k in range(basis.Nbfun):
            phi = basis.elem.gbasis(basis.mapping, pts, k, tind=tris)
            w += dofs[ib.element_dofs[k, tris]]*phi[0].flatten()
        return w
    
    return interpfun

f = interpolator(mesh, ib, psi)
f(points)
```

**Comment by gdmcbain** [comment]
Thanks for looking into this.

I wonder if the use of [`scipy.spatial.Delaunay`](https://docs.scipy.org/doc/scipy/reference/generated/scipy.spatial.Delaunay.html#scipy.spatial.Delaunay) instead of `matplotlib.tri.Triangulation` would generalize this from `MeshTri` to any simplicial mesh (i.e. really only `MeshTet` but maybe also `MeshLine`).  Would this function then be defined as a method of a mixin `class MeshSimplicial`?

**Comment by gdmcbain** [comment]
```python
points = np.array([[0.45, 0.78], [0.23, 0.55]]).T
triangulation = Triangulation(mesh.p[0, :], mesh.p[1, :], mesh.t.T)
triangles = triangulation.get_trifinder()(points[:, 0], points[:, 1])
local_points = mapping.invF(points[:, :, np.newaxis], tind=triangles)
```
isn't quite right since if given just a single global point, it returns two local points
```python
points = np.array([[0.45], [0.23]]).T
triangles = triangulation.get_trifinder()(points[:, 0], points[:, 1])
mapping.invF(points[:, :, np.newaxis], tind=triangles)
```
returns `[[[-1.59661657], [ 0.94083269]], [[ 2.9832518 ], [ 1.92616944]]]` with shape `(2, 2, 1)`.

**Comment by gdmcbain** [comment]
`function interpolator` doesn't work either.  I'm not sure what shape to pass `points` to pass to it, but it has to be (2, number_of_points), no?

But then (in ex18)
```python
interpolator(mesh, ib, psi)(np.array([[0.], [0.]]))
```
or
```python
interpolator(mesh, ib, psi)(mesh.p[:, :3])
raises
> ValueError: operand has more dimensions than subscripts given in einstein sum, but no '...' ellipsis provided to broadcast the extra dimensions.

This is from the line
```python
phi = basis.elem.gbasis(basis.mapping, pts, k, tind=tris)
```

**Comment by kinnala** [comment]
Oops. I tested this only with subclasses of `ElementH1`. The implementation of `gbasis` is different in `ElementH2` so it should be taken into account.

**Comment by gdmcbain** [comment]
Ah, and `ElementH1.gbasis` doesn't memoize the inverse Vandermonde. #68 

By the way: how do you mark up those tidy quotes from sources as in https://github.com/kinnala/scikit-fem/issues/62#issuecomment-426148068 ?

**Comment by kinnala** [comment]
When you read the source code in Github and mouse over the line number, three dots apper next to it. Pressing that gives you a URL.

**Comment by kinnala** [comment]
> Thanks for looking into this.
> 
> I wonder if the use of [`scipy.spatial.Delaunay`](https://docs.scipy.org/doc/scipy/reference/generated/scipy.spatial.Delaunay.html#scipy.spatial.Delaunay) instead of `matplotlib.tri.Triangulation` would generalize this from `MeshTri` to any simplicial mesh (i.e. really only `MeshTet` but maybe also `MeshLine`). Would this function then be defined as a method of a mixin `class MeshSimplicial`?

In particular, which function do you mean? [Delaunay.find_simplex](https://docs.scipy.org/doc/scipy/reference/generated/scipy.spatial.Delaunay.find_simplex.html#scipy.spatial.Delaunay.find_simplex)?

**Comment by gdmcbain** [comment]
Sorry, `scipy.spatial` was a false lead.  Yes, I was thinking of that method but it only seems to work with the triangulation generated by its own Delaunay class, I couldn't see how to pass in the one in MeshTri.

**Comment by kinnala** [comment]
For triangular meshes, you can now try `InteriorBasis.interpolator`. I'm gonna write some tests for it now.

**Comment by kinnala** [comment]
Ok, there is still some issues. I'm trying to fix them asap.

**Comment by kinnala** [comment]
cc99ad97b335c1698816c19b83fa46dc1683b6f0 should fix interpolating `ElementH2` bases. Support for multiple elements was missing in `MappingAffine.F`.

**Comment by gdmcbain** [comment]
Excellent!  This works now, as demonstrated in #66 for the stream-function in the centre of the cavity in ex18.  Thank you!

**Comment by gdmcbain** [comment]
I note that the new `InteriorBasis.interpolator` works for `ElementTriP2` too.
