### ISSUE TITLE
Twice execution of Example 01 raises Error in IPython (Spyder 4.1.5, Python 3.8)

### ISSUE THREAD

**Issue by adtzlr** [kinnala/scikit-fem#624]
Hi,

executing [Example 01](https://github.com/kinnala/scikit-fem/blob/master/docs/examples/ex01.py) twice in the same IPython-console in Spyder, the plot function raises an Error:

```python
plot(m, x, shading='gouraud', colorbar=True)
```

```python
  File "C:\Users\Andreas\Documents\GitHub\scikit-fem\skfem\visuals\matplotlib.py", line 127, in plot
    raise NotImplementedError("Type {} not supported.".format(type(m)))

NotImplementedError: Type <class 'skfem.mesh.mesh.MeshTri1'> not supported.
```

P.S.: I'm using the master branch from scikit-fem along with Python 3.8 and Spyder 4.1.5 on Win10. Hopefully this is ok to submit if I'm not using the latest pypi-release.

**Comment by kinnala** [comment]
I don't know why this happens but just to clarify: `MeshTri1` is the name of the class and `MeshTri` is an alias. Cannot reproduce this using `python 3.8.3`, `ipython 7.16.1` and NixOS.

**Comment by adtzlr** [comment]
Just for your information: It crashes with both `MeshTri1` and `MeshTri`. Error is raised with latest pypi-release too. It is not a big issue though, I just discovered it while walking through the examples.

**Comment by gdmcbain** [comment]
I have access to a Windows 10 Pro machine for testing.  There inside VS Code 1.55.1, I can start `ipython` 7.19.0 (Python 3.8.8) in the embedded terminal, but I don't know how to run a script inside IPython.  

If I open ex01.py, _Select/Select All_ of it, and then _Terminal/Run Selected Text_, it's sent to the IPython in the embedded terminal and if I hit Enter, it's executed.  I can repeat _Run Selected Text_ without problems.  One unintended consequence of running the contents of the script in this way is that 

https://github.com/kinnala/scikit-fem/blob/6b27580eae635b5961ca7e76dfbe28b2c46f7ddf/docs/examples/ex01.py#L20

saves the figure to `C:\Users\gmcbain\Miniconda3\envs\skfem\Scripts\ipython_solution.png`.

Ah, I see: [`%run`](https://ipython.readthedocs.io/en/stable/interactive/magics.html#magic-run) 
```shell
%run docs/examples/ex01.py
```
(Nice.)  I can run that repeatedly and it generates `docs/examples/ex01_solution.png`, no problem.

**Comment by gdmcbain** [comment]
Maybe Spyder?  Still on Win 10,
```shell
conda create -n spyder spyder scikit-fem -c conda-forge
conda activate spyder
spyder
```
This gives Spyder 5.0.0, Python 3.9.2, scikit-fem 2.4.0, IPython 7.22.0.
```shell
run src/scikit-fem/docs/examples/ex01.py
```
raises 
> ImportError: cannot import name 'laplace' from 'skfem.models'

I think that might be because I'm running the master version 9d18d01819831516119a663949b8dd6e9fffbf1f of ex01 whereas in scikit-fem 2.4.0 `laplace` was in `skfem.models.poisson`.

Quitting Spyder and
```shell
pip install src\scikit-fem
```
and restarting Spyder.  Then ex01 fails with
> ModuleNotFoundError: No module named 'matplotlib'

so in IPython in Spyder
```shell
import sys
!conda install --yes --prefix {sys.prefix} matplotlib 
```
(IPython is handy!)  
```shell
run src/scikit-fem/docs/examples/ex01.py
run src/scikit-fem/docs/examples/ex01.py
run src/scikit-fem/docs/examples/ex01.py
```
No problem.  This displays more and more copies of the plot in one of its subwindows in a _Plots_ tab.

Not sure what to try next, I can't reproduce the problem.

**Comment by kinnala** [comment]
Maybe second run uses different/older scikit-fem for some reason?

**Comment by adtzlr** [comment]
> raises
>
> `ImportError: cannot import name 'laplace' from 'skfem.models'`
>
> I think that might be because I'm running the master version 9d18d01 of ex01 whereas in scikit-fem 2.4.0 laplace was in skfem.models.poisson.

yes, I encountered that too. I added the master version in Spyder by adding the master source directory to the spyder pythonpath manager (tools - PYTHONPATH manager - add path) and uninstalled the pypi-release with `pip` before.

> run src/scikit-fem/docs/examples/ex01.py

> No problem. This displays more and more copies of the plot in one of its subwindows in a Plots tab.
Yes, that's how it should be.

Yeah, I doesn't happen in IPython directly or if i type `run ex01.py` in the Spyder IPython console. Spyder is using a custom command for running a script in its own IPython-console with `runfile()`. I executed the script in Spyder by hitting F5 (that's the default workflow in Spyder for running a script) and in the second run I get that error.

**Comment by gdmcbain** [comment]
Nope, F5 `runfile` works here too.

![image](https://user-images.githubusercontent.com/1588947/114662595-4e2b6f00-9d3c-11eb-8930-6885fec09129.png)

**Comment by adtzlr** [comment]
Then it must be related to my older versions of Spyder 4.x which are shipped with WinPython and Anaconda (I'm using them on different computers running Win10) and I get the error on both computers. Anyway, it seems an updated version of Python + Spyder resolves the issue. Thanks for trying that out!

**Comment by gdmcbain** [comment]
Modifying `PYTHONPATH` sounds fragile.  What about:
```shell
!pip install %userprofile%\src\scikit-fem
```

**Comment by adtzlr** [comment]
> Modifying `PYTHONPATH` sounds fragile. What about:
> 
> ```shell
> !pip install %userprofile%\src\scikit-fem
> ```

Thanks, that finally worked! Should I close this issue? Sorry this "special" kind of issue 😄

**Comment by gdmcbain** [comment]
Sure.  No problem, I'm pleased to have learnt more about IPython and Spyder.  Thank you.
