### ISSUE TITLE
Error using plot with provided axis

### ISSUE THREAD

**Issue by HadrienNU** [kinnala/scikit-fem#626]
When using plot with a provided axis
```
import matplotlib.pyplot as plt
fig, axs = plt.subplots()
plot(basis, x, ax=axs)
```
for a 1D Mesh (hence using MeshLine) , I get the following error

 ```
 File "/usr/local/lib/python3.8/dist-packages/skfem/visuals/matplotlib.py", line 227, in plot_basis
    return plot(*basis.refinterp(z, Nrefs=Nrefs), **kwargs)
  File "/usr/lib/python3.8/functools.py", line 875, in wrapper
    return dispatch(args[0].__class__)(*args, **kw)
  File "/usr/local/lib/python3.8/dist-packages/skfem/visuals/matplotlib.py", line 142, in plot_meshline
    xs.append(s)
UnboundLocalError: local variable 'xs' referenced before assignment
```
The error comes from the following line in visuals.matplotlib (l133 to l140)
```

    if "ax" not in kwargs:
        # create new figure
        fig = plt.figure()
        ax = fig.add_subplot(111)
        xs = []
        ys = []
    else:
        ax = kwargs["ax"]
```

And can be solved by putting the initialization fo xs and ys array outside of the if structure

**Comment by kinnala** [comment]
Thanks for the report!

I'm now AFK, but if you want to try fixing it, you can click "Fork", edit the respective file in the web browser, and then at the main page of your fork click "Submit a pull request".

**Comment by HadrienNU** [comment]
Thanks for the help, I am a bit new on github, the pull request is here, that should fix the error: #627

**Comment by kinnala** [comment]
Great! Check carefully the report of the automated test suite. It runs flake8 and mypy. You probably added extra whitespace which caused the error.

**Comment by HadrienNU** [comment]
Indeed, corrected
