### ISSUE TITLE
Free Electron Galerkin FEM in scikitfem 

### ISSUE THREAD

**Issue by nikosmatsa** [kinnala/scikit-fem#644]
I have the following problem.But I don't know if it is applicable in your module 

https://github.com/nikosmatsa/Finite-Differences-Methods-for-PDE-/blob/main/Free%20Electron%20Galerkin%20FEM%20.ipynb

**Comment by kinnala** [comment]
One comment: support for complex forms was added very recently, you need to pass `dtype` to `BilinearForm`. I think there is no example but there is a test somewhere. See https://github.com/kinnala/scikit-fem/blob/master/skfem/assembly/form/form.py#L26 for the implementation.

**Comment by gdmcbain** [comment]
But is a complex form required here? I see that the bilinear form `a` contains the imaginary factor _&kappa;_ but only as a simple factor. The bilinear form could be redefined without it as real and then the real assembled matrix multiplied by _&kappa;_. 

This is how it was done for the primitive Orr&ndash;Sommerfeld equation in ex29&mdash;a complex equation but only essentially involving real forms multiplied by complex coefficients.

https://github.com/kinnala/scikit-fem/blob/91c6c5b90a0cbf1f4d26213a13f0145aa3d90980/docs/examples/ex29.py#L97-L111

I imagine that intrinsically complex forms are possible but I can't think of an example. Do you have one?

**Comment by kinnala** [comment]
I'm not sure but probably something where you have a complex-valued nonhomogeneous material parameter such as in this example: https://doc.freefem.org/tutorials/complexNumbers.html
