### ISSUE TITLE
instructiveness of first example

### ISSUE THREAD

**Issue by nschloe** [kinnala/scikit-fem#648]
[The first example](https://github.com/kinnala/scikit-fem/blob/master/docs/examples/ex01.py) is not terribly instructive. Laplace is of course a good choice, anyone trying skfem for the first time will want to see trial and test functions, integration and such. `laplace` takes care (hides) all of this nicely, but I'd rather be explicit here and perhaps add a comment that this could be replaced with `laplace()`.

**Comment by kinnala** [comment]
You propose to revert https://github.com/kinnala/scikit-fem/commit/bd7e96d76d2e47ec1d0e1d2a3e8bd26902f5fc86#diff-6bc63290883d79ccbc5c72c4993db153ebe15920560afa84bdcce70122807998

I agree with your reasoning. Maybe also use a more up-to-date way of defining the forms.

**Comment by nschloe** [comment]
> You propose to revert bd7e96d

Indeed!

**Comment by nschloe** [comment]
From my experience, it's also useful to put an example like this in the readme. Like "here's how to install" (one line), "here's how to use it" (code block), and perhaps a plot of the solution. "More examples there and there". Helps everyone to get started quickly.

**Comment by kinnala** [comment]
![ex01_solution](https://user-images.githubusercontent.com/973268/121342616-7d202480-c92a-11eb-965f-c5ef462fbd5c.png)

Here is a figure to be added to the readme.
