### ISSUE TITLE
Mesh initializers don't accept lists

### ISSUE THREAD

**Issue by nschloe** [kinnala/scikit-fem#663]
There is some code to support list inputs, but it doesn't work. MWE:
```python
import skfem


x = [0.0, 1.0]
c = [[]]
mesh = skfem.MeshLine(x, c)
```
```
  File "/path/to/skfem/mesh/mesh.py", line 1282, in __post_init__
    if len(self.doflocs.shape) == 1:
AttributeError: 'list' object has no attribute 'shape'
```

**Comment by gdmcbain** [comment]
Yes, it would be nice from these to act more like NumPy's [array creation routines](https://numpy.org/devdocs/reference/routines.array-creation.html) and what's described in that documentation as `array_like`.  The [gloss](https://numpy.org/devdocs/glossary.html?highlight=array_like#term-array_like) of that isn't technical, but it seems to work well and many users will be used to it.  Now, how does `array_like` work, I haven't looked into it yet&hellip;  I suppose there's already something similar in initializing `meshio.Mesh` that should do the trick.

**Comment by gdmcbain** [comment]
Oh, wow, [`numpy.empty_like`](https://github.com/numpy/numpy/blob/923996a75a75fc5789a7495fcb14e4970e675bc6/numpy/core/multiarray.pyi#L134-L136), for example, uses [`typing.overload`](https://docs.python.org/3/library/typing.html?highlight=typing#typing.overload)

```python
@overload
def empty_like(
    prototype: _ArrayType,
```
I don't know whether we want to go to that length.

**Comment by gdmcbain** [comment]
What should be the interpretation of 
```python
c = [[]]
```
in the MWE?  I'm not sure that meshes with points not included in any cell are valid.

But here using 
```python
mesh = skfem.MeshLine(*map(np.asarray, [x, c]))
```
we get a single line-segment cell from 0 to 1.   That seems odd but I assume is a separate issue.

**Comment by gdmcbain** [comment]
Anyway, [`meshio.Mesh`](https://github.com/nschloe/meshio/blob/6dd053a0d5b0f32a7a7d52a2ba47e951e026471c/src/meshio/_mesh.py#L31) uses [`numpy.asarray`](https://numpy.org/devdocs/reference/generated/numpy.asarray.html#numpy.asarray) for its `points`:
```python
        self.points = np.asarray(points)
```
which has been working pretty well for a while; let's go with that.

**Comment by gdmcbain** [comment]
`MeshLine1.__post_init__` overrides the one inherited from `Mesh`.

**Comment by gdmcbain** [comment]
It's the only subclass of `Mesh` that does and the superclass does have

https://github.com/kinnala/scikit-fem/blob/08628e5f2fab82b3083dbb232c3085f49982c6d6/skfem/mesh/mesh.py#L352-L358

so it's only going to be `MeshLine1` that can't initialize with lists.  I think it might suffice to `super().__post_init__()` there; I'll try that now.

(Is the above just a verbose re-implementation of `asarray`?  I'll try that switching to that too.)

**Comment by gdmcbain** [comment]
With #664 and appending `print(mesh, mesh.p, mesh.t)` to the example, I get:
```
One-dimensional mesh with 2 vertices and 1 elements. [[0. 1.]] [[0]
 [1]]
```
