### ISSUE TITLE
Is the problem statement incorrect for example 13? 

### ISSUE THREAD

**Issue by cottrell** [kinnala/scikit-fem#671]
The problem is stating that the the normal derivative of u on the curved boundaries is zero but I don't see that boundary condition being used anywhere explicitly in the code. Possible it is not needed or I am not understanding something.

https://github.com/kinnala/scikit-fem/blob/master/docs/examples/ex13.py#L64

**Comment by kinnala** [comment]
The boundary condition du/dn = 0, aka the Neumann condition, is implicit and automatic for this variational formulation.

**Comment by cottrell** [comment]
> The boundary condition du/dn = 0, aka the Neumann condition, is implicit and automatic for this variational formulation.

Yes, but is there an example of how to set non-zero Neumann conditions elsewhere? I have not found it yet. 

Maybe the assumption is you always transform to zero Neumann so you *never* need to implement the boundary derivative conditions?

If you have arbitrary derivative conditions on the boundary, I can't remember if that is always a trivial task to simply have some polynomial term in the solution and then let the mesh handle the rest.

**Comment by cottrell** [comment]
Ok, I think I remember that you can typically add some term that might or might not be in the null space of your differential operator. If not you carry some complexity into the forms.

**Comment by gdmcbain** [comment]
For the integration by parts, see, e. g. https://en.wikipedia.org/wiki/Finite_element_method#The_weak_form_of_P1.
