### ISSUE TITLE
ElementLineDG

### ISSUE THREAD

**Issue by gdmcbain** [kinnala/scikit-fem#675]
Like [`ElementQuadDG`](https://github.com/kinnala/scikit-fem/blob/ad43d009c77e8e5694515a6d9e6bdd82b190ca2c/skfem/element/element_quad/element_quad_dg.py#L5) and [`ElementTriDG`](https://github.com/kinnala/scikit-fem/blob/d08af2a3f4607e28023656b1b6ad025b1a530aa1/skfem/element/element_tri/element_tri_dg.py#L5), but one-dimensional.

**Comment by kinnala** [comment]
This is actually now taken care of in #792 by introducing a generic `ElementDG` which works for all elements. My PR's are always subject to scope creep it seems.

**Comment by gdmcbain** [comment]
Great, I love dimension-independent finite-element implementations!

I might think about revisiting one-dimensional plotting #676 to make it less of a special case.

**Comment by kinnala** [comment]
> I might think about revisiting one-dimensional plotting #676 to make it less of a special case.

Good idea.

> Great, I love dimension-independent finite-element implementations!

I think if you wanted to calculate with 4D finite elements it would be as simple as first implementing `ElementHypertet1` with basis {x, y, z, w, 1 - x - y - w} and then `Mesh(points, cells, elem=ElementHypertet1, affine=True)` and doing some trivial extensions to `MappingAffine`.
