### ISSUE TITLE
from_meshio fails on old ex27

### ISSUE THREAD

**Issue by gdmcbain** [kinnala/scikit-fem#691]
I was trying to regenerate a mesh for ex27 as part of the discussion with @bhaveshshrimali on the speed of pypardiso relative to `scipy.sparse` in #690 so that the number of elements could be varied but the old `make_mesh(make_geom(...))` code seems not to work with the new (#680 ?) `skfem.io.mesh.from_meshio`.

The code:
```python
from skfem import *
from skfem.io.meshio import from_meshio

from itertools import cycle, islice

import numpy as np

from pygmsh import generate_mesh
from pygmsh.built_in import Geometry


def make_geom(length: float, lcar: float) -> Geometry:
    # Barkley et al (2002, figure 3 a - c)
    geom = Geometry()

    points = []
    for point in [
        [0, -1, 0],
        [length, -1, 0],
        [length, 1, 0],
        [-1, 1, 0],
        [-1, 0, 0],
        [0, 0, 0],
    ]:
        points.append(geom.add_point(point, lcar))

    lines = []
    for termini in zip(points, islice(cycle(points), 1, None)):
        lines.append(geom.add_line(*termini))

    for k, label in [
        ([1], "outlet"),
        ([2], "ceiling"),
        ([3], "inlet"),
        ([0, 4, 5], "floor"),
    ]:
        geom.add_physical(list(np.array(lines)[k]), label)

    geom.add_physical(geom.add_plane_surface(geom.add_line_loop(lines)), "domain")

    return geom


if __name__ == "__main__":
    from pathlib import Path

    geom = make_geom(35.0, 0.2)

    with open(Path(__file__).with_suffix(".geo"), "w") as fgeo:
        fgeo.write(geom.get_code())

    mio = generate_mesh(geom, dim=2)
    print(mio)

    mesh = from_meshio(mio)
    print(mesh)

    mesh.save(Path(__file__).with_suffix(".vtk"))
```

When I run this with pygmsh==6.1.1 (before the big API change in pygmsh 7), I believe that this generates a valid `*.geo` file, which is accepted by Gmsh (4.8.4 here) and Gmsh can write this as MSH 4.1 file which is understood by meshio, but something goes wrong in `skfem.io.meshio.from_meshio`:
```
Traceback (most recent call last):
  File "/home/gdmcbain/src/scikit-fem/docs/examples/ex27_mesh.py", line 55, in <module>
    mesh = from_meshio(mio)
  File "/home/gdmcbain/miniconda3/envs/skfem/lib/python3.9/site-packages/skfem/io/meshio.py", line 93, in from_meshio
    facets = {k: [tuple(f) for f in
  File "/home/gdmcbain/miniconda3/envs/skfem/lib/python3.9/site-packages/skfem/io/meshio.py", line 94, in <dictcomp>
    np.sort(m.cells_dict[bnd_type][v[bnd_type]])]
IndexError: index 381 is out of bounds for axis 0 with size 380
```

I don't mean to suggest that we should rely upon `pygmsh<7` but I believe the GEO and MSH 4.1 files are valid, as is the `meshio.Mesh`, but I'll check.

The intermediate files are generated and interrogated with
```shell
python docs/examples/ex27_mesh.py  # say, depending on where the above is saved
gmsh -2 docs/examples/ex27_mesh.geo
meshio info docs/examples/ex27_mesh.msh
```

**Comment by bhaveshshrimali** [comment]
Hmmm. this runs fine for me.

```python3
if __name__ == "__main__":
    from pathlib import Path

    geom = make_geom(35.0, 0.2)

    with open(Path(__file__).with_suffix(".geo"), "w") as fgeo:
        fgeo.write(geom.get_code())

    mio = generate_mesh(geom, dim=2)
    print(f"meshio: {mio}")

    mesh = from_meshio(mio)
    print(f"scikit-fem: {mesh}")

    mesh.save(Path(__file__).with_suffix(".vtk"))
```

```terminal
Info    : Running 'gmsh -2 C:\Users\bshri\AppData\Local\Temp\tmpyyrojl4v.geo -format msh -bin -o C:\Users\bshri\AppData\Local\Temp\tmpqwcqah75.msh' [Gmsh 4.8.3, 1 node, max. 1 thread]
Info    : Started on Wed Aug 18 11:10:08 2021
Info    : Reading 'C:\Users\bshri\AppData\Local\Temp\tmpyyrojl4v.geo'...  
Info    : Done reading 'C:\Users\bshri\AppData\Local\Temp\tmpyyrojl4v.geo'
Info    : Meshing 1D...
Info    : [  0%] Meshing curve 1 (Line)
Info    : [ 20%] Meshing curve 2 (Line)
Info    : [ 40%] Meshing curve 3 (Line)
Info    : [ 50%] Meshing curve 4 (Line)
Info    : [ 70%] Meshing curve 5 (Line)
Info    : [ 90%] Meshing curve 6 (Line)
Info    : Done meshing 1D (Wall 0.00199914s, CPU 0s)
Info    : Meshing 2D...
Info    : Meshing surface 8 (Plane, Frontal-Delaunay)
Info    : Done meshing 2D (Wall 1.52614s, CPU 1.48438s)
Info    : 33772 nodes 67548 elements
Info    : Writing 'C:\Users\bshri\AppData\Local\Temp\tmpqwcqah75.msh'...
Info    : Done writing 'C:\Users\bshri\AppData\Local\Temp\tmpqwcqah75.msh'
Info    : Stopped on Wed Aug 18 11:10:09 2021 (From start: Wall 1.57989s, CPU 1.54688s)
meshio: <meshio mesh object>
  Number of points: 33772
  Number of cells:
    line: 700
    line: 40
    line: 720
    line: 20
    line: 20
    line: 20
    triangle: 66022
  Cell sets: outlet, ceiling, inlet, floor, domain, gmsh:bounding_entities
  Point data: gmsh:dim_tags
  Cell data: gmsh:physical, gmsh:geometrical
  Field data: outlet, ceiling, inlet, floor, domain
scikit-fem: Triangular mesh with 33772 vertices and 66022 elements.
WARNING:root:VTK requires 3D points, but 2D points given. Appending 0 third component.

```

**Comment by gdmcbain** [comment]
Oh, O. K., great.  (I wonder what's going on here, but I'll sort that out later.)  You should be able to change `lcar`, the second argument to `make_geom`, to get meshes of different fineness to experiment with in #690.

Are you running on scikit-fem master, i.e. with #680?  There were some substantial changes to `skfem.io.meshio.from_meshio` in that which I don't know have been published as a release.

**Comment by bhaveshshrimali** [comment]
Thanks for the meshing code. 

> Are you running on scikit-fem master, i.e. with #680? There were some substantial changes to `skfem.io.meshio.from_meshio` in that which I don't know have been published as a release.

Nope, right now on `3.2.0`. Will try it out with master later today.

**Comment by gdmcbain** [comment]
Yeah, I suspect a regression in #680.  I'll `git bisect`.

**Comment by kinnala** [comment]
Can you give an example `meshio.Mesh` which fails without running `pygmsh`? E.g., save this `mio` object using `mio.write(...)`.

**Comment by gdmcbain** [comment]
Yes.   Insert
```python
    mio.write(Path(__file__).with_suffix(".msh"), file_format="gmsh22", binary=False)
```
then
```python
m = from_file("docs/examples/ex27_mesh.msh", out={})
```
gives
> Triangular mesh with 2300 vertices and 4218 elements.

with subdomains and boundaries.

**Comment by kinnala** [comment]
So it works when loading from a file?

**Comment by gdmcbain** [comment]
Well yes but not necessarily the same file.  That second file was MSH 2.2 whereas Gmsh (called internally by pygmsh<7) would have generated MSH 4.1 and I didn't dare write that with meshio.

**Comment by kinnala** [comment]
The differences to the earlier implementation are not huge, but I think the relevant detail is that the line which now fails was moved outside of the `try` block. I thought this part of the code cannot fail but I was proven wrong.

**Comment by kinnala** [comment]
Again something strange going on with `cell_sets` it seems.

**Comment by kinnala** [comment]
Can you give information about `meshio` version also? Could be important.

**Comment by gdmcbain** [comment]
`pip list | grep meshio` says 4.4.6, but I generally `pip install ~/src/meshio` on some snapshot of main.  Might be b3630c2d8d7649b14d26665ca75679258b6fc483.

**Comment by gdmcbain** [comment]
Aargh, I just did
```shell
cd ~/src/meshio
git checkout main
git pull upstream main
pip install .
```
and got hit with
```
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
pygmsh 6.1.1 requires meshio<5,>=4, but you have meshio 5.0.0 which is incompatible.
```
Then retrying `pip install pygmsh\<7` uninstalls meshio-5.0.0 and gives me back meshio-4.4.6.

So it looks like I have pygmsh==6.1.1 and meshio==4.4.6.

I am very unhappy about these forced movements in pygmsh and meshio.

**Comment by gdmcbain** [comment]
So to avoid pygmsh, here's the equivalent GEO code: 

```c++
length = 35.0;

Point(1) = {0, -1, 0, 1.0};
Point(2) = {length, -1, 0, 1.0};
Point(3) = {length, 1, 0, 1.0};
Point(4) = {-1, 1, 0, 1.0};
Point(5) = {-1, 0, 0, 1.0};
Point(6) = {0, 0, 0, 1.0};

Line(1) = {1, 2};
Line(2) = {2, 3};
Line(3) = {3, 4};
Line(4) = {4, 5};
Line(5) = {5, 6};
Line(6) = {6, 1};

Curve Loop(1) = {3, 4, 5, 6, 1, 2};
Plane Surface(1) = {1};

Physical Surface("domain", 7) = {1};

Physical Curve("outlet", 8) = {2};
Physical Curve("ceiling", 9) = {3};
Physical Curve("inlet", 10) = {4};
Physical Curve("floor", 11) = {5, 6, 1};
```

After installing Gmsh (e.g. `pip install gmsh`), run this with
```bash
gmsh -2 -clscale 0.125 -format msh41 -o bfs41.msh bfs.geo
gmsh -2 -clscale 0.125 -format msh22 -o bfs22.msh bfs.geo
```
to get two mesh files in formats MSH 4.1 and 22, both ASCII, with 5647 nodes.  Reduce the `-clscale` number to get more.

Here are the GEO and meshes:
* [bfs.zip](https://github.com/kinnala/scikit-fem/files/7019475/bfs.zip)

I have git-pulled and pip-installed the current meshio main (5.0.0) and then `from_file(msh, [])` does work with both, producing seemingly identical MeshTri1's with subdomain and boundaries.

So maybe there's nothing to worry about here?

**Comment by gdmcbain** [comment]
But then with `-clscale 0.2` 
```shell
gmsh -2 -clscale 0.2 -format msh41 -o bfs41.msh bfs.geo
```

to match the old example (saved in `docs/examples/meshes/backward-facing_step.json` with 2302 vertices), now having 2300 vertices, the `IndexError` is raised, even though the mesh looks O. K. and meshio is happy with it.

If this clscale is generated in MSH 2.2
```shell
gmsh -2 -clscale 0.2 -format msh22 -o bfs22.msh bfs.geo
```
it does work.

Further, 
```python
meshio.write("bfs41_22.msh", meshio.read("bfs41.msh"), file_format="gmsh22", binary=False)
skfem.io.meshio.from_file("bfs41_22.msh", [])
```
works too.

But it doesn't really work since using it in ex27 #690 diverges!
```

||F(u)|| = 3.687950e+00
||F(u)|| = 1.489416e+01
||F(u)|| = 1.781031e+01
||F(u)|| = 1.989103e+01
||F(u)|| = 2.295013e+01
||F(u)|| = 2.532056e+01
No convergence for initial step.
Traceback (most recent call last):
  File "/home/gdmcbain/src/scikit-fem/docs/examples/ex27.py", line 269, in <module>
    natural(bfs, bfs.make_vector(), 0.,
  File "/home/gdmcbain/miniconda3/envs/skfem/lib/python3.9/site-packages/pacopy/natural.py", line 62, in natural
    raise e
  File "/home/gdmcbain/miniconda3/envs/skfem/lib/python3.9/site-packages/pacopy/natural.py", line 52, in natural
    u, _ = newton(
  File "/home/gdmcbain/miniconda3/envs/skfem/lib/python3.9/site-packages/pacopy/newton.py", line 31, in newton
    raise NewtonConvergenceError(
pacopy.newton.NewtonConvergenceError: Newton's method didn't converge after 5 steps.
```
(And this is the same using pardiso or not.)

So something's not quite right, but is it my GEO, Gmsh, meshio, or scikit-fem?...  And I still can't generate new finer meshes for to test pardiso #690 on ex27.

**Comment by gdmcbain** [comment]
Leaving Gmsh out of it for the moment, I tried taking the existing JSON file and putting it through `to_meshio(from_meshio(...))`.  This permutes the three arrays in `.boundaries` but doesn't that doesn't bother ex27; it converges just fine.  I don't think there's any other difference in the `skfem.Mesh` after the round-trip.

```python
mesh_path = Path(__file__).with_name("backward-facing_step.json")
mesh = skfem.io.json.from_file(mesh_path)

mio = skfem.io.meshio.to_meshio(mesh)
mesh1 = skfem.io.meshio.from_meshio(mio)

for k in mesh.boundaries:
    assert not np.array_equal(
        mesh.boundaries[k], mesh1.boundaries[k]
    ) and np.array_equal(mesh.boundaries[k], np.sort(mesh1.boundaries[k]))
```

**Comment by gdmcbain** [comment]
I've stepped through `from_meshio` with the MSH 4.1 file generated by the `bfs.geo` above and the culprit raising the `IndexError` at

https://github.com/kinnala/scikit-fem/blob/e4a4b2b87072ece9cd386fb83d67adff54031ff5/skfem/io/meshio.py#L93-L96

is `m.cell_sets_dict["gmsh:bounding_entitles"]`.  This peculiar cell-set is something that was added later to the meshio MSH 4.1 reader.  I don't really know what it's for, but in this example we have 370 lines (`m.cells_dict["line"].shape == (370, 2)`) but there is a 371 in the culprit: `m.cell_sets_dict["gmsh:bounding_entities"]["line"]` is

> array([  1,  -2, 178, 171, 359, 350, 365, 354, 371, 364], dtype=int32)

Hence the `IndexError`.

**Comment by gdmcbain** [comment]
Can we just ignore any cell-set starting with "gmsh:"?  As in ff83c84.  If so, and ex27.py reads with 

```python
        self.mesh = skfem.io.meshio.from_file(Path(__file__).parent / "meshes" / "backward-facing_step.msh", [])
```
the example works again (and it's easier to generate meshes with different sizes, and the file is slightly smaller&mdash;;180 v. 196K for the old JSON).

**Comment by gdmcbain** [comment]
Recoding the MSH 4.1 from Gmsh with `skfem.Mesh.load("bfs.msh").save("bfs.vtu")` is considerably smaller: 84 K.  Perhaps VTU is a good choice for examples for which we need to store the mesh statically?  It doesn't rely on optional heavy libraries like h5py like XDMF or NetCDF4 like Exodus and can be viewed in ParaView.

**Comment by gdmcbain** [comment]
I'm not sure why this error didn't show up earlier.  I couldn't see anything in #680 that would have triggered it.  Maybe we were just lucky before and the spurious `"gmsh:bounding_entities"` were imbibed but happened not to contain invalid indices and so didn't raise the `IndexError` and were carried around as worthless but harmless ballast?
