### ISSUE TITLE
Assembling forms with internal variables

### ISSUE THREAD

**Issue by bhaveshshrimali** [kinnala/scikit-fem#729]
I am trying to implement a rubber-viscoelastic model in `scikit-fem`. This can be thought of as an extension of hyperelasticity (ex36) but now with internal variables at each quadrature point. Physically, this would correspond to dissipative phenomena with history dependence such as plasticity, viscoelasticity, viscoplasticity. With a `DiscreteField` object, I feel this should be straightforward, namely 

```python3
@njit(cache=True, nogil=True, parallel=True)
def F1(dv, du, p, Cv):
    out = np.zeros_like(du[0, 0])
    F = np.zeros_like(du)
    for a in prange(du.shape[2]):
        for b in prange(du.shape[3]):
            F[0, 0, a, b] += 1.
            F[1, 1, a, b] += 1.
            F[2, 2, a, b] += 1.
    
    F += du
    Finv, J = vinv(F)
    Cvinv, _ = vinv(Cv)
    FCviv = np.zeros_like(Cvinv)
    for i in range(F.shape[0]):
        for j in range(F.shape[1]):
            for k in range(F.shape[0]):
                for a in prange(F.shape[-2]):
                    for b in prange(F.shape[-1]):
                        FCviv[i, j, a, b] += F[i, k, a, b] * Cvinv[k, j, a, b]

    for i in range(du.shape[0]):
        for j in range(du.shape[1]):
            for a in prange(J.shape[0]):
                for b in prange(J.shape[1]):
                    out[a,b] += (
                        mu * F[i, j, a, b] + p[a,b] * J[a,b] * Finv[j, i, a, b] + nu * FCviv[i, j, a, b]
                    ) * dv[i, j, a, b]
    return out
.....
.....
@LinearForm(nthreads=0)
def a1(v, w):
    return F1(*(grad(v), grad(w["disp"]), w["press"].value, w["Cv"].value))

....
....
asm(a1, basis["u"], disp=uv, press = pv, Cv=Cv)

```

Here `Cv` is a numpy array of shape like `du` (in this case `3, 3, num_elems, num_quad_points`) which can be updated at each time step at quadrature point by some update rule. 

Am I thinking this correctly? Or is there something that I am missing. I will test things tomorrow. The complete code is quite long. Let me see if I can shorten it up a bit to illustrate the main points. 

I'll also put together a non-numba version as the code above is excessively convoluted.

**Comment by gdmcbain** [comment]
> Am I thinking this correctly? Or is there something that I am missing. 

I think this is correct.  This is the kind of thing that I was learning about back in #24, which led to [ex16 &lsquo;Legendre's equation&rsquo;](https://scikit-fem.readthedocs.io/en/latest/listofexamples.html#example-16-legendre-s-equation).

A recent update is that the coefficients no longer need to be interpolated onto the absciss&aelig; before passing to the assembler, in case that helps. #697

**Comment by bhaveshshrimali** [comment]
Perfect, thanks @gdmcbain !!

I'll be back on this tomorrow.
