### ISSUE TITLE
quickly parameter-dependent assembly

### ISSUE THREAD

**Issue by AnyWayOne** [kinnala/scikit-fem#731]
I wonder is it possible to implement quickly parameter-dependent assembly, e.g. the problem $-\triangledown(k(p)\triangledown(u))=1$, where $k(p)$ is a  function related to the parameter $p$.
A normal implementation is:
##############
mesh = Mesh...
Vh = Basis...
@BilinearForm
def a(u,v,w);
     return dot(w['kp']*grad(u), grad(v))
for k_p_i in k_p:
     A_i = a.assemble(Vh, kp = Vh.interpolate(k_p_i))
####################
$A_i \in R^{n \times n}$
By using a loop, it executes n_p (the number of the samplr of the parameter $p$) assemblys, but it's too time consuming for a large $n_p$.
Is it possible to implement above loop efficiently at once and to obtain a tensor $A \in R^{n \times n \times n_p}$?
Thanks for any answer.

**Comment by kinnala** [comment]
There is no command to do them all at once. Technically it would be possible to have a "TrilinearForm" to assemble 3-tensors and then do multiple contractions to 2-tensors. However, I think the limitation is that there is no efficient data structure available for such sparse 3-tensors that would be suitable for FE assembly.

One thing you could try is using Dask (and dask.bag) to parallelize the for-loop. Those computations do not depend on one another so if you have n_p computers, it should be pretty quick.
