### ISSUE TITLE
Singular matrix when mesh contains points not used by cells.

### ISSUE THREAD

**Issue by gatling-nrl** [kinnala/scikit-fem#762]
Expected behavior is that these points would be ignored (as is the case in other packages, e.g. SfePy, dolfinx).
Observed behavior is assembly of a singular matrix and failure to solve.

Minimum code to reproduce is below, with one line to add/not add the offending point.
You can inspect `mesh.points` and `mesh.cells_dict['lines']` and `mesh.cells_dict['triangles']` to see this point is in the points array but not used by any line or trinagle.
```python
import gmsh
import meshio
import skfem
from skfem.helpers import dot, grad
from skfem.io.meshio import from_meshio

lc0 = .25
p_center = [.1234, .5678]
gmsh.initialize()
try:
    gmsh.model.add('mesh')
    # Define unit square area
    # Corners
    bottom_left = gmsh.model.geo.addPoint(0, 0, 0, lc0)
    bottom_right = gmsh.model.geo.addPoint(1, 0, 0, lc0)
    top_right = gmsh.model.geo.addPoint(1, 1, 0, lc0)
    top_left = gmsh.model.geo.addPoint(0, 1, 0, lc0)
    # Edges
    bottom = gmsh.model.geo.addLine(bottom_left, bottom_right)
    right = gmsh.model.geo.addLine(bottom_right, top_right)
    top = gmsh.model.geo.addLine(top_right, top_left)
    left = gmsh.model.geo.addLine(top_left, bottom_left)
    # Surface
    perimeter = gmsh.model.geo.addCurveLoop([bottom, right, top, left])
    surface = gmsh.model.geo.addPlaneSurface([perimeter])
#
#
# comment out the following line to remove the offending point
# and clear the warnings/failure 
#
    gmsh.model.geo.add_point(p_center[0], p_center[1], 0, lc0)
#
#
#
    gmsh.model.geo.synchronize()
    gmsh.model.mesh.generate(dim=2)
    gmsh.write('demo.msh')
finally:
    gmsh.finalize()

mesh = meshio.read('demo.msh')
fem_mesh = from_meshio(mesh)
basis = skfem.Basis(fem_mesh, skfem.ElementTriP1())

@skfem.BilinearForm
def laplace(u, v, _):
    return dot(grad(u), grad(v))

@skfem.LinearForm
def rhs(v, _):
    return 1.0 * v

A = laplace.assemble(basis)
b = rhs.assemble(basis)

D = fem_mesh.boundary_nodes()
A,b = skfem.enforce(A, b, D=D)  # warning generated here:
# site-packages\scipy\sparse\_index.py:125: SparseEfficiencyWarning: Changing the
# sparsity structure of a csr_matrix is expensive. lil_matrix is more efficient.
#    self._set_arrayXarray(i, j, x)
#

x = skfem.solve(A, b)  # another warning generated here:
# site-packages\scipy\sparse\linalg\dsolve\linsolve.py:206: MatrixRankWarning:
# Matrix is exactly singular
#    warn("Matrix is exactly singular", MatrixRankWarning)
```

**Comment by gdmcbain** [comment]
>>   i always include a timestamp in the log-message.

> What kind of logging messages you propose that we add?

My answer was almost exactly anticipated: 

> I wonder if we should add something like `Starting to assemble linear system` and `Starting to initialize CellBasis` at DEBUG level to get easy access to time stamps and get a quick look at how long different parts of the examples took?

Except that I want access to that without ever carrying out expensive checks and I don't think of logging the completion of stages as debugging.  This kind of timestamping of key stages is routine (I.e. on by default) in big simulation packages like OpenFOAM. The aims of scikit-fem are different but after one builds a successful prototype in scikit-fem the question is sometimes whether to then port it to a big package or whether scikit-fem is fine.

**Comment by kinnala** [comment]
Alright, so assembly begin/end would go to INFO level and checks that cut performance go to DEBUG level. I'll update #767 accordingly and add some comments about logging use.

**Comment by gatling-nrl** [comment]
I propose this convention, trying to keep a space for adding verbose debugging messages if they exist already or are ever needed:

- CRITICAL (50): unusued
- ERROR (40): messages during unhandled exceptions (if any)
- WARNING (30): cheap checks to help the user not make mistakes
- INFO (20): timestamps and any other insightful info about execution
- (15):  expensive checks to help the user not make mistakes
 -DEBUG (10): skfem debugging messages (if any)

**Comment by kinnala** [comment]
> I propose this convention, trying to keep a space for adding verbose debugging messages if they exist already or are ever needed:

I see your intention here and tried it out but I don't foresee using internal debugging messages. If I wanted to use them at some point I can use `level=5`. Also that level name "Level 15" printed by `logging` is not very descriptive I think.

Nevertheless, I added some info messages to #767 for calls that typically take some time such as `Basis` initialization, calls to `Form.assemble` and `solve`. I'll squash and merge tomorrow unless there is any objections by then.

**Comment by gatling-nrl** [comment]
Thanks @kinnala... you adding this feature keeps saving me from myself :)

![image](https://user-images.githubusercontent.com/38136423/151217241-dc7c2e15-50ff-4021-bd6e-3d07f7440f8b.png)
