### ISSUE TITLE
DofsView doesn't call __array__ when used as the index of an ndarray

### ISSUE THREAD

**Issue by gatling-nrl** [kinnala/scikit-fem#780]
I can't figure out why, but because `DofsView` inherits from `NamedTuple` it never calls `__array__` and so `u[dv]` fails. The workaround is `u[dv.flatten()]` or to call it yourself as in `u[dv.__array__()]`  (obviously, since all `__array__` does right now is call `flatten()`).

**Comment by kinnala** [comment]
Thanks, I can look into it.

**Comment by kinnala** [comment]
Changing `DofsView` to dataclass seems to fix the issue. I'll do a PR soon.

**Comment by gdmcbain** [comment]
Should this mean that in #776 I could drop the `.all()` from the following?

https://github.com/kinnala/scikit-fem/blob/9ee89bac51620fad4b3dffdfa4eda78dda9acc39/docs/examples/ex13.py#L44

But I don't seem to be able to. With
```python
u[basis.get_dofs("positive")] = 1.
```
I get
```

Traceback (most recent call last):
  File "/home/gdmcbain/src/scikit-fem/docs/examples/ex13.py", line 44, in <module>
    u[basis.get_dofs("positive")] = 1.
IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices
```
