### ISSUE TITLE
behavior of basis.get_dofs() without arguments

### ISSUE THREAD

**Issue by gatling-nrl** [kinnala/scikit-fem#781]
Current behavior of `basis.get_dofs()` seems to return the boundary of the mesh. But now that we've added the `facets` and `elements` keywords it seems counter-intuitive... like, either it should return nothing or everything or maybe raise an exception. Is there a good argument for a default filter?

We've ad hoc added some functionality to `get_dofs()` and I think its going a good direction but it also seems like an important enough function that continuing this organic growth might be a bad idea.

**Comment by kinnala** [comment]
I don't see any issue here, moving to discussions.

Personally I use get_dofs most of the time without arguments so the default behavior is very important in my daily work.
