### ISSUE TITLE
basis.zeros_like()

### ISSUE THREAD

**Issue by gatling-nrl** [kinnala/scikit-fem#783]
I propose changing `basis.zeros()` and `basis.zeros_w()` to `basis.zeros_like(s)` where `s` is a string specifying the shape of the zero array. Possibilities for `s` could be `{'elements', 'dofs',  ...}`.  (I'm sure I got the strings wrong, but you get the idea.) It would a consistent, expandable, and easy to document way to get various shapes of initialized arrays.

This proposal comes from me not being able to figure out how to do `basis.zeros_like('elements')` except to use `np.zeros(basis.nelems)` which is okay, but since there's already a `basis.zeros()` shouldn't it be able to do that for me?

@gdmcbain My actual goal is very analogous to

https://github.com/kinnala/scikit-fem/blob/08a695dc46bb6801b51c45bafd35d86b9b87b8cd/docs/examples/ex17.py#L56

But I opened this issue because plotting my `conductivity` with (for example) `plt.tripcolor(... ,facecolors=conductivity)` didn't work and felt I needed to verify that `conductivity` was in the right places.

I don't know how to ref a future issue, but this is directly tied into the next one I'll open in a few minutes :)

I know the needs of the assembler/solver don't exactly overlap with the needs of the plotter... but in user-land, as much as possible, it would be nice not to have to care about that and still be sure you were giving the assembler the right info in the right coordinates.

**Comment by kinnala** [comment]
Let us continue this in #786.
