### ISSUE TITLE
basis.get_elements()

### ISSUE THREAD

**Issue by gatling-nrl** [kinnala/scikit-fem#784]
Now that `basis.get_dofs()` is coming along.... can we add `basis.get_elements()`

The use case is 

https://github.com/kinnala/scikit-fem/blob/08a695dc46bb6801b51c45bafd35d86b9b87b8cd/docs/examples/ex17.py#L56-L58

But what if I don't have labeled subdomains?

I propose that we could

```python
sigma = basis.zeros_like('elements')
copper_area = basis.get_elements(lambda x: x[0] < 0.5)
sigma[copper_area] = 5.96e7 # S/m
```

with a function very similar to `get_dofs`.

This `sigma` is easily plotted with `matplotlib.pyplot.tripcolor(..., facecolors=sigma)`, but can it be passed to the `Forms`? Is it easy to use as the coefficient for Laplace equation?

**Comment by kinnala** [comment]
I feel this is a bit hacky though. zeros_w is not really needed anymore but I don't feel zeros_like is needed either.

You should initialize another Basis with ElementTriP0 (piecewise constant function) and then zeros will give you the correct shape. There is Mesh.elements_satisfying so the second step already exists.

If you want to use sigma inside a form, then you make sure both Basis objects have the same number of integration points. Easiest way is to initialize the P0 basis like basis0=basis.with_element(ElementTriP0()). Then you can simply call basis0.interpolate(sigma) and pass the resulting object to assemble as a kwarg.
