### ISSUE TITLE
skfem.visuals.matplotlib.draw doesn't support a color keyword.

### ISSUE THREAD

**Issue by gatling-nrl** [kinnala/scikit-fem#814]
```python
skfem.visuals.matplotlib.draw(mesh, color='w', ax=plt.gca())
```
would be extremely helpful for overlaying the mesh on something where black lines don't provide sufficient contrast.

**Comment by kinnala** [comment]
What happens if you do edgecolors='k'? I think it was broken at some point.

**Comment by gatling-nrl** [comment]
`edgecolors='w'` doesn't change the color or raise an exception.  (In fact, invalid kwargs never raise an exception when passed to `draw`.)

**Comment by gdmcbain** [comment]
This looks like the culprit:

https://github.com/kinnala/scikit-fem/blob/fbd2558b9a20c635159737954c81a42687144486/skfem/visuals/matplotlib.py#L39-L40

`edgecolors` is hardcoded, ignoring the kwargs.

**Comment by gdmcbain** [comment]
I mean `edgecolor`; that'll be an issue too, once passing on the kwargs, possibly enhanced by defaults like `{"edgecolor": "k"}` is arranged for.

**Comment by kinnala** [comment]
Sorry I meant this one in plot: https://github.com/kinnala/scikit-fem/blob/fbd2558b9a20c635159737954c81a42687144486/skfem/visuals/matplotlib.py#L193

Does it have any effect?

**Comment by kinnala** [comment]
> Sorry I meant this one in plot:
> 
> https://github.com/kinnala/scikit-fem/blob/fbd2558b9a20c635159737954c81a42687144486/skfem/visuals/matplotlib.py#L193
> 
> Does it have any effect?

This is not a good idea it seems. It will interfere with `nrefs` and also `shading`.

**Comment by kinnala** [comment]
> This looks like the culprit:
> 
> https://github.com/kinnala/scikit-fem/blob/fbd2558b9a20c635159737954c81a42687144486/skfem/visuals/matplotlib.py#L39-L40
> 
> `edgecolors` is hardcoded, ignoring the kwargs.

Reading `edgecolor` from `kwargs` will fix this, right?
