### ISSUE TITLE
FacetBasis(..., facets=) raises IndexError

### ISSUE THREAD

**Issue by gatling-nrl** [kinnala/scikit-fem#818]
```python
def is_outer_boundary(x):
    return np.logical_or(
        np.isclose(abs(x[0]-.5), .5),
        np.isclose(abs(x[1]-.5), .5),
    )

mesh = skfem.MeshTri().refined(1)
basis_p1 = skfem.Basis(mesh, skfem.ElementTriP1())
basis_p1.get_dofs(facets=is_outer_boundary)  # no exception here
fbasis_p1 = skfem.FacetBasis(mesh, basis_p1.elem, facets=is_outer_boundary)
```

```
\scikit-fem\skfem\assembly\basis\boundary_facet_basis.py in __init__(self, mesh, elem, mapping, intorder, quadrature, facets, _side, dofs)
     69         else:
     70             self.find = facets
---> 71         self.tind = self.mesh.f2t[_side, self.find]
     72         self._side = _side  # for debugging
     73 

IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices
```

**Comment by kinnala** [comment]
I think facets must be an array of facet indices, so you must do facets=mesh.facets_satisfying(is_outer_boundary)). You think it should support Callable?

**Comment by gatling-nrl** [comment]
Hmmm. You have me in a bind.  If I look from the inside out, I see why it is how it is. But if I think as a user, from the outside in, the inconsistency makes no sense.

`get_dofs()` is already scary complicated. Documenting and testing functions as powerful and flexible as that one is hard to do...  and I tend to favor "one thing in, one thing out" as a rule....

On the other hand, clean and consistent abstractions make it so, so, so much easier to code without having to constantly look up docs/source.

I suppose I vote that `(..., facets=*)` should support the same interface, wherever it is encontered. Ditto for `(..., elements=*)`.

And I discovered when writing the extended doc draft that `(..., facets=*)` makes zero sense for `P0`.  But it doesn't raise an exception explaining that.  So I would also nominate an issue for fixing the exceptions that are raised when you supply `(..., facets=*)`  or `(..., elements=*)` in a context that makes no sense.

**Comment by gatling-nrl** [comment]
Your suggestion suppressed the exception. The following runs successfully.
```python
fbasis_p1 = skfem.FacetBasis(mesh, basis_p1.elem, facets=mesh.facets_satisfying(is_outer_boundary))
```

But there is still some confusion:

```python
def is_outer_boundary(x):
    return np.logical_or(
        np.isclose(abs(x[0]-.5), .5),
        np.isclose(abs(x[1]-.5), .5),
    )

mesh = skfem.MeshTri().refined(1)
basis_p1 = skfem.Basis(mesh, skfem.ElementTriP1())
basis_p1.get_dofs(facets=is_outer_boundary)
fbasis_p1 = skfem.FacetBasis(mesh, basis_p1.elem, facets=mesh.facets_satisfying(is_outer_boundary))

points, weights = fbasis_p1.quadrature
global_points = fbasis_p1.mapping.F(points)
plt.subplots(figsize=(5,5))
plt.plot(global_points[0], global_points[1], 'or')
skfem.visuals.matplotlib.draw(mesh, ax=plt.gca())
plt.xlabel('x[0]'); plt.ylabel('x[1]');
```

![image](https://user-images.githubusercontent.com/38136423/144375120-72bf4a57-5ae1-4806-aac0-a35433d676f4.png)

Why are these quadrature points not all on the facets I specified?  Identical code produces plots that make sense for `CellBasis` (see https://github.com/kinnala/scikit-fem/discussions/817)

**Comment by kinnala** [comment]
Change `mapping.F` to `mapping.G` which is the boundary mapping part of `Mapping`.
![Figure_1](https://user-images.githubusercontent.com/973268/144378054-55186f7e-1959-4eb4-bc09-03a5f46fcb5c.png)

**Comment by kinnala** [comment]
If you want to see only the facets you specified, then I suggest you plot `global_points = fbasis_p1.global_coordinates().value`:

![Figure_1](https://user-images.githubusercontent.com/973268/144378333-68ee6873-3c3e-4546-921e-1b96da00f0cd.png)

**Comment by kinnala** [comment]
`FacetBasis` (which is an alias to `BoundaryFacetBasis`) will by default only consider outer boundaries so your `facets=...` is not really necessary.

**Comment by kinnala** [comment]
If you want to do internal facets there is `InteriorFacetBasis` but there is a caveat related to `side` keyword argument since the value of the basis on the internal facet is not unique in general, e.g., Crouzeix-Raviart element is not continuous across the entire internal facet.

**Comment by kinnala** [comment]
> And I discovered when writing the extended doc draft that `(..., facets=*)` makes zero sense for `P0`. But it doesn't raise an exception explaining that. So I would also nominate an issue for fixing the exceptions that are raised when you supply `(..., facets=*)` or `(..., elements=*)` in a context that makes no sense.

Sometimes it is hard for me to predict what makes no sense. If you add exceptions to everything, then you end up blocking some kind of unexpected use cases that other people were using in their code. I recently had this issue with `meshio` where I resorted to forking the library and commented one line which was essentially `raise Exception`.

**Comment by gatling-nrl** [comment]
> I resorted to forking the library and commented out one line which was essentially raise Exception.

I guess except for really fatal things, why should a library raise Exception? It should have raised MeshioExceptionBlahBlah so you can just `try` `except` around it instead of forking and commenting. Or maybe your saying you needed `meshio.something()` to complete, and knew that it could, but instead it raised.  That is annoying.

>  If you add exceptions to everything

Numpy faced this problem with divide by zero, etc and decided to add options to make that an exception or not. So you're right, it is sometimes very hard to know where to draw the lines. What should a function do when it can complete, but knows its return value is questionable/invalid?

> Edit 2: Now looking at it more carefully, why does it not make sense? I think it works as expected, i.e., evaluates P0 on quadrature points on the boundary?

I am under the impression that `P0` is in general undefined on the facets because that's the exact spot where it is discontinuous. Therefore evaluating functions there would be invalid mathematically and unpredictable computationally.

**Comment by kinnala** [comment]
> I guess except for really fatal things, why should a library raise Exception? It should have raised MeshioExceptionBlahBlah so you can just `try` `except` around it instead of forking and commenting. Or maybe your saying you needed `meshio.something()` to complete, and knew that it could, but instead it raised. That is annoying.

That's exactly the case, it stopped short because of the exception even though the rest of the function would work just fine.

> I am under the impression that P0 is in general undefined on the facets because that's the exact spot where it is discontinuous. Therefore evaluating functions there would be invalid mathematically and unpredictable computationally.

Mathematically we have the concept of a "trace". The value of the trace depends on the side which is used to approach the discontinuity. On external boundary the trace is unique because nothing happens outside of the domain. On internal facets you pick this by the kwarg side: InteriorFacetBasis(..., side=0) or side=1.

**Comment by gatling-nrl** [comment]
> If you want to see only the facets you specified, then I suggest you plot global_points = fbasis_p1.global_coordinates().value

This worked, and worked for `CellBasis` as well. Is `global_coordinates()` the recommeded way to access the quadrature locations? (I'll update https://github.com/kinnala/scikit-fem/discussions/817 if so.)

**Comment by kinnala** [comment]
> > If you want to see only the facets you specified, then I suggest you plot global_points = fbasis_p1.global_coordinates().value
> 
> This worked, and worked for `CellBasis` as well. Is `global_coordinates()` the recommeded way to access the quadrature locations? (I'll update #817 if so.)

Yes in the sense that it is also used by `w.x` inside the form definitions (`BilinearForm` and `LinearForm`).

**Comment by gatling-nrl** [comment]
Speaking of `BilinearForm` and `LinearForm`



```python
def f(x):
    """arbitrary function definition"""
    return  # array of function evaluated at x

@BilinearForm
def laplace(u, v, w):
    return dot(grad(u), grad(v))

@LinearForm
def rhs(v, w):
    return f(w.x) * v

A = skfem.asm(laplace, basis_p1)
b = skfem.asm(rhs, basis_p1)
```

Is it correct that after the above code, (and taking \phi_i and \phi_j to be the ith and jth basis functions in basis_p1) 

![image](https://user-images.githubusercontent.com/38136423/144455499-dc6132e8-4b40-4c19-b4a1-3e71c3040cff.png)

**Comment by kinnala** [comment]
Yes

**Comment by gatling-nrl** [comment]
And after the above code plus

```python
@skfem.Functional
def test1(w):
    return w['g']

x = skfem.asm(test1, basis_p1, g=f(basis_p1.global_points().value))

@skfem.Functional
def test2(w):
    return f(w.x)

y = skfem.asm(test2, basis_p1)

@skfem.Functional
def test3(w):
    return w['g'](w.x)

z = skfem.asm(test3, basis_p1, g=f)
```

![image](https://user-images.githubusercontent.com/38136423/144479536-66f450fe-39cd-4d61-973f-c9dc7fd3c422.png)

**Comment by kinnala** [comment]
The first works mainly due to backwards compatibility but I'd discourage using it in the docs. The second one is also correct. I'm not sure about the third one though. I need to think what happens there.

**Comment by gatling-nrl** [comment]
> Is it correct that after the above code, (and taking \phi_i and \phi_j to be the ith and jth basis functions in basis_p1)

> Yes

```python
A = skfem.asm(laplace, [basis1_p1, basis2_p1], basis3_p0])
```
compute

![image](https://user-images.githubusercontent.com/38136423/144929136-cf910279-ce72-4c07-9717-ca86fdead096.png)

using the union of the basis functions and possibly over subdomains of Omega?

Is this an equivalent piece of code?

```python
A = np.vstack([
    skfem.asm(laplace, basis1_p1),
    skfem.asm(laplace, basis2_p1),
    skfem.asm(laplace, basis3_p0),
])
```

**Comment by kinnala** [comment]
`skfem.asm` will loop over all possible combinations of bases, assemble the same form for all combinations, and sum the resulting matrices. This functionality was mainly created for stuff that have jump terms as explained here: https://scikit-fem.readthedocs.io/en/latest/howto.html#assembling-jump-terms
