### ISSUE TITLE
Finding dof locations 

### ISSUE THREAD

**Issue by kinnala** [kinnala/scikit-fem#84]
One should be able to easily find global DOF locations using facilities such as InteriorBasis.get_dofs.

- Make local DOF locations to each element
- Map these to global coordinates
- Make nice interface for fetching them

**Comment by gdmcbain** [comment]
In #113, I noticed another case where this hurts.  Besides coordinate-dependent Dirichlet data #112, in one of the Laplace examples, the exact solution was constructed using `Mesh.p` which only gave nodal values.
 https://github.com/kinnala/scikit-fem/blob/5f1687d32f67e014d21ff477b82eea30332c796a/docs/examples/ex13.py#L63
This is gotten around in #113 by L²-projection, which might be a better idea anyway.  That's easy as we do have access to the coordinates of the quadrature points when writing a linear form.

**Comment by kinnala** [comment]
I guess one could also implement Dirichlet conditions via an explicit L2 projection. This might introduce consistency error but I'm not sure.

**Comment by gdmcbain** [comment]
I hadn't thought of that Dirichlet via L2.  Should work?  Why do you think that it might introduce consistency error?  I suppose I would have usually thought that L²-projection was "truer" (in some functional-analytic sense which I probably can't precise) that mere nodal interpolation.  Is it that to avoid increasing the consistency error a different kind of projection is called for, suited to the correct trace space?

Would this end up giving identical answers (assuming all linear algebraic systems solved exactly) to the Lagrange-multiplier method, except that it's done in two stages (boundary then interior)?  My understanding is that that effectively finds the flux such that the boundary values weakly satisfy the Dirichlet condition, i.e. w.r.t. the L² inner product, and I think that in a finite element space that set of boundary values is unique.

One to add to the sequence of examples proposed in #112 anyway, perhaps.

**Comment by gdmcbain** [comment]
It looks like the coordinates of the DOFs in ElementTriP2 are given by those of the nodes of the mesh followed by the midpoints of the facets:
```python
np.hstack([mesh.p, mesh.p[:, mesh.facets].mean(axis=1)])
```

This matches, for example, what's obtained by _L_&sup2; projection using the `w.x` available inside a `linear_form`.

**Comment by gdmcbain** [comment]
It looks like the coordinates of the DOFs in ElementTriP2 are given by those of the nodes of the mesh followed by the midpoints of the facets:
```python
np.hstack([mesh.p, mesh.p[:, mesh.facets].mean(axis=1)])
```

This matches, for example, what's obtained by _L_&sup2; projection using the `w.x` available inside a `linear_form`.

**Comment by kinnala** [comment]
I wonder if this should be closed now that we found a way to do it through L^2 projection and create an interface for performing the projections instead?

**Comment by kinnala** [comment]
Closing this since it's less relevant after adding `utils.L2_projection`.

**Comment by gdmcbain** [comment]
So if dof locations were to be made available through the API, where would that be? I figure through the InteriorBasis (haven't thought about FacetBasis), since they depend on both the Mesh and the Element. What about a property ib.x? Raising NotImplementedError by default, returning self.mesh.p for P1 and Q1 and [as above](https://github.com/kinnala/scikit-fem/issues/84#issuecomment-462613033) for P2 (and maybe Q2, need to check)?  L2 projection is good, but I feel that it loses some of the simplicity of the early examples. Plus serialization #158.

**Comment by kinnala** [comment]
I can try to sketch how this would work but I first need to understand what's actually useful. User probably wants to have global DOF locations corresponding to some subset of facets (e.g. some entry in Mesh.boundaries) and then the corresponding indexing to fill that information to the solution vector?

**Comment by gdmcbain** [comment]
> User probably wants to have global DOF locations corresponding to some subset of facets (e.g. some entry in Mesh.boundaries)

Yes, that would be the main application.

An occasional one would be comparison with exact solutions as in

https://github.com/kinnala/scikit-fem/blob/0eb2dceb442f4770661db734f45f18e3e17d871f/docs/examples/ex13.py#L42-L44

Then that first line could be replaced with
```python
u_exact = 2 * np.arctan(mesh.p[1], mesh.p[0]) / np.pi
```

**Comment by kinnala** [comment]
Status update. Now in this commit I added `ElementTriP2.doflocs` attribute: https://github.com/kinnala/scikit-fem/commit/778bb42e2de10977526d6b687a6ad633263034dd.

Then you can do stuff like this:
```
In [1]: from skfem import *                                                                   
In [2]: m = MeshTri()                                                                                                                   
In [3]: e = ElementTriP2()                                                                    
In [4]: ib = InteriorBasis(m, e) 
In [5]: ib.mapping.F(e.doflocs.T)                                                            
Out[5]: 
array([[[0. , 1. , 0. , 0.5, 0.5, 0. ],
        [1. , 0. , 1. , 0.5, 0.5, 1. ]],

       [[0. , 0. , 1. , 0. , 0.5, 0.5],
        [0. , 1. , 1. , 0.5, 1. , 0.5]]])
In [6]: ib.element_dofs.T                                                                    
Out[6]: 
array([[0, 1, 2, 4, 6, 5],
       [1, 2, 3, 6, 8, 7]])
```
Now there is a correspondence between the locations in Out[5] and global DOF indices in Out[6].

In order to use this easily, we need to implement a (preferably vectorized) mapping from Out[6] to Out[5]. This can be done (conceptually) in a similar way as in `MeshTri._build_mappings` we build `f2t`.

**Comment by gdmcbain** [comment]
Oh, that's interesting.  That's completely different to what I was going to try, which is just what was sketched above on [2019-02-12](https://github.com/kinnala/scikit-fem/issues/84#issuecomment-462613033).

Note that mappings like that required from Out[6] to Out[5] can take a while, as [profiled](https://github.com/kinnala/scikit-fem/issues/214#issuecomment-505296135) for #214.

Is
```python
np.hstack([mesh.p, mesh.p[:, mesh.facets].mean(axis=1)])
```
cheating? (For `ElementTriP2`, and analogous for others.)  Are there circumstances under which it could break?  I envisaged adding a test that

> This matches, for example, what's obtained by L² projection using the w.x available inside a linear_form.

holds.

**Comment by kinnala** [comment]
Yes that'd work in this case but I'm afraid those expressions can become tedious for complex elements. It also requires relying on some particular ordering of e.g. `mesh.facets` when going for #23 (for example `ElementTriP3`) which I'm planning to do soon.

I think we can reuse the information in `GlobalBasis._build_dofnum` to do the matching. There we are also creating the global DOF indexing for arbitrary elements.

**Comment by gdmcbain** [comment]
Ah, yes, that's obvious now, thanks.
