### ISSUE TITLE
from .basis import *

### ISSUE THREAD

**Issue by gatling-nrl** [kinnala/scikit-fem#852]
https://github.com/kinnala/scikit-fem/blob/84ef5ad81e4d4fd7228f829de8b721c7e648b6c6/skfem/assembly/__init__.py#L54-L56

should be changed to 

```python
from .basis import *
```

My rational is that if you write a new Basis, you already have to update `basis/__init__.py` and that should be enough. I don't see a reason to import something in `basis/__init__.py` that won't be included in the skfem namespace.

And it is in line with other skfem code:

https://github.com/kinnala/scikit-fem/blob/84ef5ad81e4d4fd7228f829de8b721c7e648b6c6/skfem/__init__.py#L3-L7

Can I roll that change into https://github.com/kinnala/scikit-fem/pull/851? Or is there a reason you avoided it in `assembly/__init__.py`?

**Comment by gatling-nrl** [comment]
Oh, geez... and you have 

https://github.com/kinnala/scikit-fem/blob/84ef5ad81e4d4fd7228f829de8b721c7e648b6c6/skfem/assembly/__init__.py#L92-L108

So it actually takes lots of edits to get a new basis in. I wonder if this is from overuse of `__all__`...

**Comment by kinnala** [comment]
I fully acknowledge the overuse of `__all__`. However, I'm personally dependent on this behavior because I do lots of live coding using this package (for students, colleagues, during presentations) so I rely on the commands being short and fast to type.

Doing wildcard imports inside the library is of course a good idea if it reduces the LOC, and `mypy` and `flake8` don't start whining about it. I think those `#noqa` comments have been added to satisfy `flake8`?

**Comment by gatling-nrl** [comment]
Sorry, I didn't mean to criticize the use `from scipy import *`. I meant the default behavior of python is to export everything that doesn't begin with `_`. When I said "overuse of __all__" I meant that in most places I think you can just not define it, and python will do what you want and the code will be easier to maintain. Try it and see :)

I see `__all__` as a way to _restrict_ what things come in from an import, or I guess force the inclusion of something starting with `_`. But since you're using submodules anyway, you already have a natural place to enumerate which things are exported... the `__init__.py` files of the submodules.

**Comment by gatling-nrl** [comment]
Test-passing example of this for `assembly/__init__.py` in #851

**Comment by gatling-nrl** [comment]
Finished off the rest of the `__all__`'s in #851. Let me know if you want me to revert it.
