### ISSUE TITLE
helpers.dot(vector, scalar) returns ValueError:

### ISSUE THREAD

**Issue by gatling-nrl** [kinnala/scikit-fem#856]
```python
sigma = cb_p1.zeros()
u = cb_p1.zeros()

@skfem.Functional
def func(w):
    return dot(w.n, w.sigma * w.u)

func.assemble(cb_p1, sigma=sigma, u=u)
```
```
ValueError:
```
I meant to do `grad(w.u)` which fixes the problem, but thought maybe `dot` could be more informative.

```python
np.dot([1,2,3],[[1,2]])
```
```
ValueError: shapes (3,) and (1,2) not aligned: 3 (dim 0) != 1 (dim 0)
```

**Comment by kinnala** [comment]
That's actually caused by `CellBasis` not having the normal vector `w.n`. However, the error message does not describe it very well so I will change it. I assume you are using #849.

**Comment by gatling-nrl** [comment]
Actually using #851 at the moment.

**Comment by kinnala** [comment]
Now in #849 it is like this: `ValueError: Attribute 'n' not found in 'w'.`

**Comment by kinnala** [comment]
> Actually using #851 at the moment.

Alright, but nevertheless, I think `ValueError` inside `FormExtraParams` didn't have any description since it's inception.

**Comment by gatling-nrl** [comment]
Ohh, I see. This isn't the first time I've gotten cellbasis mixed up. I've got 4 basis right now, CellP0, CellP1, FacetP0, and FacetP1. Its pretty easy to get mixed up. Maybe that should be `AttributeError` instead of `ValueError`? But that might break things.

**Comment by gatling-nrl** [comment]
The other part of the problem is that `grad(w.u)` didn't actually fix things. `grad(w['u'])` was required instead.

**Comment by kinnala** [comment]
Sure, `grad(w.u)` is an upcoming feature in #849.

**Comment by gatling-nrl** [comment]
So, using the right basis, if you actually do `dot(w.n, w.u)` you get 

```
ValueError: operands could not be broadcast together with remapped shapes [original->remapped]: (2,66,2)->(66,2,2) (66,2)->(2,66)
```

Thanks for help on that.

**Comment by gatling-nrl** [comment]
> Sure, grad(w.u) is an upcoming feature in #849.

In #849 `w.u == w['u']`?

**Comment by kinnala** [comment]
> > Sure, grad(w.u) is an upcoming feature in #849.
> 
> In #849 `w.u == w['u']`?

Yeah!

**Comment by gatling-nrl** [comment]
That's awesome! Is it possible for me to merge the current #849 into the current #851?

**Comment by kinnala** [comment]
Sure. I hope to merge #849 to master this night.

**Comment by gatling-nrl** [comment]
Fixed by https://github.com/kinnala/scikit-fem/pull/849
