### ISSUE TITLE
DiscreteField * np.array yields an array, not a DiscreteField

### ISSUE THREAD

**Issue by gatling-nrl** [kinnala/scikit-fem#859]
At the end of `__init__()` for SubdomainFacetBasis, I have

```python
        self.normals *= np.array(flip_list)
        if side == 1:
            self.normals *= -1
```

and #849 was a breaking change. Both `*=` lines now return `np.array` instead of `DiscreteField`. I don't know what is the right thing to do here and anyway SubdomainFacetBasis is probably not going to do it this way in the end. So I'm not too worried about that. 

But I wasn't sure if there are deeper ramifications, and wanted to make sure you were aware of this. Also there might be a gap in test coverage since this wasn't picked up by the tests.

**Comment by kinnala** [comment]
This is on purpose because I wanted to invalidate the extra attrs after operations.
