### ISSUE TITLE
Cholesky factorization for fast time-stepping of symmetric problems

### ISSUE THREAD

**Issue by gdmcbain** [kinnala/scikit-fem#86]
For problems like the heat equation with say Crank&ndash;Nicolson discretization in time and constant time-step, the resulting matrix pencil is the same at each step so it is appealing to factorize it once and for all; e.g. using the Cholesky factorization (since the matrices are symmetric positive-definite).

I see that `cholesky` was imported from `sksparse.cholmod` in `sp.fem` 

https://github.com/kinnala/sp.fem/blob/1398225075c9ab90dbc78616a451f7dd9139ff4c/spfem/utils.py#L71 

(though the factors were not returned or stored) and propose to use that again in scikit-fem.

**Comment by gdmcbain** [comment]
Perhaps this should not be part of the scikit-fem library itself (to avoid another dependency, and a tricky one at that) but just demonstrated in an example; I should be able to do that early next week.

**Comment by gdmcbain** [comment]
It is convenient here that [`skfem.utils.condense`](https://github.com/kinnala/scikit-fem/blob/f4722043b8106371e2f49366dcc0f284454c2e85/skfem/utils.py#L17) preserves symmetry.

**Comment by kinnala** [comment]
I have not included any built-in support since I thought CHOLMOD was GPL licensed. Now that I briefly rechecked, it seems that it's, in fact, LGPL licenced so that dynamic linking should be fine. I have to verify this.

**Comment by kinnala** [comment]
It seems to me that entire SuiteSparse is LGPL and it makes me wonder why anyone would buy a commercial license. Oh well, nevertheless, example is totally fine.

**Comment by gdmcbain** [comment]
Thanks for checking. I had forgotten about the legal issue, though that is the _raison d'être_ of scikit-sparse.

**Comment by gdmcbain** [comment]
I do also have a pure Python scipy.sparse implementation which I had to write because it was too hard to rely on CHOLMOD for deployment to Microsoft Windows. From memory that was workable; although slower, it didn't matter because the one factorization was amortized over thousands of time-steps. I'll see what the situation is with Windows these days.

**Comment by gdmcbain** [comment]
> This might work better in Windows: https://anaconda.org/conda-forge/scikit-sparse (#98)

Sadly no.  In a fresh Python 3.7 _Anaconda for Windows_ environment terminal in _Microsoft Windows 10_ I tried
```shell
conda install -c conda-forge scikit-sparse
```
but that failed
```
Solving environment: failed

PackagesNotFoundError: The following packages are not available from current channels:

  - scikit-sparse

Current channels:

  - https://conda.anaconda.org/conda-forge/win-64
  - https://conda.anaconda.org/conda-forge/noarch
  - https://repo.anaconda.com/pkgs/main/win-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/free/win-64
  - https://repo.anaconda.com/pkgs/free/noarch
  - https://repo.anaconda.com/pkgs/r/win-64
  - https://repo.anaconda.com/pkgs/r/noarch
  - https://repo.anaconda.com/pkgs/pro/win-64
  - https://repo.anaconda.com/pkgs/pro/noarch
  - https://repo.anaconda.com/pkgs/msys2/win-64
  - https://repo.anaconda.com/pkgs/msys2/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.
```
That search bar only leads to the quoted URL.

**Comment by gdmcbain** [comment]
Anyway, aside from the issue with Microsoft, this has been demonstrated at least on Linux #98 so I'll close this and open a new issue later if this needs to be deployed to Windows.
