### ISSUE TITLE
Rogue element in mesh.f2t?

### ISSUE THREAD

**Issue by gatling-nrl** [kinnala/scikit-fem#868]
```python
mesh = skfem.io.meshio.from_file('domain.msh', None)
cbasis = skfem.CellBasis(mesh, skfem.ElementTriP0())

a = mesh.facets_satisfying(lambda x: abs(np.sqrt(x[1]**2 + x[0]**2) - electrode_radius) < 0.005)

u = cbasis.zeros()
u[cbasis.get_dofs(elements=mesh.f2t[:,a])] = 1

fig,ax = plt.subplots(1,1,figsize=(8,8))
skfem.visuals.matplotlib.plot(cbasis, u, ax=ax, cmap='Blues', shading='gouraud')
skfem.visuals.matplotlib.draw(mesh, ax=ax)
```
![image](https://user-images.githubusercontent.com/38136423/150603978-c8ff7dbe-0c6c-4773-bd53-f14d11596f98.png)

**Comment by kinnala** [comment]
Second row of `f2t` is -1 if facet is on the boundary. Too bad it refers to a triangle because the indices loop over.

**Comment by kinnala** [comment]
Try this:
```python
u[cbasis.get_dofs(elements=mesh.f2t[0, a])] = 1
```

**Comment by gatling-nrl** [comment]
Yes, I had already changed it to that, and it does work. Why does -1 refer to a triangle? That part I don't understand

**Comment by gatling-nrl** [comment]
Is this correct?

```python
    @property
    def f2t(self):
        """"facets to triangles

        i.e. ith column contains triangles corresponding to ith facet
        the first row always refers to a triangle.
        the second row is
            -1 for boundary facets
            a triangle index for interior facets
        """
```

**Comment by kinnala** [comment]
In `get_dofs` it's slicing columns of some array of shape `(dofs-per-element, number-of-elements)` and if you use -1 in numpy array slice it will use the last column.

**Comment by gatling-nrl** [comment]
Ohh, because it's using -1 to index from the end of the array... doh

**Comment by kinnala** [comment]
Could do a guard in `get_dofs` to check that the indices are positive.

**Comment by kinnala** [comment]
> Is this correct?
> 
> ```python
>     @property
>     def f2t(self):
>         """"facets to triangles
> 
>         i.e. ith column contains triangles corresponding to ith facet
>         the first row always refers to a triangle.
>         the second row is
>             -1 for boundary facets
>             a triangle index for interior facets
>         """
> ```

yup

**Comment by gatling-nrl** [comment]
> In get_dofs it's slicing columns of some array of shape (dofs-per-element, number-of-elements) and if you use -1 in numpy array slice it will use the last column.

Yeah, I just realized. Is that a useful "feature"?

> Could do a guard in get_dofs to check that the indices are positive.

That seems like a good idea. Since you're using -1 as a NULL value....

**Comment by gatling-nrl** [comment]
> Could do a guard in get_dofs to check that the indices are positive.

It looks like it would actually be in `.normalize_elements` etc.  I assume `-1` should be treated as an invalid index in facets too?

But in master `normalize` is in `AbstractBasis` and in #851 and in #865 it's moved to `Mesh`. It's going to make a merge mess if a new PR was started the -1 check.

Are you happy with moving those to `Mesh`? Maybe can we merge moving those functions separately from all the rest?

**Comment by gatling-nrl** [comment]
I propose something like

```python
    def normalize_facets(self, facets):
        """Generate an array of facet indecies.

        Parameters
        ----------
        elements
            Criteria of which facets to include. Function has different
            behavior based on the type of this parameter.
        """
        if isinstance(facets, int):
            # Make  normalize_facets([1,2,3]) have the same behavior as
            # normalize_facets(np.array([1,2,3]))
            facets = np.array([facets])
            # allow to drop through to the next if statement so value guards
            # are in one place only.
        if isinstance(facets, ndarray):
            # Assume the facets have already been normalized
            if (facets < 0).any():
                raise ValueError('Negative numbers are not valid facet'
                                 ' indices')
            return facets
```
and
```python
    def normalize_elements(self, elements):
        """Generate an array of element indecies.

        Parameters
        ----------
        mesh
            The Mesh on which the elements are defined.
        elements
            Criteria of which elements to include. Function has different
            behavior based on the type of this parameter.
        """
        if isinstance(elements, int):
            # Make  normalize_elements([1,2,3]) have the same behavior as
            # normalize_elements(np.array([1,2,3]))
            elements = np.array([elements])
            # allow to drop through to the next if statement so value guards
            # are in one place only.
        if isinstance(elements, ndarray):
            # Assume the elements have already been normalized
            if (elements < 0).any():
                raise ValueError('Negative numbers are not valid element'
                                 ' indices')
            return elements
