### ISSUE TITLE
FacetBasis and ElementTriRT0 fails

### ISSUE THREAD

**Issue by kinnala** [kinnala/scikit-fem#869]
I think there is some issues with broadcasting because of the following failure:
```python
In [1]: from skfem import *
In [2]: FacetBasis(MeshTri(), ElementTriRT0())
...
ValueError: operand has more dimensions than subscripts given in einstein sum, but no '...' ellipsis provided to broadcast the extra dimensions.
```

**Comment by kinnala** [comment]
This is actually about the missing implementation in `ElementHdiv`. I tried to make a quick fix but requires some careful thinking around the vectorization to get it correct.

**Comment by gatling-nrl** [comment]
I just encountered this as well, trying to calculate accurate total fluxes using e.g. [ex37.py](https://github.com/kinnala/scikit-fem/blob/master/docs/examples/ex37.py) and mentioned it [here](https://github.com/kinnala/scikit-fem/discussions/883#discussioncomment-2553346)
