### ISSUE TITLE
DofsView with all DOFs

### ISSUE THREAD

**Issue by kinnala** [kinnala/scikit-fem#871]
Calling `basis.get_dofs()` matches all boundary DOFs and doing `basis.get_dofs(elements="subdomain")` will match the given subdomain. I think there should be an easy way to get all DOFs from all elements.

Should it be `basis.get_dofs(elements=True)` or something?

**Comment by kinnala** [comment]
Now it's like `basis.get_dofs(elements=lambda x: 1 + 0 * x[0])`.

**Comment by gdmcbain** [comment]
Yeah, or to avoid the `Union` we could introduce a new kwarg `all: bool = False`.

**Comment by gatling-nrl** [comment]
This is also available as `basis.dofs.get_element_dofs(elements=None)`, although saying `elements=None` to get all elements is pretty misleading. 

`get_dofs` has a very long doc string and I think part of what's going on is that its really two functions in a single `def`. This line in particular gives that away

https://github.com/kinnala/scikit-fem/blob/64da34c4445ec49eda163f369b54fbdf895ff673/skfem/assembly/basis/abstract_basis.py#L239-L241

An alternative to continuing to overload `get_dofs` is to split it along its natrual boundary into `get_element_dofs` and `get_facet_dofs`  or if you feel terse, maybe `get_edofs` and `get_fdofs`.

Then you don't need the `facets=` and `elements=` kwargs anymore (the first positional argument can be these things)

`get_fdofs()` -> the whole boundary
`get_edofs()` -> all the elements
`basis.get_dofs(elements="subdomain")` -> `basis.get_edofs("subdomain")`

```python
def get_dofs(*args, **kwargs):
    warn('depricated')
    get_fdofs(*args, **kwargs)
```

**Comment by gatling-nrl** [comment]
A better deprecation function
```python
def get_dofs(self, facets=None, elements=None, skip=None):
    warn('depricated')
    if elements is not None and facets is not None: 
        raise ValueError
    elif elements is not None:
        return self.get_edofs(elements, skip)
    else:
        return self.get_fdofs(facets, skip)
```
Doing this the original question is resolved by using `basis.get_edofs()` but there would still be no way to get all element dofs using `basis.get_dofs()` directly. Pretty sure this deprecation function retains the original behavior exactly.

**Comment by gatling-nrl** [comment]
I did also experiment a little while back with replacing

```python
    if elements is not None and facets is not None: 
        raise ValueError
```

with a `join` kwarg that could have the values `intersection`, `union`, etc that specified how to combine the different subsets of dofs specified by the elements and facets kwargs.  In this paradigm, `None` was a stand in for `all` and `join` defaulted to `intersection`.  It ended up being pretty hard to replicate backwards compat this way though. Still, figured I'd mention it sense you're thinking about editing `get_dofs`

**Comment by kinnala** [comment]
np.arange(basis.N, dtype=int) returns all DOFs.

**Comment by gatling-nrl** [comment]
> np.arange(basis.N, dtype=int) returns all DOFs.

but not as a DofsView.

**Comment by kinnala** [comment]
I'm against deprecating get_dofs. It has had too much breaking changes in the past and now I'll leave it alone if possible.

But there are some features we still need.
- All DOFs
- DOFs matching set of nodes
- DOFs matching set of edges in 3D

**Comment by gdmcbain** [comment]
Can one get all the DoFs of the domain by creating a "subdomain" that is actually coextensive with the domain then getting the DoFs of that improper subdomain?

I often do this inadvertently and harmlessly in Gmsh since the domain has to be declared as a Physical Line/Surfsce/Volume in 1/2/3-D for the cells to be saved and so looks like a subdomain anyway.

**Comment by gatling-nrl** [comment]
> Can one get all the DoFs of the domain by creating a "subdomain" that is actually coextensive with the domain then getting the DoFs of that improper subdomain?

I too thought about this angle.  something like `get_dofs(elements="__all__")` but it feels very unusual/irregular. What about not deprecating `get_dofs` but making it be a convivence function like I wrote, and putting the expanded functionality in the sub-functions?

There's also making dedicated sentinel values.   `ALL_ELEMENTS=object()` and then `basis.get_dofs(elements=skfem.ALL_ELEMENTS)`. 

Nothing I've thought of really seems like a great answer though. A lot is being asked of this function.

By the way, when talking about how kwargs will work between 2d and 3d, is this the convention?  If you were going to add an `edges` or a `nodes` kwarg, would you add it like this table?

| thing  | 2d      | 3d      |
|--------|---------|---------|
| point  | edge    | node    |
| line   | facet   | edge    |
| area   | element | facet   |
| volume | n/a     | element |

**Comment by kinnala** [comment]
edge only exists for 3D, something joining two nodes.

**Comment by gatling-nrl** [comment]
(I updated the table... is that how the kwargs would mean if you added `nodes` and `edges` kwargs?)

> But there are some features we still need.

> All DOFs
> DOFs matching set of nodes
> DOFs matching set of edges in 3D

Still other things come up sometimes:

Facet dofs interior to a subdomain. 
Facet dofs inside a subdomain that bound only one element.
Element dofs of elements with at least one facet on a given boundary.
Element dofs of elements that contain at least one of the specified nodes.
Etc.
Unions/Intersections/Differences/Complements of any of these subsets.  (Unions are currently supported with `np.hstack`)

I use `get_dofs` all the time to import data into a basis. The more flexible the query power, the better.
