### ISSUE TITLE
element_finder. Points of the mesh raise ValueError: Point is outside of the mesh.

### ISSUE THREAD

**Issue by HadrienNU** [kinnala/scikit-fem#880]
When trying to apply element_finder on points of the mesh, I sometimes get "ValueError: Point is outside of the mesh." For a simple sample code (the mesh is joined as [mesh.zip](https://github.com/kinnala/scikit-fem/files/8125586/mesh.zip) )

```
m = skfem.MeshTri.load("mesh.vtk") 
elem_finder = m.element_finder() 
print(elem_finder(*m.p))
```

I trace it down to a numerical precision issue. For MeshTri, whatever the points is inside of the element is determined with

`  inside = ((X[0] >= 0) * (X[1] >= 0) * (1 - X[0] - X[1] >= 0))`

and when X[0]=0.0 and X[1]=1.0, I can get 1 - X[0] - X[1]  = -2.22044605e-16. This leads to the point be declared outside of any element.

Two possible way to solve the issue, either replace the 0.0 above by `-np.finfo(X.dtype).eps` or round `1 - X[0] - X[1] `.

**Comment by kinnala** [comment]
Thanks for the report, this is hopefully fixed by #898.
