### ISSUE TITLE
piecewise-definition of coefficients on subdomains

### ISSUE THREAD

**Issue by gdmcbain** [kinnala/scikit-fem#89]
Consider a Laplace equation with variable coefficient, &nabla;&sdot; (_k_ &nabla; _u_) = 0, with _k_ piecewise-constant on ‘regions’ or ‘subdomains’; e.g. steady conduction of heat between two blocks of different thermal conductivity (with no thermal contact resistance).

I think that such problems could also be done with mortar methods (which I see from ex04 are implemented, at least for two-dimensional problems, via `InterfaceMesh1D`); however, monolithic approaches can be convenient too.  The issue here is to assign different values to _k_ depending on which submesh an element belongs to, e.g. as defined in Gmsh as `Physical Surface` (in two dimensions).  Should _k_ be defined with `ElementTriP0`?  And then populated using the `cell_data` returned by `pygmsh.generate_mesh` or the `.cell_data` attribute of the `meshio.Mesh` returned  by `meshio.read`&mdash;I don't think `skfem.mesh.from_meshio` currently does this, it only looks for tags on facets, e.g. for mixed boundary conditions.

**Comment by kinnala** [comment]
The additional parameter `w` given to `asm`, i.e.
```python
asm(bilinf, basis, w=w)
```
has shape number-of-elements x number-of-quadrature-points.

Each row corresponds to a single element. If the material field is constant within each element, you can simply create 1D array of length `mesh.t.shape[1]` (number-of-elements) and replicate this by the number of quadrature points. The result can be passed to `asm`.

**Comment by kinnala** [comment]
Ok, now that I meditated this for a while: I think we should create a method to `GlobalBasis` (say `GlobalBasis.indicator`) which takes in Submesh and outputs 2-d array which can be passed to `asm` via the keyword argument `w`.

This 2-d array represents the indicator function, i.e. it is 1 if the respective quadrature point belongs to the Submesh and 0 otherwise.

These indicator function arrays can be multiplied with specified values and summed together at will.

What do you think?

**Comment by gdmcbain** [comment]
That would be very useful for switching on a term in a subdomain, yes.   Sticking with the example of the heat equation for concreteness, it's very common for tbe source term to be confined to a region.  The Joule-heated wire in an insulator is a textbook case.

For the piecewise-constant conductivity though, this style would involve one `asm` for each region and there could be a few of those, so the P0 approach, simplified as above ('simply create') would be more convenient.

I think both idioms should be available and both work well side by side.  Both are available in the FreeFem++ language, for example.

**Comment by kinnala** [comment]
Here is a method for `InteriorBasis`:
```python
def indicator(self, submesh):
    ind = np.zeros((self.nelems, len(self.W)))
    ind[submesh.t, :] = 1.0
    return ind
```
A similar one could be created to `FacetBasis` to indicate facet subsets.

Then you could create Submeshes and input them to `InteriorBasis.indicator`:
```python
left_ind = basis.indicator(m.submesh(lambda x, y: x<0.0))
right_ind = basis.indicator(m.submesh(lambda x, y: x>0.0))
```
During assembly you could define piecewise constant fields like this:
```python
asm(bilinf, basis, w = 3.0*left_ind +2.0*right_ind)
```

**Comment by gdmcbain** [comment]
I've found a reference for the [aforementioned](https://github.com/kinnala/scikit-fem/issues/89#issuecomment-436378407) insulated wire:
* Carslaw, H. S., & J. C. Jaeger (1959). _Conduction of Heat in Solids_ (2nd ed.). Oxford University Press. §7.2.V, pp 191–192

This might be a better example than #90 .  It demonstrates both features of subdomains:
* subdomain-dependent coefficient (the thermal conductivity)
* variational forms only active in a subdomain (the Joule heating)

In variational form, with a slight change of notation (so that _h_ becomes a heat transfer coefficient), the problem is (grad _u_, _k_ grad _T_) + h [_u, T_] = (_u, A_) where the square brackets denote the inner product over the boundary and k = k0 for 0 < r < a and k1 for a < r < b and A = A0 in 0 < r < a and 0 in a < r < b.

**Comment by gdmcbain** [comment]
I got that working in insulated.py on branch piecewise-89 #90.

I used a very quick hack in `skfem.mesh.mesh.from_meshio` https://github.com/kinnala/scikit-fem/blob/a7ca4936db69ed7ce62698110c5b599a64b88306/skfem/mesh/mesh.py#L267
which will probably want some thought and then some tidying.

This is then used in the script: https://github.com/kinnala/scikit-fem/blob/a7ca4936db69ed7ce62698110c5b599a64b88306/docs/examples/insulated.py#L60 and for the subdomain-dependent coefficients as https://github.com/kinnala/scikit-fem/blob/a7ca4936db69ed7ce62698110c5b599a64b88306/docs/examples/insulated.py#L70-L71 
and the subdomain-dependent linear form as https://github.com/kinnala/scikit-fem/blob/a7ca4936db69ed7ce62698110c5b599a64b88306/docs/examples/insulated.py#L77-L84 .

I haven't checked the result against the closed-form solution yet but it looks O. K.

![insulated](https://user-images.githubusercontent.com/1588947/48243488-c804f300-e434-11e8-9cc5-15367e0c8095.png)

**Comment by kinnala** [comment]
Yes, I can see why one would like to have all data outputted by meshio accessible.

I propose that we create a single attribute `Mesh.external` or `Mesh.ext` which contains all the field data, cell data, etc. of the respective meshio object (e.g. `Mesh.ext.cell_data`) and where the word _external_ or _ext_ emphasizes that we aim not to document its contents within scikit-fem since it might depend on the format.

Still, I will probably at some point improve the wrapper `from_meshio` to create Submesh-objects from subdomains since I find them to be convenient regarding my future plans. I'll probably move the gmsh-specific parts of `from_meshio` into a separate method at some point.

**Comment by gdmcbain** [comment]
Yes, I was starting to think of something like a `.external` attribute too.  It could very well be that what's returned by `meshio.read` changes; the resolution of nschloe/meshio#175 doesn't seem like the last word on how to serialize subdomains.

**Comment by kinnala** [comment]
Check 37be054.

**Comment by gdmcbain** [comment]
Thanks for the review here. This is a very useful feature.  

I'll probably continue to tweak the user-level code in the insulated-wire example #90 as I begin to make real use of the feature myself, but I think this issue can be closed for now.

Later I might also try comparing this monolithic approach with one based `MeshInterface1d` for the same boundary value problem.
