### ISSUE TITLE
mesh.save and mesh.load broken by upstream changes in meshio

### ISSUE THREAD

**Issue by gdmcbain** [kinnala/scikit-fem#9]
The cause here is the same as in #8, but it doesn't involve the intermediate package pygmsh.

I ran the suite of examples with
```shell
parallel python {} ::: examples/ex*.py
```
and found that `examples/ex9.py` raises a `TypeError` on calling `m.save`.

**Comment by gdmcbain** [comment]
Also ex11.py.

**Comment by kinnala** [comment]
This seems to be fixed in #10.
