### ISSUE TITLE
Support scalars in extra parameters

### ISSUE THREAD

**Issue by gatling-nrl** [kinnala/scikit-fem#903]
For example:

```python
@skfem.LinearForm
def C_form(u, w):
    return w.zl * u

C = C_form.assemble(basis.e0.p1, zl=1.)
```
```
ValueError: The given type '<class 'float'>' for the list of extra form parameters w cannot be converted to DiscreteField.
```

It may be as simple as adding to https://github.com/kinnala/scikit-fem/blob/4d7d5ab59310236440bb97e710f243da2501e2e2/skfem/assembly/form/form.py#L84

```python
elif isinstance(w[k], (int, float, complex)):
    # scalar numeric values are okay
    continue
```

Although there is probably a better test for "is this a scalar numeric value"....

**Comment by kinnala** [comment]
Could you put it into a tuple and use that? z1=(1.0,)

**Comment by gatling-nrl** [comment]
That does seem to work, but it also works if I supply `z=(1., 2.)` and I realize I don't understand what the tuple index is doing.

What does it mean to write
```python
@LinearForm
def form(u, _):
    return (1., 2.) * u
```

**Comment by kinnala** [comment]
I don't think it means anything. I mean you take w.z1[0] inside the form.

**Comment by gatling-nrl** [comment]
I see, the tuple is a way of bypassing the check and getting in anything you want...  I can do that, but I still vote to make scalars a valid type of extra parameter.

If you want to include that, it looks like checking against `numbers.Number` is the way to go. All of these evaluate true. Otherwise can close the issue, since the tuple hack does get the job done.

```python
import numbers
import numpy as np

isinstance(complex(), numbers.Number)
isinstance(1, numbers.Number)
isinstance(1., numbers.Number)
isinstance(1j, numbers.Number)
isinstance(np.uint16(), numbers.Number)
isinstance(np.complex64(), numbers.Number)
```
