### ISSUE TITLE
Plane strain/stress

### ISSUE THREAD

**Issue by kinnala** [kinnala/scikit-fem#940]
### Discussed in https://github.com/kinnala/scikit-fem/discussions/939

<div type='discussions-op-text'>

<sup>Originally posted by **SebfraOslo** October 19, 2022</sup>
Hi, 

Is it possible to specifiy plane stress or plane strain conditions in the scikit-fem elastic model (linear_elastcicity and linear_stress)?

Thank you
Sebastien</div>

**Comment by kinnala** [comment]
The first job is to derive the constitutive equation for plane stress. As we are using the Lamé parameters in `skfem.models.elasticity`, it would make sense to do it here also.

**Comment by kinnala** [comment]
@SebfraOslo actually now I'm wondering if #941 is enough?

**Comment by SebfraOslo** [comment]
Yes, it is working. It passed my tests.

Thank tou
Sebastien

**Comment by kinnala** [comment]
Ok, merging.
