### ISSUE TITLE
extract element stiffness matrices 

### ISSUE THREAD

**Issue by ywan459** [kinnala/scikit-fem#943]
Hi I am working/studying on the algorithm of topological optimization. I am thinking to implement the algorithm on a more general FEA framework, e.g. scikit-fem. The algorithm is quite straightforward that the element stiffness matrices multiply the design variables (element based fraction) to minimize the overall system energy. 

I have installed the package, and tested a few examples. It was OK. I have tried to trace the codes and found the general stiffness matrix assembled in asm function (in assembly/__init__.py). By reading the code, I have also found under the form folder, the linear, bilinear and trilinear modulus seems contain the codes calculating the "local stiffness matrices", but the given linear elastic example (ex11.py) has never visited them. I am not sure where is the right place to start with, and can I extract the element stiffness matrix one-by-one and multiple some number, and then put it back to the global matrix? 

Thanks!

Regards
ywan459

**Comment by kinnala** [comment]
It is possible but currently an undocumented feature.

The idea is to create COOData object instead of scipy sparse matrix. I'm not at a computer right now, but I try to remember.

Instead of bilinf.assemble(basis) try doing bilinf.coo_data(basis). Then try using tolocal() and fromlocal() methods of the COOData object.

**Comment by ywan459** [comment]
Hi Kinnala, thank for the fast response. 

I have checked the COOData class (in coo_data.py modulus). By reading the code, it seems can get the local stiffness matrices and push the updated one back to the general stiffness matrix, but I am still not sure how to apply this class here. It requires at least three arguments, data, shape and local shape to initialize the instance. How do we use this class to extract and push back? I am use following snippet (from ex11.py) to help myself to understand its usage. Thank you very much.  

`
import numpy as np
from skfem import *
from skfem.models.elasticity import linear_elasticity, lame_parameters
from skfem.assembly.form.coo_data import COOData

m = MeshHex().refined(3)
e1 = ElementHex1()
e = ElementVector(e1)
ib = Basis(m, e, MappingIsoparametric(m, e1), 3)
linpb = linear_elasticity(*lame_parameters(1e3, 0.3))

# commented the general assembly matrix procedure
#K = asm(linpb, ib)

`

**Comment by kinnala** [comment]
I believe the issue is now in your BilinearForm. Because you defined e as ElementVector, it means u and v inside the lambda are of shape (3, nelems, nqp). However, output of the lambda should have shape (nelems, nqp). Perhaps you want to do something like u[0] * v[0] instead?

**Comment by kinnala** [comment]
There is a section in the docs which shows one way to debug the forms: https://scikit-fem.readthedocs.io/en/latest/advanced.html#anatomy-of-forms

**Comment by kinnala** [comment]
Here is a snippet which should get you started:
```python
from skfem import *
from skfem.models.elasticity import *
m = MeshHex().refined(2)
print(m.t.shape)  # (8, 64)
basis = Basis(m, ElementVector(ElementHex1()))
data = linear_elasticity().coo_data(basis)
print(data.tolocal().shape)  # (64, 24, 24)
```
You can see we have 64 elements and 64 local stiffness matrices of size 24 x 24.

**Comment by ywan459** [comment]
> Here is a snippet which should get you started:
> 
> ```python
> from skfem import *
> from skfem.models.elasticity import *
> m = MeshHex().refined(2)
> print(m.t.shape)  # (8, 64)
> basis = Basis(m, ElementVector(ElementHex1()))
> data = linear_elasticity().coo_data(basis)
> print(data.tolocal().shape)  # (64, 24, 24)
> ```
> 
> You can see we have 64 elements and 64 local stiffness matrices of size 24 x 24.

This is great. I use the following snippets with the coo_data concepts to write the ex1.py linear elasticity example. I have compared with the original ex1.py, the results are identical. I will keep working on the algorithm. Thank you very much!

``` python

from skfem import *
from skfem.models.elasticity import *
import numpy as np

m = MeshHex().refined(2)

basis = Basis(m, ElementVector(ElementHex1()))

# get coo_data object in order to access element-wise stiffness matrices
data = linear_elasticity(*lame_parameters(1e3, 0.3)).coo_data(basis)
# For future application that manipulates the element stiffness matrix
data = data.fromlocal(data.tolocal()) 
# assemble general stiffness matrix 
K = data.tocsr()

dofs = {
    'left' : basis.get_dofs(lambda x: x[0] == 0.0),
    'right': basis.get_dofs(lambda x: x[0] == 1.0),
}

u = basis.zeros()
u[dofs['right'].nodal['u^1']] = 0.3

I = basis.complement_dofs(dofs)

u = solve(*condense(K, x=u, I=I))

sf = 1.0
m = m.translated(sf * u[basis.nodal_dofs])

if __name__ == "__main__":
    from os.path import splitext
    from sys import argv
    
    m.save(splitext(argv[0])[0] + '.vtk')

```
