### ISSUE TITLE
Bmat

### ISSUE THREAD

**Issue by SebfraOslo** [kinnala/scikit-fem#945]
Hi,

I am trying to run example 14 and 24. However, they don' run because the function Bmat is not recognized (" name 'bmat' is not defined"). 

Sebastien

**Comment by kinnala** [comment]
There were some recent changes in the library. You need to either use the library version from master or then scroll back the history to the latest release, e.g., https://github.com/kinnala/scikit-fem/tree/7.0.1/docs/examples

Perhaps I need to redefine the links in the documentation to point to the latest release.

**Comment by kinnala** [comment]
In principle, the documentation urls are now fixed. However, there seems to be some mismatch of Sphinx versions at Readthedocs and my computer because the links look a bit different.
