### ISSUE TITLE
FacetBasis for ElementHCurl

### ISSUE THREAD

**Issue by HelgeGehring** [kinnala/scikit-fem#979]
```python
from skfem import *

FacetBasis(MeshTri(), ElementTriN1())
```

It is failing because `ElementHcurl.orient` doesn't allow to pass a `tind` yet :/
I have many ideas what to do with that FacetBasis :) but no clue how to implement that mapping :(

**Comment by kinnala** [comment]
Sure, this _should_ be a small task and probably the greatest obstacle (for me) is figuring out some reasonable test cases. I'll probably start by integrating some simple functions using `FacetBasis` where I know the analytical result.

**Comment by HelgeGehring** [comment]
Amazing! thanks :)

**Comment by kinnala** [comment]
Now there are some basic sanity checks such as integrating [y, -x] over a part of the boundary in #981.

**Comment by HelgeGehring** [comment]
Having tests sounds good! I'm already testing it, seems to work fine :) Thanks!
