### ISSUE TITLE
Deprecated find_dofs not backwards-compatible

### ISSUE THREAD

**Issue by kinnala** [kinnala/scikit-fem#980]
I added those default `Mesh.boundaries` such as `left` and `right` to all meshes instead of just a few of the `Mesh.init_*` meshes.

However, as reported in #972 this makes the deprecated `Basis.find_dofs` (deprecated in 5.0.0) backwards-incompatible because apparently it is acting differently if given no arguments and `Mesh.boundaries` is set vs. is not set.

Two options to fix this issue:
- Revert adding default `Mesh.boundaries`
- Remove `Basis.find_dofs` in the next release

Perhaps there is a third option of modifying `Basis.find_dofs` to retain the old behaviour as much as possible. However, I don't know if it's really possible.

**Comment by kinnala** [comment]
This must be resolved before the next release happens.

**Comment by HelgeGehring** [comment]
The default boundaries were introduced in #792 (?), i.e. in the same release?

I'd vote for removing it:
- Being deprecated for a year should be enough, 
- Changing it now to be compatible with the behavior before would make it incompatible with the current behavior and probably there's no way to make it compatible with both. So it would just lead to more confusion (?)
