### ISSUE TITLE
FacetBasis for ElementTriN2 not working

### ISSUE THREAD

**Issue by HelgeGehring** [kinnala/scikit-fem#983]
```python
from skfem import *

mesh = MeshTri()
FacetBasis(mesh, ElementTriN2())
```
Fails with
```
ValueError: operands could not be broadcast together with remapped shapes [original->remapped]: (2,2,32,3)->(2,32,3,2) (2,32,3)->(32,3,2) (128,)->(128,newaxis,newaxis) 
```

**Comment by kinnala** [comment]
Thanks, I'll check it out. I'm surprised because it's tested here: https://github.com/kinnala/scikit-fem/blob/5f60afd8b3a2ef387fb4343e0843d4762b6bc977/tests/test_assembly.py#L659

At least what I thought. Now I need to look more carefully.

**Comment by kinnala** [comment]
I'm unable to reproduce this error.

**Comment by kinnala** [comment]
```python
In [1]: from skfem import *

In [2]: m = MeshTri()

In [3]: FacetBasis(m, ElementTriN2())
Out[3]: 
<skfem FacetBasis(MeshTri1, ElementTriN2) object>
  Number of elements: 4
  Number of DOFs: 14
  Size: 2304 B
```

**Comment by HelgeGehring** [comment]
I've pulled the newest version from master and the error now disappeared for me, too, strange. 
I'd guess this was solved before I found it.
Thanks!
